# Dataset Explorer

In [ ]:
!pip install datasets -q

### Explorer Helper

In [ ]:
import pandas as pd
import random
from datasets import load_dataset, get_dataset_split_names

def explore(path, name=None, split="train", n=3, sample=250, seed=42):
    print(f"{'='*60}")
    print(f"  {path}  |  config={name}")
    print(f"{'='*60}")

    # ── Available splits ──────────────────────────────────────────
    try:
        splits = get_dataset_split_names(path, name) if name else get_dataset_split_names(path)
        print(f"  Available splits : {splits}")
    except Exception as e:
        print(f"  Could not fetch split names: {e}")

    # ── Load ──────────────────────────────────────────────────────
    print(f"  Loading split    : '{split}' ...")
    try:
        ds = load_dataset(path, name, split=split) if name else load_dataset(path, split=split)
    except Exception as e:
        print(f"  ERROR loading: {e}")
        return None

    df_full = ds.to_pandas()
    print(f"\n  ── Full dataset stats {'─'*38}")
    print(f"  Total rows  : {len(df_full)}")
    print(f"  Columns     : {df_full.columns.tolist()}")
    print()

    # ── Per-column stats ──────────────────────────────────────────
    for col in df_full.columns:
      print(f"  [{col}]")

      # Type
      print(f"    dtype      : {df_full[col].dtype}")

      # Sample value
      print(f"    sample val : {repr(df_full[col].iloc[0])[:120]}")

      # Null count
      print(f"    nulls      : {df_full[col].isna().sum()}")

      # Unique values or value counts — try, catch if unhashable
      try:
          n_unique = df_full[col].nunique()
          print(f"    n_unique   : {n_unique}")
          if n_unique <= 20:
              print(f"    counts     : {df_full[col].value_counts().to_dict()}")
      except TypeError:
          print(f"    n_unique   : unhashable (list/array column)")

      # Length distribution if iterable
      try:
          lengths = df_full[col].apply(len)
          print(f"    len dist   : {lengths.value_counts().to_dict()}")
      except (TypeError, AttributeError):
          pass

      print()

    # ── Pretty-print n examples ───────────────────────────────────
    print(f"  ── First {n} examples {'─'*38}")
    for i in range(min(n, len(df_full))):
        print(f"  ── Example {i} {'─'*40}")
        for k, v in ds[i].items():
            print(f"  {k:20s}: {repr(v)[:250]}")
        print()

    # ── Sample into DataFrame ─────────────────────────────────────
    random.seed(seed)
    if sample is None:
        df_sampled = df_full.reset_index(drop=True)
    else:
        indices = random.sample(range(len(df_full)), min(sample, len(df_full)))
        df_sampled = df_full.iloc[indices].reset_index(drop=True)
    print(f"  Returning sampled DataFrame — {len(df_sampled)} rows (seed={seed})")
    return df_sampled

## MMLU
Link: https://huggingface.co/datasets/cais/mmlu

In [ ]:
df_mmlu = explore("cais/mmlu", name="all", split="auxiliary_train", n=3, sample=250)

============================================================
  cais/mmlu  |  config=all
============================================================

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md: 0.00B [00:00, ?B/s]

dataset_infos.json: 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

  Available splits : ['test', 'validation', 'dev', 'auxiliary_train']
  Loading split    : 'auxiliary_train' ...

all/test-00000-of-00001.parquet:   0%|          | 0.00/3.50M [00:00<?, ?B/s]

all/validation-00000-of-00001.parquet:   0%|          | 0.00/408k [00:00<?, ?B/s]

all/dev-00000-of-00001.parquet:   0%|          | 0.00/76.5k [00:00<?, ?B/s]

all/auxiliary_train-00000-of-00001.parqu(…):   0%|          | 0.00/47.5M [00:00<?, ?B/s]

Generating test split:   0%|          | 0/14042 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/1531 [00:00<?, ? examples/s]

Generating dev split:   0%|          | 0/285 [00:00<?, ? examples/s]

Generating auxiliary_train split:   0%|          | 0/99842 [00:00<?, ? examples/s]

  ── Full dataset stats ──────────────────────────────────────
  Total rows  : 99842
  Columns     : ['question', 'subject', 'choices', 'answer']

  [question]
    dtype      : object
    sample val : "Davis decided to kill Adams. He set out for Adams's house. Before he got there he saw Brooks, who resembled Adams. Thin
    nulls      : 0
    n_unique   : 98487

In [ ]:
print(df_mmlu["subject"].value_counts())
print()

# Check other splits
for split in ["test", "validation", "dev"]:
    ds = load_dataset("cais/mmlu", "all", split=split)
    print(f"{split}: {len(ds)} rows, sample subjects: {list(set(ds['subject'][:20]))[:5]}")

subject
    250
Name: count, dtype: int64

test: 14042 rows, sample subjects: ['abstract_algebra']
validation: 1531 rows, sample subjects: ['abstract_algebra', 'anatomy']
dev: 285 rows, sample subjects: ['astronomy', 'business_ethics', 'abstract_algebra', 'anatomy']

In [ ]:
# Number of questions per option count
df_mmlu["choices"].apply(len).value_counts()

choices
4    250
Name: count, dtype: int64

In [ ]:
from datasets import get_dataset_config_names
import pandas as pd

# ── Get all subjects ─────────────────────────────────────────────
subjects = get_dataset_config_names("cais/mmlu")

dfs = []

# ── Load full data per subject ───────────────────────────────────
for subj in subjects:
    print(f"\nLoading subject: {subj}")

    df = explore(
        "cais/mmlu",
        name=subj,
        split="auxiliary_train",
        sample=None   # effectively disables sampling
    )

    if df is not None:
        df["subject"] = subj
        dfs.append(df)

# ── Combine ─────────────────────────────────────────────────────
df_mmlu_all = pd.concat(dfs, ignore_index=True)

print("\n" + "="*60)
print("COMBINED DATASET OVERVIEW")
print("="*60)

print(f"Total rows           : {len(df_mmlu_all)}")
print(f"Columns              : {df_mmlu_all.columns.tolist()}")

# ── Column-wise quick stats ──────────────────────────────────────
print("\nColumn summary:")
for col in df_mmlu_all.columns:
    print(f"\n[{col}]")
    print(f"  dtype      : {df_mmlu_all[col].dtype}")
    print(f"  nulls      : {df_mmlu_all[col].isna().sum()}")

    try:
        n_unique = df_mmlu_all[col].nunique()
        print(f"  n_unique   : {n_unique}")
        if n_unique <= 20:
            print(f"  counts     : {df_mmlu_all[col].value_counts().to_dict()}")
    except TypeError:
        print("  n_unique   : unhashable")

# ── Per-subject distribution ─────────────────────────────────────
print("\n" + "="*60)
print("QUESTIONS PER SUBJECT")
print("="*60)

subject_counts = (
    df_mmlu_all["subject"]
    .value_counts()
    .sort_index()
)

print(subject_counts)

print("\nSummary stats:")
print(f"Total subjects       : {subject_counts.shape[0]}")
print(f"Min questions        : {subject_counts.min()}")
print(f"Max questions        : {subject_counts.max()}")
print(f"Mean questions       : {subject_counts.mean():.2f}")

# ── Optional: inspect imbalance ──────────────────────────────────
print("\nTop 5 largest subjects:")
print(subject_counts.sort_values(ascending=False).head())

print("\nTop 5 smallest subjects:")
print(subject_counts.sort_values().head())

Loading subject: abstract_algebra
============================================================
  cais/mmlu  |  config=abstract_algebra
============================================================
  Available splits : ['test', 'validation', 'dev']
  Loading split    : 'auxiliary_train' ...
  ERROR loading: Unknown split "auxiliary_train". Should be one of ['test', 'validation', 'dev'].

Loading subject: all
============================================================
  cais/mmlu  |  config=all
============================================================
  Available splits : ['test', 'validation', 'dev', 'auxiliary_train']
  Loading split    : 'auxiliary_train' ...

  ── Full dataset stats ──────────────────────────────────────
  Total rows  : 99842
  Columns     : ['question', 'subject', 'choices', 'answer']

  [question]
    dtype      : object
    sample val : "Davis decided to kill Adams. He set out for Adams's house. Before he got there he saw Brooks, who resembled Adams. Thin
    nulls      : 0
    n_unique   : 98487

## AQuA-RAT
Math dataset, substitute for MathQA

In [ ]:
# AQuA-RAT — algebra word problems, MCQ with 5 options, clean Parquet format
df_aqua = explore("aqua_rat", name="raw", split="train", n=3, sample=250)

============================================================
  aqua_rat  |  config=raw
============================================================

README.md: 0.00B [00:00, ?B/s]

  Available splits : ['train', 'test', 'validation']
  Loading split    : 'train' ...

raw/train-00000-of-00001.parquet:   0%|          | 0.00/25.4M [00:00<?, ?B/s]

raw/test-00000-of-00001.parquet:   0%|          | 0.00/74.0k [00:00<?, ?B/s]

raw/validation-00000-of-00001.parquet:   0%|          | 0.00/76.1k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/97467 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/254 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/254 [00:00<?, ? examples/s]

  ── Full dataset stats ──────────────────────────────────────
  Total rows  : 97467
  Columns     : ['question', 'options', 'rationale', 'correct']

  [question]
    dtype      : object
    sample val : "Two friends plan to walk along a 43-km trail, starting at opposite ends of the trail at the same time. If Friend P's ra
    nulls      : 0
    n_unique   : 80924
    len dist   : {122: 722, 172: 716, 120: 692, 102: 673, 111: 662, 104: 657, 100: 653, 124: 621, 134: 619, 113: 614, 103: 603, 123: 597, 153: 585, 154: 585, 114: 583, 126: 579, 164: 578, 87: 575, 162: 572, 112: 567, 144: 566, 107: 563, 125: 559, 127: 558, 141: 549, 118: 548, 101: 548, 158: 543, 121: 542, 129: 538, 96: 538, 163: 532, 117: 531, 147: 531, 145: 529, 99: 526, 165: 526, 178: 525, 131: 523, 157: 516, 146: 516, 173: 511, 88: 511, 139: 508, 108: 505, 128: 496, 135: 489, 168: 488, 137: 484, 167: 481, 174: 478, 93: 478, 156: 475, 138: 469, 115: 467, 110: 464, 142: 462, 130: 459, 143: 459, 136: 458, 191: 456, 75: 455, 119: 455, 74: 454, 140: 450, 177: 447, 195: 446, 150: 446, 176: 445, 197: 443, 91: 442, 133: 441, 98: 441, 161: 439, 148: 437, 94: 432, 86: 430, 159: 427, 151: 426, 160: 424, 179: 420, 73: 419, 187: 418, 175: 416, 109: 414, 132: 413, 89: 413, 170: 412, 116: 411, 84: 410, 105: 409, 152: 406, 155: 403, 92: 402, 80: 401, 78: 400, 169: 399, 166: 398, 97: 396, 192: 396, 82: 394, 218: 387, 90: 384, 95: 379, 149: 378, 85: 376, 180: 375, 81: 372, 83: 371, 77: 370, 188: 369, 186: 368, 184: 364, 198: 363, 106: 360, 181: 358, 71: 354, 196: 346, 49: 346, 183: 346, 194: 338, 76: 335, 48: 335, 182: 333, 72: 328, 193: 327, 69: 327, 79: 322, 205: 320, 50: 316, 65: 315, 199: 314, 185: 310, 209: 308, 45: 305, 171: 296, 70: 290, 200: 287, 211: 287, 201: 284, 56: 283, 189: 282, 216: 278, 204: 276, 60: 276, 68: 275, 214: 274, 207: 273, 227: 271, 190: 271, 54: 269, 43: 268, 203: 267, 66: 267, 63: 264, 219: 264, 46: 260, 242: 258, 62: 257, 224: 256, 53: 254, 67: 252, 64: 252, 61: 251, 208: 249, 206: 247, 47: 246, 55: 245, 51: 243, 258: 242, 220: 242, 59: 239, 223: 239, 212: 237, 237: 237, 215: 236, 228: 234, 217: 232, 231: 232, 235: 226, 44: 226, 249: 224, 250: 223, 210: 222, 225: 220, 57: 218, 244: 218, 40: 215, 221: 213, 246: 213, 213: 212, 232: 210, 243: 210, 251: 210, 222: 209, 229: 207, 39: 206, 202: 206, 52: 203, 230: 202, 259: 201, 236: 200, 240: 198, 245: 196, 248: 196, 247: 196, 233: 195, 241: 193, 234: 192, 239: 191, 35: 190, 269: 187, 42: 186, 58: 185, 252: 183, 254: 171, 37: 171, 238: 169, 33: 166, 278: 163, 226: 161, 25: 156, 266: 154, 260: 153, 263: 151, 296: 146, 36: 145, 274: 144, 289: 144, 29: 143, 255: 142, 286: 142, 288: 141, 262: 140, 41: 139, 265: 135, 264: 134, 298: 134, 267: 133, 257: 132, 292: 132, 32: 131, 27: 131, 285: 131, 291: 130, 26: 129, 253: 128, 31: 128, 276: 128, 290: 127, 256: 126, 304: 125, 319: 124, 272: 123, 28: 123, 23: 121, 34: 121, 271: 120, 268: 119, 299: 119, 261: 118, 280: 118, 316: 118, 282: 117, 19: 116, 277: 113, 279: 112, 300: 112, 270: 111, 38: 109, 320: 109, 294: 108, 30: 108, 332: 106, 22: 103, 314: 102, 301: 102, 293: 101, 313: 100, 15: 99, 325: 99, 295: 98, 273: 97, 283: 96, 24: 96, 315: 94, 334: 94, 329: 93, 281: 93, 305: 92, 318: 91, 21: 91, 306: 87, 284: 87, 287: 86, 13: 84, 303: 84, 275: 83, 336: 81, 322: 80, 328: 79, 324: 78, 337: 77, 302: 77, 308: 74, 326: 73, 310: 73, 346: 72, 335: 72, 327: 71, 349: 70, 297: 70, 309: 70, 311: 69, 364: 69, 339: 68, 16: 68, 340: 66, 353: 66, 345: 66, 348: 66, 343: 65, 20: 63, 330: 63, 321: 63, 17: 62, 312: 61, 307: 60, 18: 59, 351: 58, 317: 57, 361: 56, 368: 54, 342: 53, 354: 53, 323: 52, 436: 51, 331: 50, 344: 50, 362: 49, 333: 49, 376: 49, 393: 49, 359: 48, 367: 48, 352: 48, 399: 46, 356: 46, 372: 46, 338: 45, 355: 44, 365: 44, 350: 44, 347: 42, 12: 42, 360: 42, 380: 42, 386: 42, 417: 42, 358: 41, 374: 41, 366: 40, 426: 39, 369: 39, 11: 39, 383: 38, 371: 38, 402: 37, 373: 36, 363: 35, 419: 34, 370: 34, 400: 34, 388: 34, 14: 33, 357: 33, 439: 33, 341: 32, 401: 31, 394: 31, 433: 31, 387: 30, 398: 29, 407: 29, 381: 28, 434: 28, 390: 28, 448: 28, 378: 27, 392: 26, 385: 26, 405: 26, 384: 26, 440: 25, 418: 25, 423: 24, 413: 24, 379: 24, 389: 23, 406: 23, 396: 23, 409: 22, 410: 22, 446: 22, 382: 22, 450: 22, 391: 22, 441: 21, 404: 21, 460: 21, 453: 21, 403: 21, 414: 21, 412: 20, 422: 20, 427: 20, 411: 20, 435: 20, 416: 19, 377: 19, 420: 19, 451: 18, 415: 18, 375: 17, 395: 17, 509: 16, 486: 16, 442: 16, 425: 16, 421: 16, 431: 16, 438: 16, 562: 16, 508: 15, 557: 15, 462: 14, 430: 14, 473: 14, 455: 14, 583: 13, 469: 13, 445: 13, 463: 13, 496: 12, 500: 12, 457: 12, 542: 12, 523: 12, 499: 12, 424: 12, 461: 12, 478: 12, 408: 12, 465: 11, 437: 11, 447: 11, 479: 11, 444: 11, 488: 11, 530: 10, 464: 10, 452: 10, 529: 10, 503: 10, 533: 9, 543: 9, 498: 9, 475: 9, 397: 9, 511: 9, 429: 9, 474: 9, 480: 9, 467: 8, 531: 8, 620: 8, 515: 8, 8: 8, 449: 8, 619: 8, 466: 8, 3: 8, 471: 8, 477: 8, 497: 7, 538: 7, 468: 7, 518: 7, 476: 7, 501: 7, 519: 7, 481: 7, 493: 7, 540: 7, 605: 7, 525: 7, 622: 6, 574: 6, 735: 6, 598: 6, 484: 6, 600: 6, 490: 6, 590: 6, 534: 6, 432: 6, 10: 6, 632: 6, 551: 6, 494: 6, 577: 5, 698: 5, 510: 5, 646: 5, 495: 5, 572: 5, 652: 5, 668: 5, 720: 5, 535: 5, 641: 5, 9: 5, 532: 5, 482: 5, 458: 5, 716: 5, 428: 5, 559: 5, 541: 5, 582: 5, 566: 5, 472: 5, 487: 4, 454: 4, 502: 4, 545: 4, 623: 4, 604: 4, 470: 4, 483: 4, 573: 4, 504: 4, 7: 4, 552: 4, 634: 3, 459: 3, 520: 3, 485: 3, 613: 3, 639: 3, 553: 3, 576: 3, 492: 3, 5: 3, 548: 2, 744: 2, 549: 2, 6: 2, 456: 2, 539: 2, 512: 2, 618: 2, 621: 2, 550: 2, 489: 2, 565: 2, 617: 2, 615: 2, 625: 2, 628: 2, 567: 2, 537: 2, 614: 2, 746: 2, 491: 2, 642: 2, 513: 2, 663: 1, 514: 1, 650: 1, 505: 1, 443: 1, 631: 1, 810: 1, 522: 1, 783: 1, 578: 1, 607: 1, 564: 1, 685: 1, 527: 1, 544: 1, 602: 1, 665: 1, 1087: 1, 630: 1, 516: 1, 560: 1, 526: 1, 882: 1, 671: 1, 1033: 1, 636: 1, 597: 1, 729: 1, 599: 1, 694: 1, 624: 1, 581: 1, 627: 1, 638: 1, 584: 1, 568: 1, 1137: 1, 754: 1, 524: 1, 507: 1, 536: 1, 586: 1, 778: 1, 546: 1, 593: 1, 579: 1, 563: 1, 739: 1, 931: 1}

  [options]
    dtype      : object
    sample val : array(['A)21', 'B)21.5', 'C)22', 'D)22.5', 'E)23'], dtype=object)
    nulls      : 0
    n_unique   : unhashable (list/array column)
    len dist   : {5: 97467}

  [rationale]
    dtype      : object
    sample val : 'If Q complete x kilometers, then P completes 1.15x kilometers.\nx + 1.15x = 43\n2.15x=43\nx = 43/2.15 = 20\nThen P will
    nulls      : 0
    n_unique   : 90941
    len dist   : {94: 487, 137: 471, 131: 465, 107: 463, 112: 457, 69: 451, 127: 451, 119: 445, 95: 438, 100: 438, 96: 434, 130: 427, 141: 423, 104: 423, 109: 419, 91: 418, 156: 412, 108: 412, 79: 411, 80: 411, 78: 411, 143: 410, 92: 410, 118: 408, 106: 408, 89: 406, 54: 406, 145: 406, 124: 405, 81: 404, 93: 403, 67: 402, 128: 402, 113: 402, 70: 402, 162: 401, 90: 400, 102: 400, 114: 400, 158: 398, 76: 397, 136: 397, 56: 396, 129: 395, 144: 394, 126: 392, 123: 391, 134: 391, 110: 388, 99: 387, 160: 386, 82: 385, 138: 385, 125: 385, 73: 385, 49: 384, 101: 384, 86: 383, 53: 383, 57: 381, 111: 381, 132: 381, 161: 381, 55: 381, 103: 377, 180: 376, 97: 376, 148: 375, 87: 374, 115: 374, 117: 374, 88: 372, 59: 372, 146: 371, 71: 370, 51: 369, 164: 368, 147: 368, 83: 368, 66: 366, 184: 366, 159: 365, 142: 364, 65: 364, 98: 363, 122: 362, 150: 361, 41: 361, 68: 359, 120: 359, 75: 359, 155: 358, 186: 357, 74: 356, 157: 353, 121: 353, 72: 352, 77: 351, 47: 351, 61: 350, 151: 349, 52: 347, 105: 346, 139: 344, 185: 343, 154: 342, 135: 341, 168: 340, 58: 339, 133: 337, 46: 336, 84: 336, 116: 335, 40: 334, 48: 334, 166: 332, 181: 332, 37: 328, 39: 328, 43: 327, 153: 326, 42: 324, 171: 322, 64: 322, 149: 321, 45: 321, 200: 321, 140: 320, 169: 318, 163: 318, 44: 316, 63: 315, 165: 314, 85: 313, 172: 312, 50: 310, 62: 310, 38: 307, 152: 305, 170: 305, 183: 303, 175: 301, 182: 299, 176: 297, 190: 296, 193: 295, 178: 293, 174: 293, 32: 292, 173: 291, 192: 291, 33: 289, 36: 288, 203: 287, 197: 282, 60: 281, 187: 280, 35: 279, 177: 277, 205: 273, 189: 272, 191: 270, 194: 269, 167: 269, 179: 267, 204: 265, 210: 261, 206: 261, 188: 260, 218: 259, 213: 259, 34: 256, 195: 254, 225: 254, 201: 252, 223: 251, 207: 251, 196: 251, 202: 250, 208: 247, 212: 246, 226: 245, 211: 239, 199: 237, 198: 235, 222: 235, 219: 233, 231: 232, 224: 228, 217: 227, 239: 226, 220: 217, 233: 217, 28: 215, 230: 214, 238: 214, 259: 210, 209: 210, 227: 210, 216: 209, 229: 207, 215: 206, 232: 206, 236: 203, 235: 202, 214: 201, 251: 195, 237: 192, 253: 192, 249: 192, 244: 191, 228: 189, 31: 189, 234: 189, 29: 186, 247: 184, 243: 176, 257: 176, 248: 173, 245: 173, 265: 170, 262: 167, 277: 167, 256: 167, 260: 166, 250: 163, 30: 163, 221: 162, 25: 160, 246: 159, 258: 156, 252: 155, 278: 155, 276: 152, 279: 151, 263: 151, 269: 149, 266: 148, 241: 147, 240: 146, 242: 146, 268: 146, 261: 146, 329: 143, 282: 143, 292: 143, 267: 142, 306: 141, 281: 141, 255: 139, 285: 136, 280: 135, 272: 135, 309: 132, 288: 131, 302: 130, 283: 130, 290: 129, 24: 129, 289: 128, 311: 128, 264: 128, 287: 127, 284: 123, 291: 122, 321: 120, 26: 119, 314: 119, 298: 119, 271: 118, 308: 116, 301: 116, 295: 115, 274: 115, 254: 114, 10: 114, 307: 111, 273: 111, 270: 110, 313: 109, 27: 109, 305: 109, 293: 108, 8: 107, 275: 107, 297: 106, 318: 105, 317: 105, 304: 105, 303: 105, 300: 101, 299: 100, 286: 99, 326: 99, 327: 99, 320: 98, 310: 98, 294: 97, 367: 96, 322: 96, 312: 96, 319: 95, 296: 95, 328: 95, 348: 94, 389: 94, 331: 94, 324: 93, 333: 93, 342: 92, 347: 92, 364: 91, 323: 90, 341: 89, 335: 89, 330: 87, 340: 86, 375: 85, 332: 84, 337: 83, 316: 83, 351: 82, 365: 81, 22: 80, 315: 80, 380: 79, 325: 79, 334: 78, 357: 78, 366: 78, 363: 78, 344: 77, 356: 76, 397: 76, 387: 76, 345: 76, 346: 76, 369: 74, 354: 74, 373: 74, 403: 73, 371: 73, 362: 73, 404: 72, 377: 72, 336: 72, 339: 72, 343: 72, 401: 71, 23: 70, 20: 70, 353: 70, 381: 69, 359: 69, 352: 69, 413: 68, 349: 68, 378: 68, 361: 68, 376: 67, 402: 67, 394: 67, 350: 66, 370: 66, 379: 66, 19: 66, 390: 65, 391: 65, 21: 64, 338: 63, 374: 62, 383: 62, 399: 62, 382: 62, 384: 62, 388: 60, 395: 60, 360: 60, 368: 59, 405: 59, 407: 59, 409: 58, 420: 58, 406: 58, 385: 57, 429: 56, 418: 56, 372: 56, 419: 56, 13: 55, 358: 53, 417: 53, 355: 53, 1: 52, 393: 52, 392: 51, 464: 51, 410: 50, 411: 49, 9: 49, 425: 48, 400: 48, 443: 48, 412: 48, 426: 48, 408: 48, 423: 48, 16: 48, 386: 47, 398: 47, 431: 47, 447: 47, 415: 46, 469: 46, 438: 45, 480: 45, 436: 45, 512: 45, 506: 44, 440: 43, 424: 43, 14: 43, 473: 43, 452: 43, 482: 42, 460: 42, 432: 42, 17: 42, 427: 42, 445: 42, 433: 42, 396: 42, 18: 41, 444: 40, 461: 40, 450: 40, 430: 39, 414: 38, 522: 38, 428: 38, 441: 38, 422: 37, 416: 37, 472: 37, 421: 37, 485: 37, 501: 36, 496: 36, 435: 35, 507: 35, 446: 35, 457: 35, 495: 35, 439: 35, 540: 34, 534: 34, 458: 34, 528: 33, 546: 33, 483: 33, 437: 33, 468: 32, 456: 32, 491: 32, 479: 32, 434: 31, 488: 31, 503: 31, 463: 31, 5: 31, 449: 31, 510: 30, 490: 30, 459: 30, 487: 30, 465: 30, 516: 29, 475: 29, 617: 29, 476: 29, 470: 29, 564: 29, 542: 28, 493: 28, 489: 28, 520: 28, 442: 28, 477: 28, 451: 28, 453: 28, 448: 28, 509: 28, 4: 27, 526: 27, 11: 27, 521: 27, 504: 27, 492: 27, 455: 27, 499: 27, 505: 27, 577: 26, 486: 26, 558: 26, 15: 25, 497: 25, 587: 25, 467: 25, 514: 25, 601: 25, 511: 25, 519: 25, 536: 24, 538: 24, 517: 24, 454: 24, 537: 24, 563: 24, 602: 24, 606: 24, 484: 23, 12: 23, 589: 23, 523: 23, 6: 23, 527: 23, 532: 23, 560: 22, 471: 22, 466: 22, 599: 22, 566: 22, 478: 22, 635: 22, 609: 21, 571: 21, 610: 21, 565: 21, 579: 21, 541: 21, 474: 21, 525: 20, 561: 20, 559: 20, 621: 20, 547: 20, 785: 20, 655: 20, 531: 20, 535: 20, 614: 19, 462: 19, 513: 19, 581: 19, 530: 19, 494: 19, 502: 19, 666: 18, 555: 18, 544: 18, 596: 18, 576: 18, 533: 18, 529: 18, 597: 18, 608: 17, 572: 17, 570: 17, 646: 17, 624: 17, 715: 17, 551: 17, 481: 17, 582: 17, 604: 17, 584: 17, 640: 16, 684: 16, 668: 16, 644: 16, 738: 16, 629: 16, 690: 16, 508: 16, 539: 16, 557: 16, 615: 16, 500: 16, 498: 16, 662: 16, 616: 15, 652: 15, 592: 15, 779: 15, 552: 15, 605: 15, 654: 15, 573: 15, 636: 15, 632: 15, 3: 15, 518: 15, 628: 15, 569: 15, 548: 15, 598: 14, 524: 14, 607: 14, 553: 14, 549: 14, 556: 14, 578: 14, 586: 14, 657: 14, 758: 14, 545: 14, 673: 14, 631: 14, 574: 14, 603: 14, 784: 14, 625: 14, 796: 14, 639: 13, 622: 13, 591: 13, 575: 13, 620: 13, 692: 13, 713: 13, 672: 13, 724: 13, 567: 13, 543: 13, 647: 13, 619: 13, 656: 13, 689: 13, 671: 12, 515: 12, 788: 12, 695: 12, 773: 12, 670: 12, 7: 12, 734: 12, 594: 12, 611: 12, 634: 12, 667: 12, 600: 12, 653: 12, 824: 12, 851: 11, 735: 11, 1001: 11, 707: 11, 891: 11, 704: 11, 650: 11, 783: 11, 642: 11, 612: 11, 627: 11, 756: 11, 798: 11, 669: 11, 554: 11, 741: 11, 626: 11, 776: 11, 568: 11, 838: 10, 934: 10, 660: 10, 633: 10, 904: 10, 1637: 10, 823: 10, 674: 10, 729: 10, 2: 10, 721: 10, 649: 10, 630: 10, 777: 10, 701: 10, 595: 10, 637: 10, 693: 10, 664: 9, 849: 9, 665: 9, 580: 9, 694: 9, 688: 9, 782: 9, 752: 9, 658: 9, 714: 9, 812: 9, 832: 9, 613: 9, 956: 9, 749: 9, 746: 9, 593: 9, 979: 9, 754: 9, 852: 9, 550: 9, 696: 8, 775: 8, 803: 8, 685: 8, 850: 8, 726: 8, 819: 8, 825: 8, 921: 8, 911: 8, 750: 8, 757: 8, 745: 8, 787: 8, 562: 8, 800: 8, 866: 8, 811: 8, 913: 8, 728: 8, 623: 8, 839: 8, 585: 8, 765: 8, 691: 8, 813: 8, 590: 8, 742: 8, 706: 8, 583: 8, 1019: 7, 736: 7, 815: 7, 954: 7, 697: 7, 833: 7, 720: 7, 885: 7, 710: 7, 743: 7, 748: 7, 725: 7, 638: 7, 678: 7, 874: 7, 834: 7, 686: 7, 648: 7, 890: 7, 1073: 7, 588: 7, 755: 7, 682: 7, 1147: 7, 778: 7, 732: 7, 663: 7, 808: 7, 791: 6, 1024: 6, 676: 6, 683: 6, 919: 6, 717: 6, 679: 6, 1459: 6, 949: 6, 1122: 6, 1105: 6, 831: 6, 940: 6, 915: 6, 659: 6, 1080: 6, 865: 6, 722: 6, 703: 6, 687: 6, 733: 6, 700: 6, 799: 6, 958: 6, 790: 6, 883: 6, 618: 6, 795: 6, 1678: 6, 1387: 6, 718: 6, 905: 5, 900: 5, 899: 5, 1070: 5, 1056: 5, 809: 5, 643: 5, 1373: 5, 1223: 5, 1002: 5, 770: 5, 2107: 5, 1124: 5, 731: 5, 3684: 5, 1082: 5, 1800: 5, 681: 5, 1114: 5, 945: 5, 843: 5, 1547: 5, 983: 5, 1259: 5, 1962: 5, 841: 5, 1475: 5, 744: 5, 820: 5, 1301: 5, 675: 5, 994: 5, 1207: 5, 769: 5, 709: 5, 1039: 5, 699: 5, 2490: 5, 737: 5, 719: 5, 1699: 5, 1467: 5, 1450: 5, 855: 5, 1052: 5, 1129: 5, 723: 5, 677: 5, 1190: 5, 1162: 5, 1304: 5, 1142: 5, 698: 4, 881: 4, 645: 4, 998: 4, 1679: 4, 827: 4, 794: 4, 896: 4, 753: 4, 910: 4, 766: 4, 1479: 4, 875: 4, 830: 4, 966: 4, 857: 4, 730: 4, 991: 4, 1027: 4, 837: 4, 1757: 4, 705: 4, 739: 4, 1121: 4, 1364: 4, 903: 4, 1123: 4, 712: 4, 786: 4, 805: 4, 1411: 4, 1157: 4, 727: 4, 661: 4, 1228: 4, 933: 3, 889: 3, 1230: 3, 989: 3, 1193: 3, 1541: 3, 975: 3, 711: 3, 1294: 3, 1292: 3, 952: 3, 1048: 3, 641: 3, 864: 3, 1021: 3, 806: 3, 870: 3, 878: 3, 2635: 3, 1000: 3, 1233: 3, 918: 3, 821: 3, 977: 3, 884: 3, 767: 3, 862: 3, 772: 3, 950: 3, 1107: 3, 970: 3, 761: 3, 968: 3, 1172: 3, 1321: 3, 1305: 3, 814: 3, 802: 3, 759: 3, 762: 3, 880: 3, 774: 3, 822: 3, 771: 3, 1029: 3, 912: 3, 1192: 3, 768: 3, 1028: 3, 1488: 3, 1079: 3, 888: 3, 702: 3, 751: 3, 792: 3, 867: 3, 1008: 3, 1254: 3, 871: 3, 1297: 2, 957: 2, 1062: 2, 886: 2, 817: 2, 1053: 2, 826: 2, 1017: 2, 842: 2, 1237: 2, 922: 2, 846: 2, 914: 2, 789: 2, 780: 2, 1392: 2, 708: 2, 1064: 2, 1096: 2, 1141: 2, 760: 2, 953: 2, 1941: 2, 1083: 2, 929: 2, 1026: 2, 1706: 2, 1014: 2, 974: 2, 926: 2, 879: 2, 935: 2, 1018: 2, 1133: 2, 835: 2, 1303: 2, 1012: 2, 740: 2, 1054: 2, 942: 2, 1359: 2, 869: 2, 1175: 2, 969: 2, 920: 2, 1323: 2, 908: 2, 986: 2, 1171: 2, 861: 2, 716: 2, 1169: 2, 860: 2, 1231: 2, 1004: 2, 948: 2, 1243: 2, 937: 2, 1263: 2, 892: 2, 829: 2, 1216: 2, 972: 2, 848: 2, 990: 2, 801: 2, 747: 2, 1264: 2, 1010: 2, 1164: 2, 1478: 2, 893: 2, 947: 2, 971: 2, 845: 2, 924: 2, 1452: 2, 1773: 2, 1823: 2, 907: 2, 844: 2, 840: 2, 965: 2, 1252: 2, 1550: 1, 1412: 1, 1225: 1, 1568: 1, 1206: 1, 1287: 1, 1191: 1, 930: 1, 1104: 1, 955: 1, 1182: 1, 1078: 1, 1353: 1, 1041: 1, 1447: 1, 1138: 1, 961: 1, 909: 1, 1170: 1, 1350: 1, 1090: 1, 901: 1, 1040: 1, 944: 1, 1473: 1, 2209: 1, 1137: 1, 1756: 1, 1460: 1, 1367: 1, 1424: 1, 1358: 1, 1293: 1, 1221: 1, 2636: 1, 873: 1, 2632: 1, 894: 1, 854: 1, 927: 1, 1333: 1, 1334: 1, 1110: 1, 1363: 1, 1540: 1, 1522: 1, 1336: 1, 1043: 1, 1487: 1, 1011: 1, 1075: 1, 793: 1, 902: 1, 2005: 1, 2160: 1, 863: 1, 1160: 1, 828: 1, 1176: 1, 1155: 1, 1116: 1, 1850: 1, 1916: 1, 1072: 1, 1229: 1, 1846: 1, 1103: 1, 1031: 1, 1789: 1, 1722: 1, 836: 1, 982: 1, 939: 1, 1943: 1, 1980: 1, 1187: 1, 818: 1, 1195: 1, 1734: 1, 1354: 1, 2411: 1, 2382: 1, 1095: 1, 1397: 1, 1130: 1, 2386: 1, 1312: 1, 1261: 1, 906: 1, 1410: 1, 1362: 1, 882: 1, 928: 1, 2154: 1, 1025: 1, 1314: 1, 963: 1, 2003: 1, 1434: 1, 1055: 1, 1068: 1, 1707: 1, 980: 1, 1279: 1, 1485: 1, 1240: 1, 816: 1, 1042: 1, 1308: 1, 1428: 1, 985: 1, 1077: 1, 887: 1, 1687: 1, 2885: 1, 1352: 1, 1120: 1, 925: 1, 936: 1, 763: 1, 859: 1, 993: 1, 1106: 1, 1022: 1, 1239: 1, 997: 1, 1310: 1, 797: 1, 1930: 1, 1245: 1, 1069: 1, 1437: 1, 1796: 1, 1790: 1, 1047: 1, 1545: 1, 1692: 1, 1013: 1, 1451: 1, 1560: 1, 1091: 1, 1246: 1, 1688: 1, 868: 1, 1033: 1, 1783: 1, 1076: 1, 1542: 1, 1183: 1, 1023: 1, 1060: 1, 1242: 1, 876: 1, 1355: 1, 1158: 1, 781: 1, 1066: 1, 1111: 1, 1432: 1, 1038: 1, 895: 1, 1087: 1, 853: 1, 1544: 1, 1482: 1, 1236: 1, 1976: 1, 1794: 1, 931: 1, 1094: 1, 1300: 1, 1572: 1, 1125: 1, 1092: 1, 951: 1, 1168: 1, 1262: 1, 810: 1, 1433: 1, 1360: 1, 1662: 1, 858: 1, 1148: 1, 1298: 1, 680: 1, 1058: 1, 1503: 1, 1144: 1, 1020: 1}

  [correct]
    dtype      : object
    sample val : 'E'
    nulls      : 0
    n_unique   : 5
    counts     : {'C': 22290, 'B': 21446, 'A': 20494, 'D': 19441, 'E': 13796}
    len dist   : {1: 97467}

  ── First 3 examples ──────────────────────────────────────
  ── Example 0 ────────────────────────────────────────
  question            : "Two friends plan to walk along a 43-km trail, starting at opposite ends of the trail at the same time. If Friend P's rate is 15% faster than Friend Q's, how many kilometers will Friend P have walked when they pass each other?"
  options             : ['A)21', 'B)21.5', 'C)22', 'D)22.5', 'E)23']
  rationale           : 'If Q complete x kilometers, then P completes 1.15x kilometers.\nx + 1.15x = 43\n2.15x=43\nx = 43/2.15 = 20\nThen P will have have walked 1.15*20=23 km.\nThe answer is E.'
  correct             : 'E'

  ── Example 1 ────────────────────────────────────────
  question            : 'In the coordinate plane, points (x, 1) and (5, y) are on line k. If line k passes through the origin and has slope 1/5, then what are the values of x and y respectively?'
  options             : ['A)4 and 1', 'B)1 and 5', 'C)5 and 1', 'D)3 and 5', 'E)5 and 3']
  rationale           : 'Line k passes through the origin and has slope 1/5 means that its equation is y=1/5*x.\nThus: (x, 1)=(5, 1) and (5, y) = (5,1) -->x=5 and y=1\nAnswer: C'
  correct             : 'C'

  ── Example 2 ────────────────────────────────────────
  question            : 'For all numbers p and q, the operation @ is defined by p@q = p^2 - pq. If xy ≠ 0, then which of the following can be equal to zero?\nI. x@y\nII. (xy)@y\nIII. x@(x + y)'
  options             : ['A)II', 'B)I and II', 'C)I and III', 'D)II and III', 'E)All of the above']
  rationale           : 'p@q = p^2 - pq=p(p-q).... so p@q will be zero if p=q or p=0.. but a cannot be equal to 0.. as per Q, x and y can take any int value except 0...\nnow lets look at the choices..\nwhen x=y, it will be 0... so ok...\nwhen we put xy=y, it is possible whe
  correct             : 'B'

  Returning sampled DataFrame — 250 rows (seed=42)

In [ ]:
# What fields do we have?
print(df_aqua.columns.tolist())
print()

# What does the answer field look like?
print(df_aqua["correct"].value_counts())
print()

# How many options per question?
df_aqua["options"].apply(len).value_counts()

['question', 'options', 'rationale', 'correct']

correct
D    57
C    55
A    51
E    44
B    43
Name: count, dtype: int64

options
5    250
Name: count, dtype: int64

## ReClor
Logical reasoning (substitute for LogiQA)

In [ ]:
df_reclor = explore("metaeval/reclor", name=None, split="train", n=3, sample=250)

============================================================
  metaeval/reclor  |  config=None
============================================================

README.md:   0%|          | 0.00/407 [00:00<?, ?B/s]

  Available splits : ['train', 'validation']
  Loading split    : 'train' ...

train.json: 0.00B [00:00, ?B/s]

val.json: 0.00B [00:00, ?B/s]

Generating train split:   0%|          | 0/4638 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/500 [00:00<?, ? examples/s]

  ── Full dataset stats ──────────────────────────────────────
  Total rows  : 4638
  Columns     : ['answers', 'context', 'label', 'id_string', 'question']

  [answers]
    dtype      : object
    sample val : array(['Unlike aspirin and other medications that reduce pain and swelling and that are currently available, the new med
    nulls      : 0
    n_unique   : unhashable (list/array column)
    len dist   : {4: 4638}

  [context]
    dtype      : object
    sample val : "In rheumatoid arthritis, the body' s immune system misfunctions by attacking healthy cells in the joints causing the re
    nulls      : 0
    n_unique   : 4628
    len dist   : {361: 26, 445: 25, 317: 23, 391: 23, 430: 21, 358: 21, 466: 20, 441: 20, 398: 20, 341: 20, 351: 19, 334: 19, 421: 19, 350: 19, 370: 18, 432: 18, 359: 18, 483: 18, 425: 18, 429: 18, 438: 18, 458: 18, 316: 18, 328: 18, 382: 18, 392: 18, 383: 18, 456: 17, 414: 17, 450: 17, 396: 17, 387: 17, 515: 17, 461: 17, 374: 17, 427: 17, 397: 17, 356: 17, 368: 17, 371: 17, 418: 17, 385: 17, 434: 16, 411: 16, 333: 16, 453: 16, 494: 16, 363: 16, 399: 16, 451: 16, 491: 16, 307: 16, 322: 16, 454: 16, 417: 16, 330: 16, 401: 16, 365: 16, 479: 16, 342: 16, 403: 16, 409: 16, 444: 16, 420: 16, 460: 16, 288: 16, 308: 15, 426: 15, 354: 15, 410: 15, 339: 15, 353: 15, 384: 15, 506: 15, 381: 15, 508: 15, 424: 15, 407: 15, 343: 15, 435: 15, 390: 15, 507: 15, 412: 15, 462: 14, 346: 14, 394: 14, 324: 14, 389: 14, 376: 14, 500: 14, 442: 14, 373: 14, 293: 14, 369: 14, 326: 14, 289: 14, 388: 14, 471: 14, 475: 14, 431: 14, 465: 14, 437: 14, 395: 14, 335: 14, 315: 14, 416: 14, 480: 14, 468: 14, 440: 13, 375: 13, 366: 13, 348: 13, 404: 13, 457: 13, 405: 13, 386: 13, 485: 13, 419: 13, 484: 13, 347: 13, 362: 13, 331: 13, 402: 13, 510: 13, 323: 13, 312: 13, 413: 13, 482: 13, 337: 13, 481: 13, 378: 13, 352: 13, 436: 13, 467: 13, 364: 13, 447: 13, 455: 13, 408: 13, 487: 13, 446: 13, 472: 13, 406: 12, 400: 12, 314: 12, 464: 12, 320: 12, 340: 12, 448: 12, 332: 12, 452: 12, 514: 12, 477: 12, 522: 12, 377: 12, 469: 12, 493: 12, 488: 12, 393: 12, 439: 12, 511: 12, 310: 12, 304: 12, 321: 12, 423: 12, 490: 12, 516: 12, 499: 12, 311: 12, 476: 12, 319: 11, 498: 11, 327: 11, 345: 11, 279: 11, 449: 11, 318: 11, 360: 11, 259: 11, 277: 11, 355: 11, 459: 11, 443: 11, 502: 11, 344: 11, 305: 11, 336: 11, 349: 11, 282: 11, 275: 11, 298: 11, 463: 11, 542: 11, 296: 11, 367: 11, 309: 11, 415: 11, 338: 11, 285: 11, 504: 10, 268: 10, 209: 10, 503: 10, 486: 10, 428: 10, 232: 10, 303: 10, 433: 10, 258: 10, 291: 10, 549: 10, 300: 10, 280: 10, 263: 10, 325: 10, 537: 10, 254: 10, 380: 10, 531: 10, 505: 10, 521: 10, 292: 10, 577: 10, 215: 9, 281: 9, 313: 9, 495: 9, 422: 9, 240: 9, 605: 9, 552: 9, 497: 9, 265: 9, 530: 9, 266: 9, 264: 9, 372: 9, 261: 9, 544: 9, 299: 9, 250: 9, 524: 9, 512: 9, 496: 9, 357: 9, 525: 8, 538: 8, 267: 8, 235: 8, 474: 8, 225: 8, 233: 8, 526: 8, 329: 8, 520: 8, 276: 8, 297: 8, 222: 8, 509: 8, 553: 8, 545: 8, 284: 8, 302: 8, 257: 8, 564: 8, 528: 7, 501: 7, 519: 7, 278: 7, 585: 7, 234: 7, 536: 7, 379: 7, 535: 7, 533: 7, 513: 7, 566: 7, 273: 7, 631: 7, 561: 7, 295: 7, 565: 7, 247: 7, 241: 7, 527: 7, 192: 7, 230: 7, 218: 7, 559: 7, 249: 6, 306: 6, 473: 6, 540: 6, 286: 6, 221: 6, 568: 6, 238: 6, 541: 6, 492: 6, 270: 6, 156: 6, 294: 6, 252: 6, 220: 6, 210: 6, 255: 6, 518: 6, 231: 6, 260: 6, 551: 6, 489: 6, 632: 6, 204: 6, 287: 6, 563: 6, 478: 6, 532: 6, 271: 6, 272: 6, 239: 6, 641: 5, 199: 5, 543: 5, 301: 5, 470: 5, 610: 5, 560: 5, 674: 5, 174: 5, 594: 5, 570: 5, 195: 5, 182: 5, 567: 5, 269: 5, 517: 5, 251: 5, 246: 5, 256: 5, 596: 5, 539: 5, 290: 5, 219: 5, 572: 5, 803: 5, 581: 5, 604: 5, 608: 5, 227: 5, 642: 5, 211: 5, 575: 5, 217: 5, 603: 5, 262: 5, 229: 5, 248: 5, 283: 5, 547: 5, 576: 5, 181: 5, 245: 5, 164: 5, 651: 5, 571: 5, 189: 5, 212: 4, 550: 4, 679: 4, 580: 4, 827: 4, 200: 4, 244: 4, 224: 4, 600: 4, 684: 4, 687: 4, 660: 4, 583: 4, 609: 4, 573: 4, 772: 4, 216: 4, 569: 4, 598: 4, 198: 4, 619: 4, 557: 4, 597: 4, 529: 4, 160: 4, 523: 4, 586: 4, 649: 4, 201: 4, 593: 4, 140: 4, 179: 4, 236: 4, 226: 4, 606: 4, 214: 4, 196: 4, 657: 4, 591: 4, 574: 4, 670: 3, 588: 3, 617: 3, 638: 3, 725: 3, 148: 3, 751: 3, 616: 3, 602: 3, 624: 3, 711: 3, 692: 3, 650: 3, 730: 3, 764: 3, 713: 3, 159: 3, 761: 3, 676: 3, 197: 3, 202: 3, 169: 3, 190: 3, 724: 3, 712: 3, 578: 3, 145: 3, 207: 3, 691: 3, 599: 3, 208: 3, 621: 3, 705: 3, 719: 3, 136: 3, 622: 3, 618: 3, 648: 3, 147: 3, 611: 3, 735: 3, 658: 3, 623: 3, 554: 3, 142: 3, 168: 3, 582: 3, 175: 3, 187: 3, 702: 3, 177: 3, 206: 3, 683: 3, 158: 3, 184: 3, 555: 3, 274: 3, 185: 3, 644: 3, 655: 2, 253: 2, 847: 2, 589: 2, 141: 2, 243: 2, 193: 2, 163: 2, 704: 2, 710: 2, 590: 2, 183: 2, 205: 2, 675: 2, 795: 2, 228: 2, 694: 2, 203: 2, 558: 2, 645: 2, 768: 2, 717: 2, 748: 2, 626: 2, 728: 2, 584: 2, 176: 2, 673: 2, 151: 2, 747: 2, 742: 2, 716: 2, 773: 2, 534: 2, 133: 2, 548: 2, 669: 2, 646: 2, 144: 2, 612: 2, 587: 2, 188: 2, 633: 2, 709: 2, 613: 2, 149: 2, 191: 2, 663: 2, 171: 2, 656: 2, 126: 2, 146: 2, 715: 2, 636: 2, 793: 2, 647: 2, 170: 2, 706: 2, 143: 2, 154: 2, 681: 2, 161: 2, 699: 2, 637: 2, 123: 2, 223: 2, 753: 2, 690: 2, 167: 2, 886: 2, 242: 2, 740: 2, 237: 2, 562: 2, 682: 2, 654: 2, 634: 2, 697: 2, 782: 2, 708: 2, 155: 2, 754: 1, 628: 1, 783: 1, 823: 1, 677: 1, 134: 1, 696: 1, 157: 1, 671: 1, 701: 1, 114: 1, 775: 1, 720: 1, 667: 1, 729: 1, 186: 1, 726: 1, 1005: 1, 703: 1, 736: 1, 659: 1, 166: 1, 732: 1, 601: 1, 869: 1, 727: 1, 615: 1, 556: 1, 750: 1, 680: 1, 757: 1, 116: 1, 119: 1, 672: 1, 688: 1, 102: 1, 945: 1, 1135: 1, 901: 1, 135: 1, 94: 1, 744: 1, 108: 1, 128: 1, 627: 1, 678: 1, 769: 1, 800: 1, 127: 1, 988: 1, 194: 1, 814: 1, 614: 1, 788: 1, 665: 1, 125: 1, 718: 1, 607: 1, 832: 1, 698: 1, 111: 1, 781: 1, 842: 1, 790: 1, 749: 1, 854: 1, 784: 1, 546: 1, 131: 1, 592: 1, 95: 1, 707: 1, 178: 1, 734: 1, 162: 1, 738: 1, 595: 1, 165: 1, 152: 1, 640: 1, 741: 1, 643: 1, 746: 1, 766: 1, 172: 1, 760: 1, 153: 1, 620: 1, 877: 1, 798: 1, 173: 1, 180: 1, 150: 1, 653: 1, 685: 1, 661: 1, 579: 1, 925: 1, 745: 1, 786: 1}

  [label]
    dtype      : int64
    sample val : np.int64(1)
    nulls      : 0
    n_unique   : 4
    counts     : {0: 1171, 1: 1170, 2: 1154, 3: 1143}

  [id_string]
    dtype      : object
    sample val : 'train_0'
    nulls      : 0
    n_unique   : 4638
    len dist   : {10: 3638, 9: 900, 8: 90, 7: 10}

  [question]
    dtype      : object
    sample val : 'The statements above, if true, most strongly support which one of the following conclusions?'
    nulls      : 0
    n_unique   : 3372
    len dist   : {74: 138, 79: 123, 69: 112, 84: 110, 86: 105, 80: 104, 60: 102, 90: 99, 67: 94, 94: 93, 73: 90, 83: 87, 70: 87, 89: 84, 78: 83, 91: 82, 81: 79, 95: 73, 87: 71, 77: 70, 85: 70, 82: 69, 63: 68, 88: 68, 101: 66, 92: 66, 100: 65, 96: 63, 109: 63, 93: 60, 104: 60, 98: 57, 76: 56, 71: 56, 108: 55, 75: 54, 103: 54, 65: 49, 105: 47, 99: 47, 106: 47, 72: 46, 111: 44, 97: 43, 102: 40, 68: 39, 66: 39, 107: 38, 112: 34, 113: 34, 64: 31, 114: 30, 61: 29, 115: 28, 110: 27, 125: 25, 55: 24, 118: 22, 117: 22, 126: 21, 128: 21, 120: 20, 121: 20, 124: 20, 123: 20, 122: 19, 116: 19, 56: 19, 62: 19, 119: 17, 129: 16, 43: 16, 41: 15, 127: 14, 53: 14, 24: 14, 58: 14, 130: 14, 135: 13, 136: 13, 50: 13, 137: 13, 59: 11, 144: 11, 132: 11, 134: 10, 45: 10, 49: 10, 54: 10, 150: 10, 40: 9, 38: 9, 138: 9, 131: 9, 133: 9, 39: 9, 48: 9, 162: 8, 152: 8, 47: 8, 147: 8, 146: 8, 149: 8, 139: 8, 57: 7, 153: 7, 156: 7, 46: 7, 145: 7, 51: 7, 25: 7, 142: 7, 141: 7, 33: 7, 158: 7, 148: 6, 155: 6, 160: 6, 44: 6, 170: 6, 35: 6, 177: 6, 161: 6, 31: 6, 143: 5, 175: 5, 189: 5, 163: 5, 36: 5, 52: 5, 37: 5, 154: 5, 34: 4, 173: 4, 168: 4, 27: 4, 205: 4, 169: 4, 172: 4, 166: 4, 157: 4, 29: 4, 198: 4, 164: 4, 140: 3, 181: 3, 179: 3, 28: 3, 184: 3, 30: 3, 194: 3, 219: 3, 192: 3, 200: 3, 151: 3, 187: 3, 180: 3, 212: 3, 185: 3, 196: 3, 26: 3, 206: 2, 165: 2, 234: 2, 171: 2, 191: 2, 204: 2, 202: 2, 193: 2, 42: 2, 237: 2, 159: 2, 183: 2, 230: 2, 167: 2, 213: 2, 311: 1, 293: 1, 195: 1, 278: 1, 232: 1, 342: 1, 291: 1, 259: 1, 217: 1, 257: 1, 222: 1, 228: 1, 201: 1, 292: 1, 262: 1, 214: 1, 216: 1, 182: 1, 211: 1, 275: 1, 188: 1, 238: 1, 226: 1, 32: 1, 231: 1, 186: 1, 242: 1, 326: 1, 225: 1, 210: 1, 174: 1}

  ── First 3 examples ──────────────────────────────────────
  ── Example 0 ────────────────────────────────────────
  answers             : ['Unlike aspirin and other medications that reduce pain and swelling and that are currently available, the new medication would repair existing cell damage that had been caused by rheumatoid arthritis.', 'A patient treated with the new medication for
  context             : "In rheumatoid arthritis, the body' s immune system misfunctions by attacking healthy cells in the joints causing the release of a hormone that in turn causes pain and swelling. This hormone is normally activated only in reaction to injury or infecti
  label               : 1
  id_string           : 'train_0'
  question            : 'The statements above, if true, most strongly support which one of the following conclusions?'

  ── Example 1 ────────────────────────────────────────
  answers             : ['attempting to discredit a position by questioning the motives of the proponents of that position', 'rejecting a questionable position on the grounds that the general public does not support that position', "pointing out an unstated assumption on wh
  context             : 'Patient: Pharmacists maintain that doctors should not be permitted to sell the medicine that they prescribe because doctors would then be tempted to prescribe unnecessary medicines in order to earn extra income. But pharmacists have a financial inte
  label               : 0
  id_string           : 'train_1'
  question            : "The patient's argument proceeds by"

  ── Example 2 ────────────────────────────────────────
  answers             : ['If Marge goes to the bank today, Lauren will not cash her check tomorrow. Marge will not wash her car unless it is sunny. However, it is sunny, so Marge will wash her car and go shopping with Lauren.', 'Kevin will wash his car tomorrow only if Brit
  context             : 'Paula will visit the dentist tomorrow morning only if Bill goes golfing in the morning. Bill will not go golfing unless Damien agrees to go golfing too. However, Damien has decided not to go golfing. Ttherefore, Paula will not be visiting the dentis
  label               : 1
  id_string           : 'train_2'
  question            : 'The pattern of reasoning displayed above most closely parallels which of the following?'

  Returning sampled DataFrame — 250 rows (seed=42)

In [ ]:
print(df_reclor.columns.tolist())
print()
print(df_reclor["label"].value_counts())
print()
df_reclor["answers"].apply(len).value_counts()

['answers', 'context', 'label', 'id_string', 'question']

label
0    70
2    63
3    60
1    57
Name: count, dtype: int64

answers
4    250
Name: count, dtype: int64

## OpenBookQA
Elementary science

In [ ]:
# OpenBookQA — elementary science, requires external knowledge to answer
df_openbookqa = explore("allenai/openbookqa", name="main", split="train", n=3, sample=250)

============================================================
  allenai/openbookqa  |  config=main
============================================================

README.md: 0.00B [00:00, ?B/s]

  Available splits : ['train', 'validation', 'test']
  Loading split    : 'train' ...

main/train-00000-of-00001.parquet:   0%|          | 0.00/496k [00:00<?, ?B/s]

main/validation-00000-of-00001.parquet:   0%|          | 0.00/58.2k [00:00<?, ?B/s]

main/test-00000-of-00001.parquet:   0%|          | 0.00/55.5k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/4957 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/500 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/500 [00:00<?, ? examples/s]

  ── Full dataset stats ──────────────────────────────────────
  Total rows  : 4957
  Columns     : ['id', 'question_stem', 'choices', 'answerKey']

  [id]
    dtype      : object
    sample val : '7-980'
    nulls      : 0
    n_unique   : 4957
    len dist   : {6: 2856, 5: 946, 7: 651, 4: 310, 3: 173, 2: 21}

  [question_stem]
    dtype      : object
    sample val : 'The sun is responsible for'
    nulls      : 0
    n_unique   : 4835
    len dist   : {38: 103, 46: 98, 41: 96, 47: 94, 49: 92, 45: 89, 40: 88, 37: 88, 36: 86, 34: 86, 59: 85, 54: 85, 52: 84, 30: 84, 44: 83, 42: 83, 32: 82, 39: 82, 35: 82, 55: 80, 48: 78, 51: 78, 33: 76, 57: 75, 29: 73, 58: 73, 63: 73, 43: 70, 60: 68, 28: 66, 56: 65, 25: 65, 50: 63, 53: 60, 27: 58, 31: 58, 62: 58, 61: 57, 67: 56, 66: 56, 65: 53, 73: 48, 72: 48, 64: 47, 26: 47, 69: 46, 68: 46, 23: 45, 71: 44, 78: 44, 21: 40, 77: 39, 22: 39, 79: 36, 74: 36, 70: 36, 83: 35, 75: 35, 20: 34, 82: 33, 24: 33, 76: 32, 87: 32, 80: 30, 84: 30, 85: 28, 19: 27, 91: 27, 90: 26, 18: 25, 89: 24, 88: 24, 93: 23, 86: 23, 81: 22, 101: 21, 95: 21, 17: 19, 106: 18, 96: 18, 100: 18, 97: 17, 14: 16, 15: 15, 102: 15, 13: 15, 99: 14, 110: 13, 107: 13, 92: 13, 98: 13, 16: 12, 104: 12, 105: 12, 11: 12, 12: 11, 112: 10, 10: 10, 103: 10, 116: 10, 109: 9, 111: 9, 94: 9, 113: 8, 129: 8, 114: 8, 122: 7, 131: 7, 108: 7, 9: 7, 117: 7, 138: 6, 146: 6, 120: 5, 133: 5, 123: 5, 151: 5, 118: 5, 127: 5, 8: 5, 128: 5, 153: 4, 130: 4, 140: 4, 187: 4, 115: 4, 126: 4, 142: 4, 137: 4, 6: 3, 195: 3, 160: 3, 149: 3, 4: 3, 144: 3, 161: 3, 168: 3, 132: 3, 192: 3, 150: 3, 134: 3, 141: 3, 165: 3, 125: 3, 7: 3, 135: 3, 152: 2, 5: 2, 204: 2, 119: 2, 121: 2, 148: 2, 178: 2, 136: 2, 157: 2, 155: 2, 158: 2, 174: 2, 124: 2, 171: 2, 215: 1, 208: 1, 255: 1, 159: 1, 1: 1, 201: 1, 139: 1, 185: 1, 333: 1, 227: 1, 295: 1, 164: 1, 264: 1, 172: 1, 232: 1, 230: 1, 147: 1, 222: 1, 282: 1, 199: 1, 190: 1, 218: 1, 200: 1, 169: 1, 156: 1, 184: 1, 166: 1, 143: 1, 256: 1, 197: 1, 167: 1, 188: 1, 179: 1, 217: 1, 209: 1, 154: 1, 211: 1}

  [choices]
    dtype      : object
    sample val : {'text': array(['puppies learning new tricks',
       'children growing up and getting old', 'flowers wilting in a vase'
    nulls      : 0
    n_unique   : unhashable (list/array column)
    len dist   : {2: 4957}

  [answerKey]
    dtype      : object
    sample val : 'D'
    nulls      : 0
    n_unique   : 4
    counts     : {'A': 1378, 'D': 1221, 'B': 1212, 'C': 1146}
    len dist   : {1: 4957}

  ── First 3 examples ──────────────────────────────────────
  ── Example 0 ────────────────────────────────────────
  id                  : '7-980'
  question_stem       : 'The sun is responsible for'
  choices             : {'text': ['puppies learning new tricks', 'children growing up and getting old', 'flowers wilting in a vase', 'plants sprouting, blooming and wilting'], 'label': ['A', 'B', 'C', 'D']}
  answerKey           : 'D'

  ── Example 1 ────────────────────────────────────────
  id                  : '7-584'
  question_stem       : 'When standing miles away from Mount Rushmore'
  choices             : {'text': ['the mountains seem very close', 'the mountains are boring', 'the mountains look the same as from up close', 'the mountains seem smaller than in photographs'], 'label': ['A', 'B', 'C', 'D']}
  answerKey           : 'D'

  ── Example 2 ────────────────────────────────────────
  id                  : '7-870'
  question_stem       : 'When food is reduced in the stomach'
  choices             : {'text': ['the mind needs time to digest', 'take a second to digest what I said', 'nutrients are being deconstructed', "reader's digest is a body of works"], 'label': ['A', 'B', 'C', 'D']}
  answerKey           : 'C'

  Returning sampled DataFrame — 250 rows (seed=42)

In [ ]:
print("Columns:", df_openbookqa.columns.tolist())
print()
print("Answer key distribution:")
print(df_openbookqa["answerKey"].value_counts())
print()
print("Choices structure (first row):")
print(df_openbookqa["choices"].iloc[0])
print()
print("Number of options per question:")
df_openbookqa["choices"].apply(lambda x: len(x["text"])).value_counts()

Columns: ['id', 'question_stem', 'choices', 'answerKey']

Answer key distribution:
answerKey
D    75
A    62
B    57
C    56
Name: count, dtype: int64

Choices structure (first row):
{'text': array(['on a hot street', 'in a basement', 'on a sunny day',
       'next to a window'], dtype=object), 'label': array(['A', 'B', 'C', 'D'], dtype=object)}

Number of options per question:

choices
4    250
Name: count, dtype: int64

## ARC
Reasoning

In [ ]:
from datasets import get_dataset_config_names
print(get_dataset_config_names("allenai/ai2_arc"))

README.md: 0.00B [00:00, ?B/s]

['ARC-Challenge', 'ARC-Easy']

In [ ]:
df_arc_easy = explore("allenai/ai2_arc", name="ARC-Easy", split="train", n=3, sample=250)

============================================================
  allenai/ai2_arc  |  config=ARC-Easy
============================================================
  Available splits : ['train', 'test', 'validation']
  Loading split    : 'train' ...

ARC-Easy/train-00000-of-00001.parquet:   0%|          | 0.00/331k [00:00<?, ?B/s]

ARC-Easy/test-00000-of-00001.parquet:   0%|          | 0.00/346k [00:00<?, ?B/s]

ARC-Easy/validation-00000-of-00001.parqu(…):   0%|          | 0.00/86.1k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/2251 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/2376 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/570 [00:00<?, ? examples/s]

  ── Full dataset stats ──────────────────────────────────────
  Total rows  : 2251
  Columns     : ['id', 'question', 'choices', 'answerKey']

  [id]
    dtype      : object
    sample val : 'Mercury_7220990'
    nulls      : 0
    n_unique   : 2251
    len dist   : {15: 911, 17: 459, 14: 351, 22: 147, 16: 125, 13: 104, 21: 63, 19: 44, 12: 17, 8: 16, 18: 14}

  [question]
    dtype      : object
    sample val : 'Which factor will most likely cause a person to develop a fever?'
    nulls      : 0
    n_unique   : 2245
    len dist   : {54: 34, 74: 32, 69: 32, 57: 27, 55: 25, 56: 24, 77: 24, 63: 24, 70: 24, 47: 24, 60: 24, 87: 23, 78: 23, 53: 23, 50: 22, 62: 22, 71: 22, 79: 22, 72: 22, 58: 21, 59: 21, 75: 21, 64: 21, 61: 20, 85: 19, 38: 19, 92: 19, 52: 19, 66: 19, 84: 19, 73: 19, 48: 19, 80: 19, 46: 19, 104: 18, 65: 18, 81: 18, 96: 18, 97: 18, 91: 18, 82: 18, 68: 18, 67: 17, 110: 17, 43: 17, 120: 17, 37: 17, 76: 16, 40: 16, 51: 15, 122: 15, 83: 15, 134: 15, 103: 14, 49: 14, 94: 14, 88: 14, 41: 14, 86: 14, 39: 13, 109: 13, 111: 13, 44: 13, 42: 13, 116: 12, 100: 12, 90: 12, 115: 12, 136: 11, 93: 11, 108: 11, 121: 11, 119: 11, 117: 11, 95: 10, 98: 10, 102: 10, 132: 10, 45: 10, 125: 10, 107: 10, 105: 10, 155: 10, 128: 10, 126: 10, 113: 10, 36: 10, 138: 9, 160: 9, 144: 9, 204: 9, 114: 9, 149: 9, 133: 9, 31: 9, 99: 9, 141: 9, 171: 9, 142: 8, 140: 8, 106: 8, 192: 8, 89: 8, 175: 8, 158: 8, 124: 8, 28: 8, 35: 8, 168: 8, 162: 7, 101: 7, 127: 7, 156: 7, 146: 7, 157: 7, 145: 7, 191: 7, 130: 7, 137: 7, 167: 7, 207: 7, 33: 7, 131: 7, 254: 7, 152: 7, 170: 7, 181: 6, 27: 6, 190: 6, 176: 6, 193: 6, 118: 6, 159: 6, 139: 6, 135: 6, 166: 6, 195: 6, 123: 6, 184: 6, 189: 6, 186: 6, 147: 6, 209: 6, 206: 6, 151: 6, 199: 6, 183: 6, 30: 5, 161: 5, 244: 5, 29: 5, 177: 5, 174: 5, 185: 5, 201: 5, 212: 5, 153: 5, 112: 5, 172: 5, 187: 5, 129: 5, 164: 4, 235: 4, 163: 4, 198: 4, 227: 4, 154: 4, 32: 4, 196: 4, 213: 4, 205: 4, 150: 4, 169: 4, 218: 4, 173: 4, 216: 3, 217: 3, 202: 3, 243: 3, 226: 3, 249: 3, 219: 3, 236: 3, 165: 3, 211: 3, 197: 3, 179: 3, 267: 3, 276: 3, 26: 3, 240: 3, 231: 3, 200: 3, 203: 3, 271: 3, 252: 3, 143: 3, 277: 3, 367: 2, 228: 2, 214: 2, 210: 2, 225: 2, 238: 2, 287: 2, 239: 2, 242: 2, 268: 2, 260: 2, 222: 2, 208: 2, 233: 2, 255: 2, 180: 2, 275: 2, 253: 2, 270: 2, 182: 2, 148: 2, 245: 2, 230: 2, 264: 2, 289: 2, 24: 2, 338: 2, 290: 2, 301: 2, 215: 2, 229: 2, 322: 2, 407: 2, 257: 2, 274: 2, 221: 2, 34: 2, 194: 2, 178: 2, 395: 2, 291: 2, 280: 1, 370: 1, 586: 1, 400: 1, 311: 1, 327: 1, 401: 1, 17: 1, 256: 1, 494: 1, 348: 1, 472: 1, 358: 1, 380: 1, 316: 1, 282: 1, 250: 1, 281: 1, 20: 1, 265: 1, 337: 1, 21: 1, 25: 1, 341: 1, 188: 1, 288: 1, 261: 1, 299: 1, 302: 1, 223: 1, 237: 1, 304: 1, 246: 1, 463: 1, 465: 1, 315: 1, 296: 1, 232: 1, 332: 1, 286: 1, 333: 1, 22: 1, 285: 1, 319: 1, 273: 1, 234: 1, 396: 1, 308: 1, 262: 1, 284: 1, 248: 1, 317: 1, 314: 1, 241: 1, 310: 1, 224: 1, 331: 1, 292: 1, 484: 1, 258: 1, 374: 1}

  [choices]
    dtype      : object
    sample val : {'text': array(['a leg muscle relaxing after exercise',
       'a bacterial population in the bloodstream',
       'seve
    nulls      : 0
    n_unique   : unhashable (list/array column)
    len dist   : {2: 2251}

  [answerKey]
    dtype      : object
    sample val : 'B'
    nulls      : 0
    n_unique   : 9
    counts     : {'B': 566, 'C': 545, 'A': 523, 'D': 513, '3': 33, '1': 25, '2': 22, '4': 22, 'E': 2}
    len dist   : {1: 2251}

  ── First 3 examples ──────────────────────────────────────
  ── Example 0 ────────────────────────────────────────
  id                  : 'Mercury_7220990'
  question            : 'Which factor will most likely cause a person to develop a fever?'
  choices             : {'text': ['a leg muscle relaxing after exercise', 'a bacterial population in the bloodstream', 'several viral particles on the skin', 'carbohydrates being digested in the stomach'], 'label': ['A', 'B', 'C', 'D']}
  answerKey           : 'B'

  ── Example 1 ────────────────────────────────────────
  id                  : 'MCAS_2007_8_5189'
  question            : 'Lichens are symbiotic organisms made of green algae and fungi. What do the green algae supply to the fungi in this symbiotic relationship?'
  choices             : {'text': ['carbon dioxide', 'food', 'protection', 'water'], 'label': ['A', 'B', 'C', 'D']}
  answerKey           : 'B'

  ── Example 2 ────────────────────────────────────────
  id                  : 'Mercury_SC_401169'
  question            : 'When a switch is used in an electrical circuit, the switch can'
  choices             : {'text': ['cause the charge to build.', 'increase and decrease the voltage.', 'cause the current to change direction.', 'stop and start the flow of current.'], 'label': ['A', 'B', 'C', 'D']}
  answerKey           : 'D'

  Returning sampled DataFrame — 250 rows (seed=42)

In [ ]:
print("Columns:", df_arc_easy.columns.tolist())
print()
print("Answer key distribution:")
print(df_arc_easy["answerKey"].value_counts())
print()
print("Number of options per question:")
df_arc_easy["choices"].apply(lambda x: len(x["text"])).value_counts()

Columns: ['id', 'question', 'choices', 'answerKey']

Answer key distribution:
answerKey
A    71
B    71
C    51
D    44
1     5
3     4
2     3
E     1
Name: count, dtype: int64

Number of options per question:

choices
4    248
5      1
3      1
Name: count, dtype: int64

In [ ]:
df_arc_challenge = explore("allenai/ai2_arc", name="ARC-Challenge", split="train", n=3, sample=250)

============================================================
  allenai/ai2_arc  |  config=ARC-Challenge
============================================================
  Available splits : ['train', 'test', 'validation']
  Loading split    : 'train' ...

  ── Full dataset stats ──────────────────────────────────────
  Total rows  : 1119
  Columns     : ['id', 'question', 'choices', 'answerKey']

  [id]
    dtype      : object
    sample val : 'Mercury_SC_415702'
    nulls      : 0
    n_unique   : 1119
    len dist   : {15: 480, 17: 222, 14: 186, 16: 80, 13: 56, 22: 31, 19: 28, 12: 12, 21: 11, 18: 7, 8: 6}

  [question]
    dtype      : object
    sample val : 'George wants to warm his hands quickly by rubbing them. Which skin surface will produce the most heat?'
    nulls      : 0
    n_unique   : 1118
    len dist   : {64: 14, 56: 14, 51: 14, 65: 14, 95: 14, 68: 13, 67: 13, 94: 13, 58: 13, 79: 12, 91: 12, 80: 11, 52: 11, 61: 11, 69: 11, 66: 10, 107: 10, 54: 10, 57: 10, 84: 10, 106: 10, 96: 9, 76: 9, 86: 9, 50: 9, 60: 9, 43: 9, 73: 9, 59: 8, 128: 8, 88: 8, 63: 8, 81: 8, 112: 8, 153: 8, 87: 8, 130: 8, 232: 8, 53: 8, 85: 8, 155: 7, 90: 7, 48: 7, 102: 7, 75: 7, 147: 7, 99: 7, 121: 7, 55: 7, 116: 7, 184: 7, 138: 6, 93: 6, 115: 6, 97: 6, 74: 6, 163: 6, 148: 6, 44: 6, 179: 6, 38: 6, 92: 6, 135: 6, 83: 6, 77: 6, 62: 6, 126: 6, 70: 6, 159: 6, 45: 6, 122: 6, 117: 6, 146: 6, 182: 5, 100: 5, 37: 5, 120: 5, 39: 5, 110: 5, 98: 5, 169: 5, 72: 5, 152: 5, 144: 5, 215: 5, 172: 5, 136: 5, 196: 5, 78: 5, 142: 5, 132: 5, 41: 5, 174: 5, 109: 5, 188: 5, 150: 5, 71: 5, 140: 5, 197: 4, 131: 4, 256: 4, 29: 4, 208: 4, 134: 4, 162: 4, 104: 4, 193: 4, 139: 4, 89: 4, 35: 4, 171: 4, 111: 4, 119: 4, 47: 4, 164: 4, 219: 4, 129: 4, 165: 4, 187: 4, 214: 4, 180: 4, 154: 4, 137: 4, 157: 4, 151: 4, 217: 3, 176: 3, 103: 3, 127: 3, 181: 3, 186: 3, 190: 3, 113: 3, 202: 3, 158: 3, 46: 3, 177: 3, 207: 3, 194: 3, 36: 3, 249: 3, 201: 3, 224: 3, 168: 3, 167: 3, 205: 3, 101: 3, 236: 3, 49: 3, 183: 3, 209: 3, 149: 3, 173: 3, 192: 3, 213: 3, 133: 3, 34: 3, 108: 3, 160: 3, 156: 3, 170: 3, 191: 3, 266: 3, 204: 3, 40: 3, 82: 3, 141: 3, 33: 3, 123: 3, 42: 3, 199: 3, 175: 3, 292: 3, 247: 2, 185: 2, 198: 2, 426: 2, 272: 2, 118: 2, 203: 2, 206: 2, 145: 2, 114: 2, 257: 2, 161: 2, 276: 2, 105: 2, 28: 2, 281: 2, 125: 2, 200: 2, 189: 2, 124: 2, 239: 2, 234: 2, 293: 2, 143: 2, 252: 2, 27: 2, 248: 1, 195: 1, 343: 1, 240: 1, 218: 1, 416: 1, 294: 1, 345: 1, 537: 1, 260: 1, 353: 1, 246: 1, 683: 1, 222: 1, 338: 1, 280: 1, 598: 1, 305: 1, 319: 1, 235: 1, 250: 1, 245: 1, 211: 1, 359: 1, 434: 1, 333: 1, 314: 1, 284: 1, 315: 1, 255: 1, 348: 1, 230: 1, 385: 1, 229: 1, 300: 1, 178: 1, 262: 1, 584: 1, 233: 1, 306: 1, 296: 1, 331: 1, 24: 1, 263: 1, 212: 1, 289: 1, 241: 1, 465: 1, 274: 1, 381: 1, 25: 1, 288: 1, 273: 1, 517: 1, 166: 1, 264: 1, 622: 1, 259: 1, 334: 1, 404: 1, 253: 1, 402: 1, 271: 1, 226: 1, 30: 1, 227: 1, 22: 1, 396: 1, 503: 1, 367: 1, 268: 1, 352: 1}

  [choices]
    dtype      : object
    sample val : {'text': array(['dry palms', 'wet palms', 'palms covered with oil',
       'palms covered with lotion'], dtype=object),
    nulls      : 0
    n_unique   : unhashable (list/array column)
    len dist   : {2: 1119}

  [answerKey]
    dtype      : object
    sample val : 'A'
    nulls      : 0
    n_unique   : 8
    counts     : {'B': 293, 'C': 287, 'D': 283, 'A': 233, '4': 10, '1': 6, '3': 4, '2': 3}
    len dist   : {1: 1119}

  ── First 3 examples ──────────────────────────────────────
  ── Example 0 ────────────────────────────────────────
  id                  : 'Mercury_SC_415702'
  question            : 'George wants to warm his hands quickly by rubbing them. Which skin surface will produce the most heat?'
  choices             : {'text': ['dry palms', 'wet palms', 'palms covered with oil', 'palms covered with lotion'], 'label': ['A', 'B', 'C', 'D']}
  answerKey           : 'A'

  ── Example 1 ────────────────────────────────────────
  id                  : 'MCAS_2009_5_6516'
  question            : 'Which of the following statements best explains why magnets usually stick to a refrigerator door?'
  choices             : {'text': ['The refrigerator door is smooth.', 'The refrigerator door contains iron.', 'The refrigerator door is a good conductor.', 'The refrigerator door has electric wires in it.'], 'label': ['A', 'B', 'C', 'D']}
  answerKey           : 'B'

  ── Example 2 ────────────────────────────────────────
  id                  : 'Mercury_7233695'
  question            : 'A fold observed in layers of sedimentary rock most likely resulted from the'
  choices             : {'text': ['cooling of flowing magma.', 'converging of crustal plates.', 'deposition of river sediments.', 'solution of carbonate minerals.'], 'label': ['A', 'B', 'C', 'D']}
  answerKey           : 'B'

  Returning sampled DataFrame — 250 rows (seed=42)

In [ ]:
print("Answer key distribution (Challenge):")
print(df_arc_challenge["answerKey"].value_counts())
print()
print("Number of options per question (Challenge):")
df_arc_challenge["choices"].apply(lambda x: len(x["text"])).value_counts()

Answer key distribution (Challenge):
answerKey
C    66
B    66
D    58
A    52
1     3
3     2
4     2
2     1
Name: count, dtype: int64

Number of options per question (Challenge):

choices
4    250
Name: count, dtype: int64

## MedQA USMLE

In [ ]:
df_medqa = explore("GBaker/MedQA-USMLE-4-options", name=None, split="train", n=3, sample=250)

============================================================
  GBaker/MedQA-USMLE-4-options  |  config=None
============================================================

README.md:   0%|          | 0.00/654 [00:00<?, ?B/s]

  Available splits : ['train', 'test']
  Loading split    : 'train' ...

phrases_no_exclude_train.jsonl:   0%|          | 0.00/16.2M [00:00<?, ?B/s]

phrases_no_exclude_test.jsonl: 0.00B [00:00, ?B/s]

Generating train split:   0%|          | 0/10178 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1273 [00:00<?, ? examples/s]

  ── Full dataset stats ──────────────────────────────────────
  Total rows  : 10178
  Columns     : ['question', 'answer', 'options', 'meta_info', 'answer_idx', 'metamap_phrases']

  [question]
    dtype      : object
    sample val : 'A 23-year-old pregnant woman at 22 weeks gestation presents with burning upon urination. She states it started 1 day ag
    nulls      : 0
    n_unique   : 10176
    len dist   : {633: 26, 532: 24, 576: 24, 678: 24, 755: 23, 601: 23, 624: 23, 555: 23, 652: 22, 535: 22, 638: 22, 700: 22, 579: 21, 666: 21, 475: 21, 699: 21, 717: 21, 626: 21, 542: 21, 692: 21, 545: 21, 740: 21, 778: 21, 695: 21, 546: 20, 674: 20, 655: 20, 756: 20, 726: 20, 707: 20, 605: 20, 524: 20, 512: 20, 693: 20, 432: 20, 493: 19, 815: 19, 882: 19, 548: 19, 784: 19, 688: 19, 704: 19, 727: 19, 639: 19, 722: 19, 623: 19, 574: 19, 565: 19, 541: 19, 648: 19, 617: 19, 822: 19, 690: 19, 609: 19, 683: 19, 809: 19, 568: 19, 580: 18, 491: 18, 575: 18, 610: 18, 495: 18, 663: 18, 572: 18, 714: 18, 817: 18, 559: 18, 488: 18, 672: 18, 651: 18, 711: 18, 553: 18, 600: 18, 668: 18, 779: 18, 713: 18, 640: 18, 879: 18, 480: 18, 790: 17, 502: 17, 630: 17, 620: 17, 525: 17, 643: 17, 701: 17, 774: 17, 689: 17, 670: 17, 584: 17, 732: 17, 731: 17, 611: 17, 538: 17, 720: 17, 653: 17, 567: 17, 705: 17, 628: 17, 520: 17, 761: 17, 846: 17, 877: 17, 552: 16, 888: 16, 743: 16, 658: 16, 591: 16, 659: 16, 531: 16, 800: 16, 571: 16, 595: 16, 599: 16, 390: 16, 953: 16, 585: 16, 562: 16, 597: 16, 662: 16, 526: 16, 697: 16, 602: 16, 858: 16, 577: 16, 561: 16, 835: 16, 539: 16, 560: 16, 586: 16, 490: 16, 455: 16, 813: 16, 752: 16, 898: 16, 851: 15, 464: 15, 508: 15, 686: 15, 443: 15, 573: 15, 769: 15, 671: 15, 467: 15, 673: 15, 878: 15, 747: 15, 614: 15, 709: 15, 856: 15, 785: 15, 618: 15, 603: 15, 900: 15, 819: 15, 764: 15, 594: 15, 929: 15, 675: 15, 906: 15, 730: 15, 715: 15, 866: 15, 847: 15, 650: 15, 608: 15, 389: 15, 440: 15, 741: 15, 396: 15, 476: 15, 708: 15, 667: 15, 558: 15, 474: 15, 921: 15, 660: 15, 556: 15, 706: 15, 912: 15, 384: 15, 637: 15, 899: 14, 645: 14, 797: 14, 691: 14, 807: 14, 592: 14, 466: 14, 527: 14, 438: 14, 557: 14, 777: 14, 685: 14, 862: 14, 786: 14, 631: 14, 489: 14, 793: 14, 596: 14, 590: 14, 570: 14, 910: 14, 528: 14, 759: 14, 681: 14, 504: 14, 550: 14, 770: 14, 801: 14, 483: 14, 647: 14, 751: 14, 547: 14, 734: 14, 703: 14, 509: 14, 702: 14, 808: 14, 864: 14, 753: 14, 543: 14, 619: 14, 501: 14, 516: 14, 766: 14, 890: 14, 449: 14, 448: 14, 799: 14, 437: 14, 905: 14, 725: 14, 503: 13, 787: 13, 523: 13, 505: 13, 415: 13, 507: 13, 903: 13, 684: 13, 948: 13, 698: 13, 511: 13, 718: 13, 593: 13, 665: 13, 621: 13, 925: 13, 446: 13, 876: 13, 644: 13, 470: 13, 416: 13, 810: 13, 694: 13, 445: 13, 615: 13, 533: 13, 506: 13, 682: 13, 518: 13, 435: 13, 950: 13, 587: 13, 589: 13, 710: 13, 424: 13, 649: 13, 664: 13, 782: 13, 669: 13, 622: 13, 880: 13, 450: 13, 859: 13, 816: 13, 729: 13, 514: 13, 441: 13, 616: 13, 635: 13, 529: 13, 632: 13, 746: 13, 657: 13, 814: 13, 875: 13, 739: 13, 676: 13, 1026: 13, 886: 13, 964: 13, 981: 13, 780: 13, 998: 13, 661: 13, 750: 13, 830: 13, 1056: 13, 765: 13, 924: 13, 820: 13, 772: 13, 869: 13, 850: 13, 487: 12, 863: 12, 1033: 12, 712: 12, 497: 12, 719: 12, 634: 12, 818: 12, 409: 12, 831: 12, 515: 12, 870: 12, 917: 12, 733: 12, 812: 12, 728: 12, 804: 12, 1020: 12, 431: 12, 408: 12, 380: 12, 937: 12, 794: 12, 938: 12, 656: 12, 867: 12, 767: 12, 566: 12, 811: 12, 471: 12, 868: 12, 654: 12, 783: 12, 395: 12, 737: 12, 985: 12, 884: 12, 838: 12, 983: 12, 771: 12, 680: 12, 646: 12, 544: 12, 430: 12, 642: 12, 975: 12, 872: 12, 582: 12, 472: 12, 498: 12, 417: 12, 569: 12, 482: 12, 829: 12, 530: 12, 821: 12, 629: 12, 583: 11, 791: 11, 834: 11, 907: 11, 372: 11, 469: 11, 374: 11, 500: 11, 447: 11, 971: 11, 398: 11, 1015: 11, 625: 11, 534: 11, 540: 11, 795: 11, 429: 11, 461: 11, 1024: 11, 947: 11, 486: 11, 857: 11, 958: 11, 844: 11, 485: 11, 410: 11, 853: 11, 563: 11, 439: 11, 889: 11, 796: 11, 383: 11, 860: 11, 848: 11, 537: 11, 454: 11, 914: 11, 788: 11, 460: 11, 434: 11, 991: 11, 428: 11, 581: 11, 854: 11, 942: 11, 1148: 11, 423: 11, 855: 11, 393: 11, 453: 11, 749: 11, 798: 11, 554: 11, 873: 11, 578: 11, 463: 11, 861: 11, 418: 11, 613: 11, 735: 11, 364: 11, 957: 11, 901: 11, 959: 11, 742: 11, 1013: 11, 421: 11, 961: 11, 452: 11, 679: 11, 745: 10, 468: 10, 803: 10, 1051: 10, 993: 10, 405: 10, 976: 10, 1008: 10, 724: 10, 378: 10, 960: 10, 404: 10, 331: 10, 347: 10, 641: 10, 549: 10, 479: 10, 517: 10, 1045: 10, 499: 10, 426: 10, 768: 10, 823: 10, 350: 10, 1037: 10, 904: 10, 473: 10, 781: 10, 894: 10, 513: 10, 598: 10, 892: 10, 936: 10, 943: 10, 946: 10, 833: 10, 494: 10, 386: 10, 422: 10, 716: 10, 465: 10, 736: 10, 895: 10, 481: 10, 636: 10, 456: 10, 363: 10, 696: 10, 510: 10, 789: 10, 891: 10, 1034: 10, 970: 10, 940: 10, 425: 10, 402: 10, 832: 10, 776: 10, 902: 10, 836: 10, 427: 10, 826: 10, 536: 9, 919: 9, 407: 9, 744: 9, 842: 9, 802: 9, 989: 9, 762: 9, 979: 9, 420: 9, 413: 9, 290: 9, 1052: 9, 687: 9, 478: 9, 419: 9, 382: 9, 963: 9, 881: 9, 1006: 9, 972: 9, 1004: 9, 738: 9, 399: 9, 941: 9, 923: 9, 327: 9, 433: 9, 366: 9, 980: 9, 280: 9, 522: 9, 827: 9, 887: 9, 849: 9, 459: 9, 839: 9, 1032: 9, 1044: 9, 315: 9, 997: 9, 885: 9, 931: 9, 992: 9, 918: 9, 392: 9, 1072: 9, 828: 9, 932: 9, 677: 9, 337: 9, 1107: 9, 1054: 9, 477: 9, 754: 9, 1068: 9, 312: 9, 723: 9, 564: 9, 588: 9, 994: 9, 348: 9, 351: 9, 825: 9, 607: 9, 982: 9, 874: 9, 935: 9, 357: 9, 484: 9, 954: 9, 1083: 9, 805: 9, 1014: 8, 945: 8, 346: 8, 1108: 8, 896: 8, 288: 8, 758: 8, 977: 8, 1007: 8, 1147: 8, 986: 8, 1041: 8, 551: 8, 359: 8, 806: 8, 1105: 8, 1073: 8, 1136: 8, 944: 8, 824: 8, 721: 8, 865: 8, 1029: 8, 627: 8, 1010: 8, 1058: 8, 376: 8, 952: 8, 1074: 8, 792: 8, 920: 8, 385: 8, 775: 8, 411: 8, 606: 8, 369: 8, 845: 8, 988: 8, 1093: 8, 322: 8, 457: 8, 909: 8, 1016: 8, 349: 8, 612: 8, 1048: 8, 521: 8, 458: 8, 757: 8, 1000: 8, 1050: 7, 1096: 7, 287: 7, 1200: 7, 1061: 7, 320: 7, 852: 7, 962: 7, 928: 7, 1215: 7, 1030: 7, 1031: 7, 371: 7, 375: 7, 1084: 7, 999: 7, 519: 7, 1154: 7, 397: 7, 773: 7, 913: 7, 403: 7, 871: 7, 897: 7, 951: 7, 1009: 7, 1017: 7, 995: 7, 303: 7, 1011: 7, 317: 7, 308: 7, 973: 7, 604: 7, 1071: 7, 1100: 7, 1190: 7, 340: 7, 412: 7, 492: 7, 763: 7, 984: 7, 345: 7, 1232: 7, 1046: 7, 387: 7, 1043: 7, 436: 7, 321: 7, 1069: 7, 268: 7, 262: 7, 400: 7, 1091: 6, 244: 6, 293: 6, 277: 6, 939: 6, 1027: 6, 368: 6, 748: 6, 356: 6, 1112: 6, 968: 6, 496: 6, 760: 6, 1134: 6, 451: 6, 1077: 6, 401: 6, 1118: 6, 355: 6, 978: 6, 1156: 6, 342: 6, 1002: 6, 930: 6, 275: 6, 1122: 6, 365: 6, 212: 6, 343: 6, 1035: 6, 843: 6, 1195: 6, 297: 6, 230: 6, 319: 6, 301: 6, 1062: 6, 444: 6, 1116: 6, 313: 6, 1078: 6, 284: 6, 391: 6, 1042: 6, 908: 6, 1066: 6, 1081: 6, 1222: 6, 1152: 6, 883: 6, 289: 6, 271: 6, 1005: 6, 1172: 6, 955: 6, 1123: 6, 933: 6, 987: 6, 373: 6, 414: 6, 1018: 6, 1157: 6, 1092: 6, 1139: 6, 974: 6, 1223: 6, 1021: 6, 965: 6, 394: 6, 442: 6, 260: 6, 307: 6, 1233: 6, 259: 5, 358: 5, 967: 5, 318: 5, 1001: 5, 257: 5, 1089: 5, 1099: 5, 1003: 5, 302: 5, 1250: 5, 256: 5, 1252: 5, 1101: 5, 285: 5, 1192: 5, 1047: 5, 335: 5, 379: 5, 1121: 5, 927: 5, 837: 5, 840: 5, 1088: 5, 324: 5, 1049: 5, 1244: 5, 235: 5, 462: 5, 966: 5, 263: 5, 1158: 5, 1012: 5, 1137: 5, 1022: 5, 1090: 5, 1175: 5, 1182: 5, 377: 5, 1378: 5, 341: 5, 1167: 5, 294: 5, 1125: 5, 1132: 5, 893: 5, 1067: 5, 291: 5, 1217: 5, 1025: 5, 339: 5, 1127: 5, 922: 5, 911: 5, 996: 5, 1113: 5, 1206: 5, 1039: 5, 1234: 5, 949: 5, 388: 5, 1258: 5, 926: 5, 1065: 5, 314: 5, 370: 5, 1070: 5, 1129: 5, 1131: 5, 1057: 5, 267: 5, 286: 5, 1124: 4, 278: 4, 1212: 4, 1159: 4, 1386: 4, 1028: 4, 1332: 4, 1186: 4, 1213: 4, 1197: 4, 361: 4, 305: 4, 264: 4, 1087: 4, 1144: 4, 1201: 4, 1163: 4, 916: 4, 367: 4, 213: 4, 1187: 4, 1104: 4, 1130: 4, 1580: 4, 298: 4, 274: 4, 214: 4, 229: 4, 1120: 4, 282: 4, 1126: 4, 1168: 4, 328: 4, 1086: 4, 1082: 4, 248: 4, 1102: 4, 316: 4, 381: 4, 1063: 4, 332: 4, 1111: 4, 1228: 4, 1075: 4, 270: 4, 841: 4, 353: 4, 1271: 4, 239: 4, 1221: 4, 296: 4, 1059: 4, 1170: 4, 233: 4, 1115: 4, 300: 4, 1114: 4, 196: 4, 990: 4, 209: 4, 1191: 4, 333: 4, 1181: 4, 1283: 4, 1055: 4, 1395: 4, 1256: 4, 201: 4, 1076: 4, 915: 4, 323: 4, 1293: 4, 329: 4, 1211: 4, 295: 4, 352: 4, 1019: 4, 1259: 4, 1106: 4, 354: 3, 1151: 3, 1155: 3, 310: 3, 232: 3, 1299: 3, 1140: 3, 1185: 3, 148: 3, 1196: 3, 1119: 3, 1322: 3, 299: 3, 1171: 3, 1424: 3, 1079: 3, 1349: 3, 338: 3, 1208: 3, 1204: 3, 1141: 3, 326: 3, 1360: 3, 330: 3, 1235: 3, 1146: 3, 1085: 3, 1094: 3, 1178: 3, 1162: 3, 1202: 3, 1257: 3, 1287: 3, 1183: 3, 1225: 3, 1053: 3, 1237: 3, 360: 3, 1023: 3, 1484: 3, 1260: 3, 1273: 3, 1143: 3, 309: 3, 304: 3, 406: 3, 1239: 3, 1366: 3, 334: 3, 1161: 3, 1596: 3, 1334: 3, 1493: 3, 1318: 3, 1169: 3, 226: 3, 1060: 3, 1328: 3, 283: 3, 249: 3, 1193: 3, 1040: 3, 956: 3, 934: 3, 1164: 3, 1117: 3, 1288: 3, 272: 3, 266: 2, 1133: 2, 1348: 2, 1737: 2, 1577: 2, 202: 2, 1194: 2, 1294: 2, 1216: 2, 216: 2, 221: 2, 1380: 2, 1296: 2, 258: 2, 1350: 2, 1214: 2, 1463: 2, 1630: 2, 1306: 2, 279: 2, 1251: 2, 1358: 2, 210: 2, 1184: 2, 186: 2, 1335: 2, 1403: 2, 1279: 2, 227: 2, 1314: 2, 1269: 2, 1485: 2, 344: 2, 1176: 2, 969: 2, 1203: 2, 247: 2, 1153: 2, 1458: 2, 1429: 2, 1138: 2, 1231: 2, 1561: 2, 1207: 2, 1365: 2, 224: 2, 1282: 2, 1268: 2, 1109: 2, 1292: 2, 198: 2, 1589: 2, 1509: 2, 336: 2, 164: 2, 1336: 2, 1240: 2, 1177: 2, 261: 2, 242: 2, 1274: 2, 1405: 2, 1301: 2, 311: 2, 1165: 2, 1224: 2, 1368: 2, 1415: 2, 254: 2, 1298: 2, 1376: 2, 325: 2, 1142: 2, 1098: 2, 1330: 2, 1297: 2, 1255: 2, 276: 2, 171: 2, 159: 2, 231: 2, 269: 2, 1699: 2, 1180: 2, 1354: 2, 1674: 2, 1265: 2, 89: 2, 1407: 2, 1097: 2, 1326: 2, 1411: 2, 1284: 2, 253: 2, 1459: 2, 123: 2, 1342: 2, 1323: 2, 1442: 2, 1227: 2, 246: 2, 1270: 2, 1482: 2, 1135: 2, 240: 2, 1506: 2, 1229: 2, 1226: 2, 1532: 2, 1689: 2, 1149: 2, 1036: 2, 1080: 2, 1179: 2, 1128: 2, 1410: 2, 1264: 2, 1236: 2, 1519: 2, 1421: 2, 1344: 2, 1160: 2, 1339: 2, 1241: 2, 83: 2, 1188: 2, 1220: 2, 1110: 2, 243: 2, 1247: 2, 1278: 2, 1347: 2, 1173: 1, 1356: 1, 1038: 1, 1502: 1, 1427: 1, 1488: 1, 1430: 1, 1472: 1, 1209: 1, 182: 1, 1261: 1, 1305: 1, 273: 1, 1563: 1, 1598: 1, 75: 1, 1950: 1, 281: 1, 1245: 1, 1550: 1, 1370: 1, 106: 1, 3577: 1, 1174: 1, 1357: 1, 170: 1, 200: 1, 1317: 1, 1542: 1, 1518: 1, 1343: 1, 1673: 1, 1438: 1, 1307: 1, 2142: 1, 1567: 1, 1353: 1, 223: 1, 153: 1, 1621: 1, 1540: 1, 1846: 1, 237: 1, 1541: 1, 251: 1, 1189: 1, 191: 1, 1479: 1, 92: 1, 1375: 1, 1692: 1, 1712: 1, 177: 1, 1371: 1, 162: 1, 1280: 1, 1662: 1, 183: 1, 1492: 1, 1480: 1, 1536: 1, 1526: 1, 1393: 1, 1409: 1, 1387: 1, 1404: 1, 2069: 1, 2015: 1, 1562: 1, 1412: 1, 255: 1, 1800: 1, 172: 1, 245: 1, 1454: 1, 1456: 1, 1824: 1, 1064: 1, 129: 1, 138: 1, 2084: 1, 1359: 1, 250: 1, 1166: 1, 236: 1, 1537: 1, 1628: 1, 1324: 1, 1312: 1, 1477: 1, 1616: 1, 1821: 1, 70: 1, 1362: 1, 1363: 1, 1441: 1, 1620: 1, 1253: 1, 113: 1, 1333: 1, 1500: 1, 215: 1, 1515: 1, 1900: 1, 1435: 1, 1499: 1, 1327: 1, 1428: 1, 1272: 1, 1877: 1, 1262: 1, 1555: 1, 137: 1, 1524: 1, 1815: 1, 1539: 1, 1439: 1, 1556: 1, 1697: 1, 169: 1, 1647: 1, 1668: 1, 225: 1, 1103: 1, 66: 1, 161: 1, 1481: 1, 1462: 1, 1394: 1, 265: 1, 1590: 1, 1198: 1, 81: 1, 151: 1, 1361: 1, 1503: 1, 218: 1, 1413: 1, 1565: 1, 1230: 1, 228: 1, 1467: 1, 1698: 1, 1319: 1, 173: 1, 1210: 1, 238: 1, 178: 1, 1736: 1, 1437: 1, 1367: 1, 306: 1, 1372: 1, 1447: 1, 1513: 1, 1150: 1, 1219: 1, 168: 1, 166: 1, 1558: 1, 1564: 1, 135: 1, 1723: 1, 1682: 1, 1451: 1, 1382: 1, 1755: 1, 1520: 1, 86: 1, 1310: 1, 195: 1, 1338: 1, 1095: 1, 184: 1, 1845: 1, 1571: 1, 1341: 1, 1595: 1, 1417: 1, 145: 1, 1286: 1, 1325: 1, 1303: 1, 2005: 1, 1277: 1, 1285: 1, 1337: 1, 362: 1, 1199: 1, 1352: 1, 208: 1, 1266: 1, 1373: 1, 174: 1, 1249: 1, 1379: 1, 1402: 1, 1316: 1, 1145: 1, 160: 1, 199: 1, 1473: 1, 1711: 1, 1433: 1, 1624: 1, 1267: 1, 1434: 1, 1570: 1, 1448: 1, 292: 1, 1281: 1, 1351: 1, 1724: 1, 111: 1, 143: 1, 2122: 1, 1469: 1, 1381: 1, 1313: 1, 1392: 1, 1331: 1, 1295: 1, 125: 1, 190: 1, 3556: 1, 147: 1, 1399: 1, 1728: 1, 1584: 1, 2109: 1, 1291: 1, 1398: 1, 1511: 1, 1289: 1, 205: 1, 1414: 1, 1321: 1, 121: 1, 72: 1, 188: 1, 108: 1, 1786: 1}

  [answer]
    dtype      : object
    sample val : 'Nitrofurantoin'
    nulls      : 0
    n_unique   : 8346
    len dist   : {11: 394, 10: 371, 18: 358, 20: 356, 12: 331, 22: 329, 17: 323, 16: 321, 21: 317, 19: 301, 9: 300, 25: 296, 14: 283, 24: 282, 15: 279, 13: 266, 23: 264, 28: 223, 27: 223, 26: 218, 29: 214, 30: 184, 7: 176, 32: 172, 35: 156, 8: 154, 33: 151, 31: 151, 34: 143, 36: 136, 38: 133, 39: 113, 37: 112, 40: 102, 44: 99, 42: 88, 41: 81, 43: 81, 6: 76, 3: 75, 46: 74, 45: 73, 4: 69, 48: 63, 47: 62, 5: 60, 53: 58, 50: 48, 49: 48, 54: 45, 52: 45, 51: 37, 55: 37, 63: 35, 61: 35, 56: 32, 58: 30, 57: 29, 66: 28, 60: 26, 64: 26, 67: 25, 62: 24, 1: 23, 70: 23, 68: 22, 65: 21, 74: 19, 69: 19, 72: 19, 59: 19, 71: 19, 2: 17, 75: 15, 73: 14, 78: 14, 76: 13, 89: 13, 79: 13, 80: 12, 94: 11, 87: 11, 82: 11, 85: 10, 77: 10, 88: 9, 83: 9, 96: 8, 84: 7, 90: 7, 91: 7, 109: 6, 104: 6, 81: 6, 102: 5, 97: 5, 117: 5, 123: 4, 106: 4, 95: 4, 86: 4, 124: 4, 93: 4, 92: 4, 99: 3, 113: 3, 107: 3, 140: 3, 149: 3, 114: 3, 110: 3, 103: 3, 108: 2, 142: 2, 126: 2, 158: 2, 129: 2, 134: 2, 118: 2, 105: 2, 100: 2, 111: 2, 161: 2, 98: 2, 119: 2, 122: 2, 125: 2, 130: 2, 160: 1, 186: 1, 145: 1, 164: 1, 168: 1, 157: 1, 162: 1, 133: 1, 147: 1, 131: 1, 153: 1, 150: 1, 195: 1, 101: 1, 191: 1, 156: 1, 183: 1, 112: 1, 141: 1, 116: 1, 159: 1, 167: 1, 136: 1, 230: 1, 152: 1}

  [options]
    dtype      : object
    sample val : {'A': 'Ampicillin', 'B': 'Ceftriaxone', 'C': 'Doxycycline', 'D': 'Nitrofurantoin'}
    nulls      : 0
    n_unique   : unhashable (list/array column)
    len dist   : {4: 10178}

  [meta_info]
    dtype      : object
    sample val : 'step2&3'
    nulls      : 0
    n_unique   : 2
    counts     : {'step1': 5629, 'step2&3': 4549}
    len dist   : {5: 5629, 7: 4549}

  [answer_idx]
    dtype      : object
    sample val : 'D'
    nulls      : 0
    n_unique   : 4
    counts     : {'B': 2654, 'A': 2584, 'C': 2557, 'D': 2383}
    len dist   : {1: 10178}

  [metamap_phrases]
    dtype      : object
    sample val : array(['23 year old pregnant woman', 'weeks presents', 'burning',
       'urination', 'states', 'started 1 day', 'worsen
    nulls      : 0
    n_unique   : unhashable (list/array column)
    len dist   : {30: 312, 31: 306, 27: 302, 34: 287, 26: 271, 29: 268, 28: 263, 23: 261, 32: 260, 35: 257, 33: 257, 25: 257, 24: 254, 41: 246, 22: 246, 36: 244, 40: 239, 39: 238, 37: 238, 42: 237, 38: 235, 21: 232, 43: 211, 45: 211, 20: 209, 19: 198, 48: 196, 18: 183, 47: 183, 44: 179, 46: 163, 49: 155, 17: 154, 50: 148, 52: 141, 51: 136, 16: 132, 53: 116, 54: 116, 15: 102, 56: 101, 14: 97, 55: 97, 13: 89, 59: 79, 58: 77, 12: 72, 57: 68, 60: 66, 11: 64, 61: 56, 63: 51, 65: 51, 62: 46, 10: 44, 64: 40, 66: 35, 9: 33, 68: 30, 69: 27, 70: 26, 67: 21, 73: 21, 8: 18, 78: 18, 71: 17, 72: 15, 75: 13, 76: 11, 74: 11, 6: 11, 7: 11, 77: 11, 79: 9, 80: 8, 84: 8, 3: 7, 87: 7, 4: 6, 85: 6, 5: 6, 82: 5, 91: 5, 88: 5, 89: 4, 81: 4, 86: 4, 83: 3, 92: 3, 127: 2, 93: 2, 116: 1, 103: 1, 104: 1, 97: 1, 123: 1, 99: 1, 106: 1, 95: 1, 1: 1, 184: 1, 108: 1, 120: 1, 100: 1, 177: 1}

  ── First 3 examples ──────────────────────────────────────
  ── Example 0 ────────────────────────────────────────
  question            : 'A 23-year-old pregnant woman at 22 weeks gestation presents with burning upon urination. She states it started 1 day ago and has been worsening despite drinking more water and taking cranberry extract. She otherwise feels well and is followed by a d
  answer              : 'Nitrofurantoin'
  options             : {'A': 'Ampicillin', 'B': 'Ceftriaxone', 'C': 'Doxycycline', 'D': 'Nitrofurantoin'}
  meta_info           : 'step2&3'
  answer_idx          : 'D'
  metamap_phrases     : ['23 year old pregnant woman', 'weeks presents', 'burning', 'urination', 'states', 'started 1 day', 'worsening', 'drinking', 'water', 'taking cranberry extract', 'feels well', 'followed by', 'doctor', 'pregnancy', 'temperature', '97', '36', 'blood pr

  ── Example 1 ────────────────────────────────────────
  question            : 'A 3-month-old baby died suddenly at night while asleep. His mother noticed that he had died only after she awoke in the morning. No cause of death was determined based on the autopsy. Which of the following precautions could have prevented the death
  answer              : 'Placing the infant in a supine position on a firm mattress while sleeping'
  options             : {'A': 'Placing the infant in a supine position on a firm mattress while sleeping', 'B': 'Keeping the infant covered and maintaining a high room temperature', 'C': 'Application of a device to maintain the sleeping position', 'D': 'Avoiding pacifier us
  meta_info           : 'step2&3'
  answer_idx          : 'A'
  metamap_phrases     : ['3 month old baby died', 'night', 'asleep', 'mother', 'died only', 'awoke in', 'morning', 'cause of death', 'based', 'autopsy', 'following precautions', 'prevented', 'death', 'baby']

  ── Example 2 ────────────────────────────────────────
  question            : "A mother brings her 3-week-old infant to the pediatrician's office because she is concerned about his feeding habits. He was born without complications and has not had any medical problems up until this time. However, for the past 4 days, he has bee
  answer              : 'Abnormal migration of ventral pancreatic bud'
  options             : {'A': 'Abnormal migration of ventral pancreatic bud', 'B': 'Complete failure of proximal duodenum to recanalize', 'C': 'Abnormal hypertrophy of the pylorus', 'D': 'Failure of lateral body folds to move ventrally and fuse in the midline'}
  meta_info           : 'step1'
  answer_idx          : 'A'
  metamap_phrases     : ['mother', 'week old infant', "pediatrician's office", 'concerned', 'feeding habits', 'born', 'complications', 'not', 'medical problems', 'time', 'past', 'days', 'fussy', 'regurgitating', 'feeds', 'vomit', 'yellow', 'color', 'physical exam', "child's

  Returning sampled DataFrame — 250 rows (seed=42)

In [ ]:
print("Columns:", df_medqa.columns.tolist())
print()
print("Answer distribution:")
print(df_medqa["answer_idx"].value_counts())
print()
print("Number of options per question:")
df_medqa["options"].apply(lambda x: len(x)).value_counts()
print()
print("Meta info distribution:")
print(df_medqa["meta_info"].value_counts())

Columns: ['question', 'answer', 'options', 'meta_info', 'answer_idx', 'metamap_phrases']

Answer distribution:
answer_idx
C    76
D    64
B    58
A    52
Name: count, dtype: int64

Number of options per question:

Meta info distribution:
meta_info
step1      141
step2&3    109
Name: count, dtype: int64

## MedMCQA

In [ ]:
df_medmcqa = explore("openlifescienceai/medmcqa", name=None, split="train", n=3, sample=250)

============================================================
  openlifescienceai/medmcqa  |  config=None
============================================================

README.md: 0.00B [00:00, ?B/s]

  Available splits : ['train', 'test', 'validation']
  Loading split    : 'train' ...

data/train-00000-of-00001.parquet:   0%|          | 0.00/85.9M [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/936k [00:00<?, ?B/s]

data/validation-00000-of-00001.parquet:   0%|          | 0.00/1.48M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/182822 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/6150 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/4183 [00:00<?, ? examples/s]

  ── Full dataset stats ──────────────────────────────────────
  Total rows  : 182822
  Columns     : ['id', 'question', 'opa', 'opb', 'opc', 'opd', 'cop', 'choice_type', 'exp', 'subject_name', 'topic_name']

  [id]
    dtype      : object
    sample val : 'e9ad821a-c438-4965-9f77-760819dfa155'
    nulls      : 0
    n_unique   : 182822
    len dist   : {36: 182822}

  [question]
    dtype      : object
    sample val : 'Chronic urethral obstruction due to benign prismatic hyperplasia can lead to the following change in kidney parenchyma'
    nulls      : 0
    n_unique   : 182822
    len dist   : {41: 3086, 43: 3061, 42: 3048, 40: 3016, 44: 3007, 48: 2967, 46: 2958, 45: 2941, 37: 2931, 38: 2928, 47: 2900, 39: 2898, 49: 2861, 36: 2836, 35: 2813, 34: 2792, 50: 2790, 51: 2697, 52: 2682, 33: 2601, 32: 2592, 53: 2542, 54: 2535, 31: 2524, 56: 2379, 55: 2378, 30: 2368, 58: 2303, 59: 2301, 60: 2243, 61: 2213, 57: 2196, 62: 2189, 29: 2175, 64: 2102, 63: 2076, 28: 2056, 65: 1995, 27: 1953, 66: 1889, 68: 1855, 26: 1825, 67: 1821, 69: 1761, 70: 1655, 25: 1652, 71: 1631, 72: 1551, 73: 1521, 24: 1459, 74: 1423, 75: 1326, 76: 1313, 77: 1257, 23: 1255, 78: 1161, 80: 1134, 79: 1125, 22: 1096, 81: 1053, 82: 1020, 83: 991, 21: 972, 85: 968, 84: 884, 86: 880, 87: 855, 20: 845, 88: 842, 89: 821, 90: 818, 91: 710, 19: 698, 92: 677, 93: 673, 94: 669, 95: 607, 18: 578, 96: 578, 97: 554, 99: 520, 98: 505, 100: 500, 102: 487, 101: 486, 17: 484, 103: 461, 16: 418, 105: 417, 104: 416, 108: 408, 106: 398, 109: 394, 15: 391, 110: 388, 107: 387, 111: 387, 112: 341, 114: 319, 113: 319, 120: 318, 119: 302, 121: 294, 122: 293, 123: 280, 115: 273, 14: 272, 118: 271, 116: 271, 117: 270, 125: 246, 128: 246, 126: 244, 133: 241, 124: 240, 132: 237, 129: 236, 131: 232, 127: 227, 134: 226, 130: 216, 135: 207, 142: 207, 137: 205, 141: 205, 136: 203, 13: 201, 144: 199, 139: 196, 143: 190, 140: 186, 138: 185, 153: 185, 148: 183, 145: 182, 146: 182, 149: 178, 150: 177, 158: 173, 157: 171, 155: 171, 152: 169, 151: 169, 12: 165, 163: 163, 165: 149, 154: 146, 156: 146, 147: 146, 160: 146, 169: 142, 164: 142, 168: 141, 162: 140, 166: 140, 167: 139, 170: 138, 180: 137, 179: 135, 184: 134, 161: 132, 198: 132, 210: 124, 176: 123, 185: 123, 181: 122, 172: 121, 182: 120, 173: 118, 159: 117, 174: 116, 11: 116, 197: 114, 175: 113, 202: 113, 204: 111, 171: 111, 177: 111, 183: 110, 188: 109, 196: 108, 191: 106, 189: 106, 187: 104, 186: 103, 201: 102, 203: 102, 209: 102, 178: 101, 212: 101, 214: 99, 194: 98, 199: 96, 218: 95, 226: 95, 195: 95, 190: 94, 206: 94, 205: 94, 213: 93, 10: 90, 207: 88, 192: 88, 200: 88, 217: 87, 220: 85, 193: 85, 227: 84, 208: 83, 228: 83, 215: 82, 233: 82, 224: 80, 248: 79, 222: 79, 225: 78, 221: 77, 247: 76, 219: 75, 234: 73, 216: 73, 211: 72, 232: 72, 223: 71, 241: 71, 230: 71, 240: 70, 258: 70, 235: 70, 250: 69, 270: 68, 231: 66, 246: 65, 264: 64, 239: 64, 249: 63, 254: 62, 229: 62, 243: 62, 257: 61, 255: 59, 260: 59, 273: 58, 251: 58, 267: 58, 268: 57, 244: 57, 236: 57, 252: 56, 285: 56, 259: 56, 253: 56, 238: 56, 282: 55, 290: 54, 274: 54, 286: 54, 237: 54, 281: 53, 266: 53, 242: 52, 272: 52, 271: 52, 280: 49, 292: 49, 265: 49, 279: 48, 9: 48, 278: 47, 263: 47, 303: 47, 245: 47, 283: 47, 256: 46, 275: 46, 269: 45, 316: 44, 321: 43, 284: 43, 261: 43, 262: 42, 315: 42, 277: 42, 291: 41, 287: 40, 302: 40, 305: 40, 299: 40, 289: 40, 308: 40, 322: 39, 304: 39, 295: 39, 314: 38, 306: 38, 323: 38, 296: 38, 301: 37, 337: 37, 309: 37, 307: 36, 356: 36, 293: 36, 288: 36, 298: 36, 336: 34, 276: 34, 318: 34, 311: 34, 325: 33, 361: 33, 343: 32, 332: 32, 329: 32, 297: 32, 317: 32, 319: 31, 334: 31, 310: 31, 294: 31, 333: 31, 8: 30, 324: 30, 330: 29, 371: 29, 348: 29, 327: 29, 376: 29, 300: 29, 326: 28, 342: 28, 339: 28, 335: 28, 340: 28, 363: 28, 320: 28, 357: 27, 358: 27, 344: 27, 362: 27, 380: 26, 383: 26, 353: 26, 331: 25, 7: 25, 370: 25, 338: 25, 378: 25, 312: 25, 364: 25, 360: 25, 393: 24, 375: 24, 366: 24, 437: 24, 386: 24, 392: 24, 359: 24, 368: 24, 350: 24, 369: 24, 406: 24, 345: 23, 373: 23, 390: 23, 372: 23, 400: 23, 354: 23, 328: 23, 387: 23, 391: 23, 313: 22, 384: 22, 377: 22, 346: 22, 349: 22, 365: 22, 399: 22, 397: 22, 382: 21, 388: 21, 351: 21, 355: 21, 367: 21, 419: 21, 395: 20, 389: 20, 404: 20, 416: 20, 341: 20, 381: 19, 398: 19, 396: 19, 427: 19, 403: 19, 347: 19, 410: 18, 352: 18, 474: 18, 414: 18, 374: 18, 385: 18, 409: 18, 422: 18, 412: 18, 394: 17, 430: 17, 429: 17, 431: 17, 421: 17, 401: 17, 450: 16, 454: 16, 379: 16, 426: 16, 457: 16, 476: 15, 460: 15, 423: 15, 413: 15, 432: 15, 443: 15, 467: 15, 438: 15, 490: 15, 440: 15, 517: 14, 451: 14, 402: 14, 417: 14, 489: 14, 488: 14, 435: 14, 405: 14, 498: 14, 463: 13, 452: 13, 472: 13, 471: 13, 497: 13, 6: 13, 493: 13, 486: 13, 425: 13, 407: 13, 499: 12, 479: 12, 505: 12, 444: 12, 501: 12, 428: 12, 411: 12, 496: 12, 434: 12, 418: 12, 455: 12, 540: 12, 503: 11, 415: 11, 507: 11, 480: 11, 461: 11, 500: 11, 420: 11, 442: 11, 468: 11, 554: 10, 470: 10, 502: 10, 445: 10, 453: 10, 539: 10, 509: 10, 553: 10, 447: 10, 478: 10, 433: 10, 492: 10, 462: 10, 459: 10, 541: 9, 446: 9, 424: 9, 439: 9, 511: 9, 495: 9, 531: 9, 441: 9, 473: 9, 583: 9, 465: 9, 504: 9, 523: 9, 533: 9, 525: 9, 485: 9, 592: 9, 515: 9, 551: 9, 510: 9, 436: 8, 482: 8, 548: 8, 469: 8, 563: 8, 534: 8, 519: 8, 514: 8, 604: 8, 520: 8, 487: 8, 522: 7, 518: 7, 530: 7, 588: 7, 599: 7, 565: 7, 513: 7, 577: 7, 449: 7, 573: 7, 732: 7, 643: 7, 571: 7, 580: 7, 584: 7, 491: 7, 542: 7, 475: 7, 458: 7, 558: 7, 547: 7, 569: 7, 483: 6, 484: 6, 622: 6, 662: 6, 602: 6, 552: 6, 600: 6, 526: 6, 624: 6, 516: 6, 555: 6, 566: 6, 610: 6, 527: 6, 562: 6, 506: 6, 633: 6, 590: 6, 570: 6, 408: 6, 545: 6, 512: 6, 560: 6, 456: 6, 575: 5, 660: 5, 626: 5, 586: 5, 629: 5, 597: 5, 521: 5, 448: 5, 615: 5, 477: 5, 532: 5, 582: 5, 747: 5, 653: 5, 635: 5, 645: 5, 574: 5, 663: 5, 508: 5, 611: 5, 665: 5, 556: 5, 655: 5, 621: 5, 641: 5, 658: 5, 557: 5, 619: 5, 647: 5, 561: 5, 549: 4, 529: 4, 694: 4, 589: 4, 607: 4, 464: 4, 616: 4, 535: 4, 572: 4, 596: 4, 636: 4, 620: 4, 578: 4, 745: 4, 664: 4, 638: 4, 623: 4, 528: 4, 733: 4, 711: 4, 466: 4, 544: 4, 613: 4, 536: 4, 634: 4, 652: 4, 591: 4, 581: 4, 630: 4, 594: 4, 605: 4, 661: 4, 579: 3, 678: 3, 593: 3, 700: 3, 713: 3, 567: 3, 775: 3, 701: 3, 559: 3, 809: 3, 672: 3, 674: 3, 598: 3, 691: 3, 707: 3, 524: 3, 494: 3, 609: 3, 587: 3, 481: 3, 651: 3, 734: 3, 682: 3, 699: 3, 729: 3, 788: 3, 628: 3, 546: 3, 712: 3, 717: 3, 657: 3, 668: 3, 709: 3, 644: 3, 608: 3, 632: 3, 680: 3, 543: 3, 722: 3, 681: 3, 538: 3, 843: 3, 5: 3, 679: 3, 618: 3, 720: 3, 640: 3, 564: 3, 721: 3, 781: 3, 601: 3, 727: 2, 770: 2, 786: 2, 1071: 2, 684: 2, 688: 2, 693: 2, 595: 2, 846: 2, 780: 2, 802: 2, 853: 2, 736: 2, 746: 2, 695: 2, 773: 2, 692: 2, 858: 2, 795: 2, 650: 2, 667: 2, 659: 2, 656: 2, 765: 2, 714: 2, 627: 2, 741: 2, 704: 2, 537: 2, 646: 2, 728: 2, 932: 2, 697: 2, 845: 2, 606: 2, 687: 2, 933: 2, 670: 2, 761: 2, 689: 2, 673: 2, 748: 2, 806: 2, 797: 2, 671: 2, 875: 2, 675: 2, 740: 2, 568: 2, 710: 2, 585: 2, 758: 2, 612: 2, 811: 2, 649: 2, 801: 2, 768: 2, 815: 2, 798: 1, 823: 1, 830: 1, 750: 1, 799: 1, 669: 1, 777: 1, 817: 1, 731: 1, 909: 1, 774: 1, 666: 1, 756: 1, 1121: 1, 928: 1, 1026: 1, 804: 1, 1181: 1, 851: 1, 862: 1, 796: 1, 686: 1, 683: 1, 956: 1, 939: 1, 576: 1, 690: 1, 920: 1, 868: 1, 856: 1, 984: 1, 738: 1, 924: 1, 1568: 1, 890: 1, 715: 1, 735: 1, 742: 1, 965: 1, 631: 1, 923: 1, 865: 1, 771: 1, 837: 1, 708: 1, 648: 1, 808: 1, 800: 1, 763: 1, 914: 1, 873: 1, 706: 1, 743: 1, 1: 1, 737: 1, 896: 1, 878: 1, 1047: 1, 1275: 1, 603: 1, 772: 1, 895: 1, 921: 1, 1144: 1, 757: 1, 723: 1, 769: 1, 784: 1, 782: 1, 1222: 1, 767: 1, 891: 1, 864: 1, 1154: 1, 716: 1, 1401: 1, 1335: 1, 642: 1, 753: 1, 696: 1, 1002: 1, 898: 1, 940: 1, 969: 1, 787: 1, 785: 1, 807: 1, 654: 1, 881: 1, 903: 1, 1059: 1, 1068: 1, 614: 1, 931: 1, 637: 1, 766: 1, 625: 1, 759: 1, 863: 1, 776: 1, 904: 1, 1064: 1, 935: 1, 754: 1, 810: 1, 793: 1, 883: 1, 859: 1, 1006: 1, 639: 1, 1053: 1, 930: 1, 698: 1, 849: 1, 953: 1, 884: 1, 870: 1, 850: 1, 908: 1, 971: 1, 1058: 1, 833: 1, 803: 1}

  [opa]
    dtype      : object
    sample val : 'Hyperplasia'
    nulls      : 0
    n_unique   : 79939
    len dist   : {11: 9314, 10: 9205, 12: 8755, 9: 8592, 8: 8297, 13: 8089, 7: 7853, 15: 7314, 14: 7299, 16: 6692, 18: 6390, 17: 6344, 3: 6277, 6: 5690, 19: 5444, 20: 5265, 21: 4719, 4: 4541, 22: 4539, 5: 4431, 23: 3597, 24: 3452, 2: 2851, 25: 2819, 26: 2564, 28: 2154, 27: 2150, 29: 1873, 30: 1735, 1: 1659, 31: 1600, 32: 1434, 33: 1383, 34: 1240, 35: 1179, 37: 1118, 36: 988, 38: 870, 39: 847, 40: 833, 42: 743, 41: 707, 43: 622, 44: 575, 45: 525, 47: 525, 46: 486, 49: 445, 50: 434, 48: 415, 51: 382, 53: 348, 52: 337, 55: 307, 54: 277, 56: 260, 57: 260, 58: 251, 59: 230, 60: 199, 62: 167, 61: 158, 65: 155, 63: 146, 67: 135, 64: 131, 68: 121, 66: 121, 69: 103, 72: 98, 71: 96, 75: 96, 76: 92, 70: 91, 74: 86, 73: 71, 78: 69, 79: 68, 82: 67, 84: 55, 80: 54, 77: 52, 86: 47, 93: 47, 85: 45, 81: 43, 83: 40, 87: 29, 88: 29, 94: 29, 92: 28, 102: 24, 89: 24, 96: 24, 91: 23, 95: 23, 90: 23, 100: 23, 97: 21, 99: 19, 112: 19, 104: 17, 103: 17, 101: 15, 106: 15, 109: 15, 98: 15, 105: 14, 118: 12, 111: 10, 116: 10, 113: 9, 120: 8, 110: 8, 108: 7, 117: 7, 115: 6, 127: 6, 132: 5, 107: 5, 134: 5, 122: 5, 114: 5, 129: 5, 153: 5, 121: 4, 152: 4, 133: 4, 123: 3, 136: 3, 128: 3, 126: 3, 135: 3, 137: 3, 139: 3, 125: 3, 150: 2, 131: 2, 147: 2, 172: 2, 174: 2, 124: 2, 181: 2, 180: 2, 169: 1, 201: 1, 205: 1, 140: 1, 208: 1, 185: 1, 231: 1, 194: 1, 145: 1, 130: 1, 168: 1, 138: 1, 165: 1, 287: 1, 156: 1, 151: 1, 190: 1, 184: 1, 142: 1, 265: 1, 119: 1, 160: 1, 199: 1, 148: 1, 175: 1, 163: 1, 171: 1, 144: 1}

  [opb]
    dtype      : object
    sample val : 'Hyperophy'
    nulls      : 0
    n_unique   : 83459
    len dist   : {11: 9421, 10: 9003, 12: 8805, 9: 8655, 8: 8191, 13: 8037, 7: 7387, 14: 7343, 15: 7147, 16: 6659, 18: 6491, 17: 6262, 3: 5827, 19: 5596, 20: 5412, 6: 5293, 21: 4779, 22: 4481, 5: 4079, 4: 3993, 23: 3750, 24: 3527, 2: 2981, 25: 2971, 26: 2755, 27: 2442, 28: 2183, 29: 1907, 30: 1891, 31: 1629, 32: 1577, 1: 1505, 33: 1325, 34: 1235, 35: 1216, 37: 1067, 36: 1051, 38: 938, 39: 922, 40: 888, 41: 760, 42: 748, 44: 675, 43: 648, 45: 603, 46: 512, 49: 492, 47: 490, 48: 469, 50: 408, 51: 389, 52: 379, 54: 331, 53: 311, 55: 296, 56: 276, 58: 258, 57: 240, 59: 237, 60: 211, 63: 199, 62: 178, 64: 171, 61: 169, 66: 160, 65: 143, 67: 142, 68: 141, 69: 124, 71: 110, 74: 109, 70: 107, 73: 102, 72: 94, 75: 92, 80: 76, 81: 76, 83: 75, 76: 75, 77: 70, 79: 63, 82: 62, 78: 59, 84: 49, 90: 39, 87: 37, 88: 35, 85: 35, 86: 33, 94: 33, 89: 32, 96: 29, 91: 27, 100: 27, 92: 25, 102: 24, 97: 23, 95: 23, 98: 22, 101: 22, 93: 21, 104: 20, 103: 20, 99: 20, 105: 16, 125: 13, 112: 11, 111: 11, 113: 11, 106: 10, 107: 10, 108: 10, 124: 10, 122: 9, 109: 9, 129: 8, 135: 7, 115: 7, 117: 7, 114: 6, 127: 6, 118: 6, 130: 6, 151: 6, 123: 6, 110: 5, 120: 5, 126: 5, 137: 4, 136: 4, 154: 4, 119: 4, 133: 4, 145: 3, 149: 3, 134: 3, 128: 3, 121: 3, 152: 2, 202: 2, 131: 2, 141: 2, 139: 2, 165: 2, 157: 2, 140: 2, 138: 1, 205: 1, 180: 1, 224: 1, 172: 1, 212: 1, 176: 1, 287: 1, 247: 1, 277: 1, 158: 1, 170: 1, 178: 1, 132: 1, 278: 1, 159: 1, 116: 1, 146: 1, 175: 1, 144: 1, 173: 1, 164: 1, 156: 1, 155: 1}

  [opc]
    dtype      : object
    sample val : 'Atrophy'
    nulls      : 0
    n_unique   : 84680
    len dist   : {11: 9079, 10: 8942, 9: 8597, 12: 8504, 8: 8210, 13: 8053, 15: 7308, 14: 7282, 7: 6993, 16: 6617, 17: 6444, 18: 6414, 3: 5739, 19: 5423, 20: 5256, 21: 5032, 6: 4951, 22: 4581, 4: 4213, 5: 4102, 24: 3889, 23: 3830, 2: 3207, 25: 3039, 26: 2867, 27: 2446, 28: 2315, 29: 1948, 30: 1826, 31: 1745, 32: 1442, 33: 1418, 35: 1280, 34: 1252, 37: 1084, 36: 1047, 38: 976, 1: 906, 39: 894, 40: 841, 41: 760, 44: 697, 42: 689, 43: 683, 46: 594, 45: 557, 48: 523, 47: 516, 49: 455, 50: 446, 53: 415, 54: 388, 52: 385, 51: 373, 56: 347, 55: 331, 57: 306, 58: 282, 59: 262, 61: 247, 62: 216, 60: 211, 63: 197, 64: 193, 65: 181, 66: 163, 67: 139, 70: 133, 69: 129, 68: 119, 71: 108, 72: 100, 75: 98, 73: 94, 74: 88, 76: 88, 78: 77, 77: 66, 81: 63, 84: 63, 80: 61, 83: 56, 79: 55, 82: 48, 88: 44, 87: 43, 86: 43, 85: 41, 90: 31, 93: 30, 91: 29, 92: 27, 97: 27, 89: 27, 101: 26, 103: 25, 99: 23, 94: 23, 96: 21, 95: 19, 104: 17, 108: 17, 109: 17, 98: 14, 111: 13, 115: 13, 102: 13, 121: 12, 114: 12, 118: 10, 110: 9, 106: 9, 116: 8, 126: 8, 113: 8, 107: 8, 117: 7, 144: 7, 100: 7, 105: 7, 128: 6, 134: 6, 129: 6, 125: 6, 127: 6, 152: 5, 119: 5, 162: 4, 154: 4, 140: 4, 112: 4, 143: 4, 146: 4, 122: 4, 145: 3, 168: 3, 138: 3, 130: 3, 124: 3, 120: 3, 123: 3, 131: 3, 149: 2, 160: 2, 141: 2, 139: 2, 166: 2, 132: 2, 150: 2, 155: 2, 137: 2, 133: 1, 142: 1, 159: 1, 147: 1, 163: 1, 167: 1, 165: 1, 135: 1, 151: 1, 193: 1, 232: 1, 178: 1, 157: 1, 286: 1, 258: 1, 240: 1, 156: 1, 148: 1, 164: 1, 136: 1, 253: 1, 199: 1, 153: 1}

  [opd]
    dtype      : object
    sample val : 'Dyplasia'
    nulls      : 0
    n_unique   : 80444
    len dist   : {16: 10090, 17: 9195, 11: 8738, 12: 8575, 10: 8568, 13: 7827, 9: 7783, 8: 7493, 3: 6949, 15: 6702, 14: 6661, 7: 6529, 4: 6247, 18: 5998, 20: 5160, 19: 4977, 21: 4689, 6: 4597, 22: 4342, 5: 3749, 24: 3555, 23: 3451, 2: 3053, 25: 2746, 26: 2518, 27: 2255, 28: 2007, 30: 1830, 29: 1810, 31: 1628, 32: 1388, 33: 1302, 34: 1239, 35: 1095, 1: 1026, 37: 1009, 36: 978, 38: 948, 39: 901, 40: 850, 42: 774, 44: 691, 41: 668, 43: 665, 45: 608, 46: 528, 47: 487, 49: 474, 48: 472, 50: 417, 52: 369, 51: 367, 53: 354, 55: 329, 54: 316, 56: 292, 57: 289, 58: 267, 59: 248, 61: 220, 63: 218, 62: 198, 64: 193, 60: 182, 66: 169, 65: 158, 70: 133, 69: 115, 67: 114, 68: 110, 72: 107, 71: 96, 78: 92, 76: 92, 74: 81, 75: 79, 73: 78, 80: 76, 82: 74, 81: 73, 79: 67, 77: 66, 84: 54, 83: 53, 88: 53, 89: 53, 86: 44, 87: 43, 85: 43, 91: 40, 90: 36, 93: 33, 97: 30, 92: 29, 94: 26, 108: 21, 95: 21, 96: 20, 101: 20, 98: 19, 99: 16, 100: 16, 102: 15, 105: 14, 106: 13, 111: 12, 115: 10, 109: 10, 103: 10, 120: 10, 104: 9, 110: 9, 123: 8, 118: 8, 107: 8, 112: 8, 113: 8, 114: 7, 117: 7, 124: 6, 116: 6, 137: 5, 132: 5, 122: 5, 128: 5, 138: 4, 130: 4, 126: 4, 121: 4, 133: 4, 125: 4, 147: 4, 162: 3, 139: 3, 153: 3, 135: 3, 140: 3, 119: 3, 141: 3, 127: 3, 154: 2, 170: 2, 160: 2, 164: 2, 177: 2, 136: 2, 165: 2, 129: 2, 134: 2, 148: 2, 152: 2, 248: 1, 145: 1, 131: 1, 146: 1, 285: 1, 143: 1, 301: 1, 185: 1, 224: 1, 195: 1, 157: 1, 158: 1, 166: 1, 193: 1, 149: 1, 209: 1}

  [cop]
    dtype      : int64
    sample val : np.int64(2)
    nulls      : 0
    n_unique   : 4
    counts     : {0: 53591, 1: 47826, 2: 42442, 3: 38963}

  [choice_type]
    dtype      : object
    sample val : 'single'
    nulls      : 0
    n_unique   : 2
    counts     : {'single': 120765, 'multi': 62057}
    len dist   : {6: 120765, 5: 62057}

  [exp]
    dtype      : object
    sample val : 'Chronic urethral obstruction because of urinary calculi, prostatic hyperophy, tumors, normal pregnancy, tumors, uterine
    nulls      : 21953
    n_unique   : 156640

  [subject_name]
    dtype      : object
    sample val : 'Anatomy'
    nulls      : 0
    n_unique   : 21
    len dist   : {12: 36353, 7: 34467, 10: 21309, 9: 19279, 8: 17887, 28: 11882, 24: 10013, 6: 8938, 13: 6932, 17: 5900, 3: 4919, 11: 3172, 4: 1771}

  [topic_name]
    dtype      : object
    sample val : 'Urinary tract'
    nulls      : 95613
    n_unique   : 2388

  ── First 3 examples ──────────────────────────────────────
  ── Example 0 ────────────────────────────────────────
  id                  : 'e9ad821a-c438-4965-9f77-760819dfa155'
  question            : 'Chronic urethral obstruction due to benign prismatic hyperplasia can lead to the following change in kidney parenchyma'
  opa                 : 'Hyperplasia'
  opb                 : 'Hyperophy'
  opc                 : 'Atrophy'
  opd                 : 'Dyplasia'
  cop                 : 2
  choice_type         : 'single'
  exp                 : 'Chronic urethral obstruction because of urinary calculi, prostatic hyperophy, tumors, normal pregnancy, tumors, uterine prolapse or functional disorders cause hydronephrosis which by definition is used to describe dilatation of renal pelvis and calc
  subject_name        : 'Anatomy'
  topic_name          : 'Urinary tract'

  ── Example 1 ────────────────────────────────────────
  id                  : 'e3d3c4e1-4fb2-45e7-9f88-247cc8f373b3'
  question            : 'Which vitamin is supplied from only animal source:'
  opa                 : 'Vitamin C'
  opb                 : 'Vitamin B7'
  opc                 : 'Vitamin B12'
  opd                 : 'Vitamin D'
  cop                 : 2
  choice_type         : 'single'
  exp                 : "Ans. (c) Vitamin B12 Ref: Harrison's 19th ed. P 640* Vitamin B12 (Cobalamin) is synthesized solely by microorganisms.* In humans, the only source for humans is food of animal origin, e.g., meat, fish, and dairy products.* Vegetables, fruits, and oth
  subject_name        : 'Biochemistry'
  topic_name          : 'Vitamins and Minerals'

  ── Example 2 ────────────────────────────────────────
  id                  : '5c38bea6-787a-44a9-b2df-88f4218ab914'
  question            : 'All of the following are surgical options for morbid obesity except -'
  opa                 : 'Adjustable gastric banding'
  opb                 : 'Biliopancreatic diversion'
  opc                 : 'Duodenal Switch'
  opd                 : 'Roux en Y Duodenal By pass'
  cop                 : 3
  choice_type         : 'multi'
  exp                 : "Ans. is 'd' i.e., Roux en Y Duodenal Bypass Bariatric surgical procedures include:a. Vertical banded gastroplastyb. Adjustable gastric bandingc. Roux-en Y gastric bypass (Not - Roux-en Y Duodenal Bypass)d. Biliopancreatic diversione. Duodenal switch
  subject_name        : 'Surgery'
  topic_name          : 'Surgical Treatment Obesity'

  Returning sampled DataFrame — 250 rows (seed=42)

## CommonSenseQA

In [ ]:
df_commonsenseqa = explore("tau/commonsense_qa", name=None, split="train", n=3, sample=250)

============================================================
  tau/commonsense_qa  |  config=None
============================================================

README.md: 0.00B [00:00, ?B/s]

  Available splits : ['train', 'validation', 'test']
  Loading split    : 'train' ...

data/train-00000-of-00001.parquet:   0%|          | 0.00/1.25M [00:00<?, ?B/s]

data/validation-00000-of-00001.parquet:   0%|          | 0.00/160k [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/151k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/9741 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/1221 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1140 [00:00<?, ? examples/s]

  ── Full dataset stats ──────────────────────────────────────
  Total rows  : 9741
  Columns     : ['id', 'question', 'question_concept', 'choices', 'answerKey']

  [id]
    dtype      : object
    sample val : '075e483d21c29a511267ef62bedc0461'
    nulls      : 0
    n_unique   : 9741
    len dist   : {32: 9618, 34: 123}

  [question]
    dtype      : object
    sample val : 'The sanctions against the school were a punishing blow, and they seemed to what the efforts the school had made to chan
    nulls      : 0
    n_unique   : 9741
    len dist   : {55: 185, 49: 179, 50: 178, 53: 172, 57: 165, 45: 162, 47: 162, 52: 158, 56: 156, 51: 156, 44: 155, 46: 155, 61: 151, 67: 149, 54: 146, 39: 145, 62: 145, 60: 143, 43: 143, 65: 142, 48: 142, 41: 141, 63: 140, 58: 139, 59: 139, 42: 138, 66: 137, 73: 137, 72: 136, 40: 134, 68: 128, 77: 128, 69: 127, 64: 127, 74: 124, 38: 121, 70: 119, 37: 118, 76: 116, 71: 114, 81: 110, 80: 109, 83: 108, 85: 103, 75: 103, 82: 100, 78: 98, 88: 98, 84: 98, 35: 94, 36: 90, 86: 90, 34: 89, 79: 84, 91: 84, 87: 83, 90: 82, 33: 76, 89: 76, 32: 69, 93: 69, 96: 68, 94: 68, 92: 65, 95: 60, 97: 55, 104: 53, 99: 53, 101: 51, 31: 51, 102: 50, 106: 48, 100: 48, 30: 48, 28: 47, 110: 44, 98: 43, 112: 43, 105: 41, 107: 41, 103: 40, 111: 39, 29: 39, 108: 35, 27: 34, 117: 33, 119: 33, 26: 31, 123: 30, 124: 30, 115: 30, 109: 29, 25: 28, 113: 26, 114: 25, 122: 25, 116: 25, 125: 21, 118: 20, 120: 19, 130: 19, 121: 18, 133: 17, 134: 15, 24: 15, 129: 14, 139: 14, 23: 14, 127: 14, 126: 14, 128: 13, 131: 13, 136: 13, 141: 11, 149: 11, 145: 11, 152: 10, 161: 10, 144: 9, 150: 9, 135: 9, 163: 8, 143: 8, 132: 8, 22: 7, 157: 7, 140: 7, 160: 7, 138: 7, 20: 7, 153: 7, 148: 7, 137: 7, 158: 6, 146: 6, 173: 6, 142: 6, 154: 5, 147: 5, 21: 4, 164: 4, 202: 4, 168: 4, 169: 4, 155: 4, 194: 3, 162: 3, 178: 3, 198: 3, 189: 3, 216: 3, 184: 3, 170: 3, 159: 3, 179: 3, 156: 3, 209: 2, 175: 2, 19: 2, 176: 2, 185: 2, 182: 2, 151: 2, 166: 2, 174: 2, 165: 2, 219: 2, 204: 2, 17: 1, 201: 1, 188: 1, 183: 1, 244: 1, 203: 1, 200: 1, 215: 1, 192: 1, 222: 1, 248: 1, 242: 1, 206: 1, 228: 1, 191: 1, 278: 1, 205: 1, 15: 1, 167: 1, 273: 1, 246: 1, 181: 1, 186: 1, 376: 1, 252: 1, 210: 1, 177: 1, 238: 1, 172: 1, 207: 1, 180: 1, 270: 1}

  [question_concept]
    dtype      : object
    sample val : 'punishing'
    nulls      : 0
    n_unique   : 2151
    len dist   : {6: 1392, 5: 1322, 4: 1057, 7: 998, 8: 783, 9: 655, 10: 573, 11: 459, 3: 457, 13: 400, 12: 373, 14: 274, 15: 231, 16: 208, 17: 179, 18: 98, 19: 96, 20: 54, 21: 35, 25: 30, 22: 20, 24: 19, 23: 17, 26: 7, 28: 4}

  [choices]
    dtype      : object
    sample val : {'label': array(['A', 'B', 'C', 'D', 'E'], dtype=object), 'text': array(['ignore', 'enforce', 'authoritarian', 'yell at'
    nulls      : 0
    n_unique   : unhashable (list/array column)
    len dist   : {2: 9741}

  [answerKey]
    dtype      : object
    sample val : 'A'
    nulls      : 0
    n_unique   : 5
    counts     : {'D': 1985, 'B': 1973, 'C': 1946, 'E': 1928, 'A': 1909}
    len dist   : {1: 9741}

  ── First 3 examples ──────────────────────────────────────
  ── Example 0 ────────────────────────────────────────
  id                  : '075e483d21c29a511267ef62bedc0461'
  question            : 'The sanctions against the school were a punishing blow, and they seemed to what the efforts the school had made to change?'
  question_concept    : 'punishing'
  choices             : {'label': ['A', 'B', 'C', 'D', 'E'], 'text': ['ignore', 'enforce', 'authoritarian', 'yell at', 'avoid']}
  answerKey           : 'A'

  ── Example 1 ────────────────────────────────────────
  id                  : '61fe6e879ff18686d7552425a36344c8'
  question            : 'Sammy wanted to go to where the people were.  Where might he go?'
  question_concept    : 'people'
  choices             : {'label': ['A', 'B', 'C', 'D', 'E'], 'text': ['race track', 'populated areas', 'the desert', 'apartment', 'roadblock']}
  answerKey           : 'B'

  ── Example 2 ────────────────────────────────────────
  id                  : '4c1cb0e95b99f72d55c068ba0255c54d'
  question            : 'To locate a choker not located in a jewelry box or boutique where would you go?'
  question_concept    : 'choker'
  choices             : {'label': ['A', 'B', 'C', 'D', 'E'], 'text': ['jewelry store', 'neck', 'jewlery box', 'jewelry box', 'boutique']}
  answerKey           : 'A'

  Returning sampled DataFrame — 250 rows (seed=42)

In [ ]:
ds_commonsense = load_dataset("tau/commonsense_qa", split="train")
df_commonsense_full = ds_commonsense.to_pandas()

print("Total rows:", len(df_commonsense_full))
print()
print("Answer key distribution:")
print(df_commonsense_full["answerKey"].value_counts())
print()
print("Number of options per question:")
df_commonsense_full["choices"].apply(lambda x: len(x["text"])).value_counts()

Total rows: 9741

Answer key distribution:
answerKey
D    1985
B    1973
C    1946
E    1928
A    1909
Name: count, dtype: int64

Number of options per question:

choices
5    9741
Name: count, dtype: int64

## SciQA

In [ ]:
df_sciq = explore("allenai/sciq", name=None, split="train", n=3, sample=250)

============================================================
  allenai/sciq  |  config=None
============================================================

README.md: 0.00B [00:00, ?B/s]

  Available splits : ['train', 'validation', 'test']
  Loading split    : 'train' ...

data/train-00000-of-00001.parquet:   0%|          | 0.00/3.99M [00:00<?, ?B/s]

data/validation-00000-of-00001.parquet:   0%|          | 0.00/339k [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/343k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/11679 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/1000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1000 [00:00<?, ? examples/s]

  ── Full dataset stats ──────────────────────────────────────
  Total rows  : 11679
  Columns     : ['question', 'distractor3', 'distractor1', 'distractor2', 'correct_answer', 'support']

  [question]
    dtype      : object
    sample val : 'What type of organism is commonly used in preparation of foods such as cheese and yogurt?'
    nulls      : 0
    n_unique   : 11609
    len dist   : {61: 213, 64: 199, 51: 192, 69: 189, 59: 185, 58: 182, 57: 182, 52: 182, 56: 181, 55: 180, 50: 179, 54: 178, 66: 177, 49: 175, 62: 175, 67: 172, 71: 172, 60: 170, 68: 170, 53: 170, 65: 167, 73: 165, 72: 162, 63: 162, 48: 162, 77: 158, 70: 156, 76: 154, 44: 151, 74: 148, 83: 148, 46: 147, 82: 147, 45: 147, 81: 144, 47: 144, 79: 143, 75: 142, 42: 138, 43: 137, 85: 135, 80: 134, 78: 133, 87: 130, 90: 129, 84: 128, 86: 124, 89: 119, 91: 118, 88: 111, 92: 109, 95: 107, 41: 106, 39: 102, 38: 98, 40: 96, 98: 95, 93: 92, 99: 91, 102: 89, 97: 89, 94: 88, 104: 87, 36: 79, 96: 76, 100: 75, 106: 73, 101: 73, 37: 69, 105: 69, 35: 67, 107: 64, 103: 59, 113: 59, 109: 58, 114: 57, 116: 54, 110: 53, 34: 51, 108: 51, 111: 42, 119: 41, 33: 40, 120: 39, 121: 39, 125: 38, 123: 38, 112: 38, 117: 38, 115: 37, 32: 36, 124: 35, 118: 33, 31: 32, 30: 32, 131: 29, 136: 29, 29: 28, 122: 27, 127: 24, 130: 24, 129: 23, 126: 22, 128: 22, 151: 21, 137: 20, 143: 18, 138: 18, 28: 17, 132: 17, 134: 17, 145: 16, 133: 16, 147: 16, 139: 15, 27: 14, 150: 14, 144: 13, 154: 12, 146: 12, 26: 12, 142: 12, 140: 12, 148: 11, 153: 11, 164: 10, 135: 10, 155: 10, 25: 10, 149: 10, 156: 9, 159: 9, 23: 8, 161: 8, 24: 8, 152: 8, 141: 8, 158: 7, 178: 7, 22: 7, 170: 6, 183: 6, 179: 6, 163: 6, 171: 6, 176: 5, 177: 5, 203: 5, 169: 5, 157: 5, 166: 4, 212: 4, 167: 4, 160: 4, 165: 4, 21: 4, 172: 4, 181: 4, 173: 4, 202: 3, 174: 3, 168: 3, 190: 3, 189: 3, 175: 3, 235: 3, 200: 2, 211: 2, 205: 2, 197: 2, 228: 2, 20: 2, 289: 2, 162: 2, 210: 2, 185: 2, 193: 2, 198: 2, 182: 2, 187: 2, 291: 2, 19: 2, 275: 2, 191: 2, 180: 2, 199: 2, 276: 2, 194: 2, 196: 2, 230: 2, 192: 2, 236: 1, 340: 1, 298: 1, 280: 1, 247: 1, 208: 1, 227: 1, 243: 1, 232: 1, 233: 1, 221: 1, 215: 1, 313: 1, 14: 1, 184: 1, 231: 1, 240: 1, 16: 1, 207: 1, 248: 1, 269: 1, 295: 1, 201: 1, 250: 1, 209: 1, 206: 1, 244: 1, 261: 1, 358: 1, 399: 1, 217: 1, 296: 1, 264: 1, 369: 1, 348: 1, 223: 1, 253: 1, 279: 1, 257: 1, 239: 1, 216: 1, 309: 1, 17: 1, 226: 1, 388: 1, 186: 1}

  [distractor3]
    dtype      : object
    sample val : 'viruses'
    nulls      : 0
    n_unique   : 6960
    len dist   : {7: 1174, 8: 1137, 9: 1131, 6: 971, 5: 938, 10: 793, 11: 773, 12: 583, 4: 538, 13: 516, 14: 484, 15: 454, 16: 370, 17: 321, 18: 286, 3: 205, 19: 189, 20: 176, 21: 145, 22: 97, 23: 75, 24: 68, 25: 36, 2: 34, 26: 25, 27: 25, 1: 25, 29: 20, 28: 18, 32: 13, 30: 10, 34: 8, 37: 6, 38: 5, 31: 5, 36: 4, 35: 4, 33: 3, 41: 2, 51: 2, 43: 2, 57: 1, 39: 1, 59: 1, 52: 1, 40: 1, 55: 1, 63: 1, 45: 1}

  [distractor1]
    dtype      : object
    sample val : 'protozoa'
    nulls      : 0
    n_unique   : 6991
    len dist   : {8: 1150, 7: 1128, 9: 1098, 6: 1041, 5: 869, 10: 838, 11: 775, 12: 561, 4: 547, 13: 538, 14: 493, 15: 437, 17: 334, 16: 317, 18: 291, 19: 229, 3: 219, 20: 175, 21: 156, 22: 106, 23: 71, 24: 65, 25: 36, 2: 33, 1: 27, 27: 25, 26: 25, 28: 17, 31: 10, 29: 10, 32: 10, 34: 9, 38: 7, 30: 6, 35: 4, 33: 3, 37: 3, 44: 2, 43: 2, 39: 2, 56: 1, 57: 1, 46: 1, 54: 1, 40: 1, 48: 1, 42: 1, 45: 1, 41: 1, 36: 1}

  [distractor2]
    dtype      : object
    sample val : 'gymnosperms'
    nulls      : 0
    n_unique   : 6900
    len dist   : {7: 1154, 9: 1136, 8: 1114, 6: 1018, 5: 926, 10: 809, 11: 790, 12: 588, 4: 527, 13: 505, 14: 492, 15: 475, 16: 339, 17: 338, 18: 271, 19: 207, 20: 198, 3: 190, 21: 140, 22: 94, 23: 72, 24: 58, 2: 34, 25: 33, 27: 27, 26: 26, 1: 23, 30: 14, 29: 11, 31: 9, 28: 9, 35: 7, 33: 7, 32: 7, 34: 6, 36: 5, 37: 3, 50: 3, 39: 3, 44: 2, 53: 2, 38: 2, 41: 1, 43: 1, 45: 1, 46: 1, 62: 1}

  [correct_answer]
    dtype      : object
    sample val : 'mesophilic organisms'
    nulls      : 0
    n_unique   : 5896
    len dist   : {7: 1046, 8: 1043, 9: 948, 6: 934, 11: 920, 5: 845, 10: 801, 14: 674, 12: 648, 13: 533, 4: 435, 15: 432, 16: 370, 17: 366, 18: 247, 19: 226, 20: 213, 3: 194, 21: 154, 22: 136, 24: 85, 23: 69, 25: 63, 26: 53, 2: 44, 27: 29, 28: 27, 1: 25, 30: 19, 29: 14, 32: 11, 34: 10, 33: 9, 31: 9, 35: 6, 39: 6, 37: 5, 44: 5, 40: 5, 36: 4, 38: 3, 51: 2, 41: 2, 54: 2, 43: 1, 45: 1, 53: 1, 49: 1, 50: 1, 55: 1, 67: 1}

  [support]
    dtype      : object
    sample val : 'Mesophiles grow best in moderate temperature, typically between 25°C and 40°C (77°F and 104°F). Mesophiles are often fo
    nulls      : 0
    n_unique   : 10474
    len dist   : {0: 1198, 76: 38, 80: 36, 68: 36, 73: 35, 72: 34, 86: 32, 65: 30, 88: 29, 59: 29, 223: 29, 94: 29, 69: 28, 71: 28, 64: 28, 252: 27, 79: 27, 248: 27, 152: 27, 173: 27, 364: 26, 231: 26, 163: 26, 193: 26, 82: 26, 224: 26, 190: 26, 84: 26, 75: 25, 66: 25, 355: 25, 70: 25, 89: 25, 85: 25, 206: 24, 250: 24, 92: 23, 109: 23, 101: 23, 58: 23, 50: 23, 218: 23, 343: 23, 95: 23, 275: 23, 87: 23, 228: 23, 268: 23, 284: 23, 116: 23, 220: 23, 103: 23, 207: 23, 323: 23, 342: 23, 191: 23, 194: 23, 159: 22, 98: 22, 153: 22, 83: 22, 235: 22, 126: 22, 266: 22, 108: 22, 99: 22, 107: 22, 264: 22, 283: 22, 141: 22, 211: 22, 239: 22, 157: 22, 97: 22, 122: 22, 263: 21, 221: 21, 144: 21, 254: 21, 253: 21, 77: 21, 200: 21, 138: 21, 232: 21, 242: 21, 93: 21, 278: 21, 201: 20, 143: 20, 341: 20, 304: 20, 158: 20, 100: 20, 282: 20, 57: 20, 188: 20, 91: 20, 309: 20, 56: 20, 396: 20, 237: 20, 60: 20, 317: 20, 114: 20, 133: 20, 192: 20, 53: 20, 286: 19, 183: 19, 229: 19, 54: 19, 315: 19, 356: 19, 314: 19, 281: 19, 305: 19, 241: 19, 175: 19, 104: 19, 67: 19, 164: 19, 233: 19, 313: 19, 184: 19, 380: 19, 169: 19, 90: 19, 386: 19, 166: 18, 354: 18, 269: 18, 215: 18, 161: 18, 123: 18, 134: 18, 385: 18, 119: 18, 240: 18, 291: 18, 112: 18, 182: 18, 330: 18, 238: 18, 198: 18, 384: 18, 81: 18, 407: 18, 149: 18, 137: 18, 312: 18, 262: 18, 185: 18, 423: 18, 280: 18, 150: 18, 316: 18, 349: 18, 310: 18, 145: 18, 146: 18, 230: 18, 276: 18, 260: 17, 391: 17, 328: 17, 167: 17, 470: 17, 181: 17, 63: 17, 379: 17, 55: 17, 259: 17, 297: 17, 296: 17, 234: 17, 406: 17, 332: 17, 367: 17, 178: 17, 127: 17, 205: 17, 448: 17, 214: 17, 267: 17, 96: 17, 401: 17, 324: 17, 222: 17, 363: 17, 203: 17, 428: 17, 274: 17, 392: 17, 48: 17, 102: 17, 227: 17, 374: 17, 257: 17, 340: 17, 411: 17, 270: 16, 350: 16, 388: 16, 49: 16, 245: 16, 177: 16, 180: 16, 246: 16, 560: 16, 156: 16, 209: 16, 509: 16, 256: 16, 424: 16, 131: 16, 251: 16, 413: 16, 376: 16, 247: 16, 139: 16, 416: 16, 117: 16, 331: 16, 321: 16, 217: 16, 555: 16, 151: 16, 74: 16, 348: 16, 271: 16, 272: 16, 132: 16, 155: 16, 147: 16, 195: 16, 172: 16, 61: 16, 408: 16, 478: 16, 277: 16, 294: 16, 492: 16, 453: 16, 197: 16, 160: 15, 417: 15, 136: 15, 395: 15, 346: 15, 360: 15, 52: 15, 329: 15, 371: 15, 404: 15, 320: 15, 212: 15, 377: 15, 273: 15, 389: 15, 327: 15, 213: 15, 351: 15, 292: 15, 381: 15, 244: 15, 311: 15, 390: 15, 154: 15, 358: 15, 199: 15, 106: 15, 236: 15, 300: 15, 189: 15, 336: 15, 318: 15, 499: 15, 301: 15, 295: 14, 115: 14, 333: 14, 204: 14, 176: 14, 187: 14, 255: 14, 265: 14, 434: 14, 288: 14, 168: 14, 148: 14, 110: 14, 426: 14, 249: 14, 502: 14, 338: 14, 402: 14, 474: 14, 382: 14, 436: 13, 369: 13, 468: 13, 443: 13, 285: 13, 430: 13, 170: 13, 564: 13, 62: 13, 462: 13, 460: 13, 446: 13, 210: 13, 366: 13, 216: 13, 431: 13, 325: 13, 51: 13, 393: 13, 422: 13, 353: 13, 225: 13, 347: 13, 186: 13, 299: 13, 394: 13, 303: 13, 375: 13, 142: 13, 279: 13, 322: 13, 111: 13, 243: 13, 290: 13, 405: 13, 361: 13, 410: 13, 518: 13, 609: 13, 135: 12, 352: 12, 202: 12, 298: 12, 525: 12, 373: 12, 520: 12, 486: 12, 121: 12, 130: 12, 174: 12, 171: 12, 219: 12, 383: 12, 400: 12, 370: 12, 140: 12, 501: 12, 472: 12, 293: 12, 496: 12, 527: 12, 459: 12, 475: 12, 287: 12, 466: 12, 372: 12, 469: 12, 357: 12, 365: 12, 335: 12, 162: 12, 113: 12, 615: 12, 78: 12, 129: 12, 420: 12, 541: 12, 196: 11, 491: 11, 454: 11, 208: 11, 179: 11, 378: 11, 473: 11, 498: 11, 337: 11, 425: 11, 661: 11, 403: 11, 432: 11, 226: 11, 165: 11, 319: 11, 128: 11, 523: 11, 592: 11, 307: 11, 47: 11, 414: 11, 577: 11, 482: 11, 359: 11, 397: 11, 258: 11, 120: 11, 387: 11, 344: 11, 418: 11, 289: 11, 306: 11, 507: 10, 530: 10, 535: 10, 261: 10, 571: 10, 105: 10, 575: 10, 579: 10, 464: 10, 605: 10, 561: 10, 528: 10, 612: 10, 495: 10, 458: 10, 345: 10, 540: 10, 497: 10, 484: 10, 326: 10, 534: 10, 440: 10, 441: 10, 442: 10, 538: 10, 562: 10, 437: 10, 398: 10, 573: 10, 544: 10, 536: 9, 646: 9, 522: 9, 506: 9, 302: 9, 118: 9, 537: 9, 339: 9, 449: 9, 483: 9, 433: 9, 558: 9, 514: 9, 549: 9, 531: 9, 444: 9, 706: 9, 568: 9, 524: 9, 45: 9, 513: 9, 455: 9, 485: 9, 471: 9, 649: 9, 46: 9, 125: 9, 368: 9, 124: 9, 591: 9, 508: 9, 587: 9, 465: 9, 626: 9, 435: 9, 481: 9, 548: 8, 505: 8, 494: 8, 461: 8, 480: 8, 631: 8, 419: 8, 421: 8, 547: 8, 362: 8, 552: 8, 598: 8, 668: 8, 409: 8, 308: 8, 334: 8, 698: 8, 399: 8, 487: 8, 447: 8, 745: 8, 590: 8, 539: 8, 636: 8, 567: 8, 557: 8, 607: 8, 415: 8, 450: 8, 542: 8, 517: 8, 504: 8, 642: 8, 477: 8, 516: 8, 427: 8, 681: 7, 439: 7, 578: 7, 659: 7, 545: 7, 515: 7, 654: 7, 647: 7, 737: 7, 628: 7, 687: 7, 526: 7, 488: 7, 489: 7, 559: 7, 777: 7, 619: 7, 611: 7, 543: 7, 452: 7, 778: 7, 565: 7, 572: 7, 645: 7, 510: 7, 576: 7, 445: 7, 776: 7, 596: 7, 511: 7, 570: 7, 613: 7, 942: 7, 608: 7, 694: 7, 641: 7, 519: 7, 584: 7, 456: 7, 563: 7, 712: 7, 412: 7, 490: 7, 553: 6, 828: 6, 476: 6, 648: 6, 963: 6, 556: 6, 660: 6, 512: 6, 627: 6, 675: 6, 621: 6, 580: 6, 614: 6, 932: 6, 503: 6, 551: 6, 574: 6, 670: 6, 643: 6, 620: 6, 657: 6, 688: 6, 650: 6, 735: 6, 585: 6, 438: 6, 758: 6, 677: 6, 813: 6, 493: 6, 581: 6, 982: 6, 606: 6, 639: 6, 479: 6, 603: 6, 618: 6, 610: 6, 769: 6, 600: 5, 685: 5, 1081: 5, 858: 5, 834: 5, 747: 5, 583: 5, 901: 5, 683: 5, 597: 5, 857: 5, 888: 5, 902: 5, 44: 5, 604: 5, 791: 5, 708: 5, 39: 5, 42: 5, 622: 5, 802: 5, 701: 5, 736: 5, 754: 5, 664: 5, 693: 5, 593: 5, 739: 5, 820: 5, 601: 5, 916: 5, 40: 5, 41: 5, 672: 5, 451: 5, 566: 5, 971: 5, 457: 5, 529: 5, 1036: 5, 546: 5, 674: 5, 740: 5, 637: 5, 1388: 5, 623: 5, 1342: 4, 829: 4, 1123: 4, 1044: 4, 1010: 4, 1299: 4, 900: 4, 956: 4, 1657: 4, 1796: 4, 1211: 4, 862: 4, 929: 4, 1468: 4, 700: 4, 833: 4, 569: 4, 692: 4, 767: 4, 859: 4, 760: 4, 651: 4, 884: 4, 1506: 4, 554: 4, 521: 4, 588: 4, 1170: 4, 1060: 4, 1073: 4, 667: 4, 1005: 4, 697: 4, 837: 4, 855: 4, 730: 4, 550: 4, 678: 4, 599: 4, 748: 4, 1206: 4, 860: 4, 819: 4, 43: 4, 1018: 4, 1168: 4, 1290: 4, 463: 4, 1292: 4, 904: 4, 633: 4, 838: 4, 892: 4, 709: 4, 878: 4, 586: 4, 429: 4, 669: 4, 734: 4, 799: 4, 750: 4, 759: 4, 1139: 4, 966: 4, 699: 4, 686: 4, 1077: 4, 704: 4, 869: 4, 898: 4, 723: 4, 533: 4, 616: 4, 640: 4, 719: 4, 1240: 4, 703: 4, 717: 4, 679: 4, 830: 4, 994: 4, 656: 4, 632: 4, 1006: 4, 467: 4, 786: 3, 882: 3, 1049: 3, 872: 3, 854: 3, 1368: 3, 880: 3, 789: 3, 1028: 3, 617: 3, 1307: 3, 1136: 3, 1789: 3, 836: 3, 918: 3, 877: 3, 1178: 3, 751: 3, 812: 3, 824: 3, 1145: 3, 783: 3, 770: 3, 893: 3, 722: 3, 800: 3, 790: 3, 1235: 3, 1003: 3, 845: 3, 930: 3, 973: 3, 1537: 3, 808: 3, 816: 3, 665: 3, 1057: 3, 635: 3, 1125: 3, 765: 3, 953: 3, 1353: 3, 594: 3, 1101: 3, 897: 3, 991: 3, 658: 3, 1358: 3, 630: 3, 1747: 3, 1306: 3, 1322: 3, 990: 3, 689: 3, 718: 3, 684: 3, 761: 3, 629: 3, 764: 3, 844: 3, 1324: 3, 653: 3, 1835: 3, 1162: 3, 727: 3, 713: 3, 894: 3, 1119: 3, 1042: 3, 1811: 3, 766: 3, 1037: 3, 912: 3, 1409: 3, 1369: 3, 875: 3, 853: 3, 716: 3, 1021: 3, 741: 3, 638: 3, 696: 3, 1017: 3, 879: 3, 1281: 3, 726: 3, 752: 3, 842: 3, 707: 3, 1928: 3, 1205: 3, 976: 3, 889: 3, 1642: 3, 742: 3, 876: 3, 1647: 3, 1141: 3, 1083: 3, 910: 3, 919: 3, 1357: 3, 655: 3, 780: 3, 1130: 3, 744: 3, 711: 3, 814: 3, 825: 3, 680: 3, 1335: 3, 743: 3, 772: 3, 1050: 3, 1064: 3, 1293: 3, 866: 3, 856: 3, 848: 3, 955: 3, 1336: 3, 1112: 3, 861: 3, 1189: 3, 1180: 3, 774: 3, 1518: 3, 1341: 3, 1058: 3, 960: 3, 796: 3, 1682: 3, 1272: 3, 691: 2, 1458: 2, 1936: 2, 1549: 2, 896: 2, 1137: 2, 1208: 2, 1453: 2, 1147: 2, 849: 2, 997: 2, 1498: 2, 1172: 2, 908: 2, 788: 2, 1052: 2, 1542: 2, 1743: 2, 827: 2, 1411: 2, 1012: 2, 1289: 2, 798: 2, 1347: 2, 852: 2, 1157: 2, 1510: 2, 931: 2, 1849: 2, 1104: 2, 792: 2, 1282: 2, 989: 2, 914: 2, 1519: 2, 909: 2, 1513: 2, 1673: 2, 1395: 2, 1389: 2, 1509: 2, 1181: 2, 1569: 2, 1140: 2, 851: 2, 1392: 2, 1088: 2, 1072: 2, 1804: 2, 1011: 2, 1380: 2, 1026: 2, 1689: 2, 1775: 2, 883: 2, 1271: 2, 1253: 2, 1746: 2, 1891: 2, 1561: 2, 935: 2, 1729: 2, 2628: 2, 2393: 2, 940: 2, 1132: 2, 1020: 2, 1602: 2, 1038: 2, 1360: 2, 1055: 2, 1107: 2, 822: 2, 724: 2, 775: 2, 1574: 2, 818: 2, 1214: 2, 839: 2, 1932: 2, 1179: 2, 781: 2, 738: 2, 873: 2, 1019: 2, 1482: 2, 1418: 2, 663: 2, 1606: 2, 1068: 2, 582: 2, 1592: 2, 1815: 2, 1004: 2, 589: 2, 1792: 2, 785: 2, 532: 2, 865: 2, 1041: 2, 863: 2, 1517: 2, 922: 2, 895: 2, 835: 2, 731: 2, 981: 2, 1653: 2, 1121: 2, 1533: 2, 1805: 2, 1230: 2, 1708: 2, 1365: 2, 710: 2, 846: 2, 1863: 2, 2222: 2, 784: 2, 725: 2, 1236: 2, 885: 2, 1065: 2, 634: 2, 1199: 2, 1128: 2, 595: 2, 500: 2, 695: 2, 1023: 2, 1308: 2, 1135: 2, 2256: 2, 1938: 2, 797: 2, 870: 2, 1985: 2, 2123: 2, 972: 2, 850: 2, 1161: 2, 890: 2, 1400: 2, 757: 2, 1328: 2, 794: 2, 1263: 2, 1413: 2, 899: 2, 1266: 2, 1447: 2, 927: 2, 992: 2, 984: 2, 2307: 2, 1089: 2, 1584: 2, 644: 2, 1233: 2, 676: 2, 1076: 2, 1535: 2, 762: 2, 957: 2, 950: 2, 921: 2, 1390: 2, 1439: 2, 803: 2, 1045: 2, 1330: 2, 1391: 2, 1594: 2, 1361: 2, 958: 2, 1989: 2, 1217: 2, 1547: 2, 1111: 2, 1219: 2, 1053: 2, 1309: 2, 1445: 2, 967: 2, 1934: 2, 1354: 2, 2461: 2, 1182: 2, 702: 2, 821: 2, 2120: 2, 1751: 2, 823: 2, 1596: 2, 1438: 2, 771: 2, 1857: 2, 1279: 2, 974: 2, 1198: 2, 928: 2, 1490: 2, 1676: 2, 1425: 2, 1079: 2, 867: 2, 732: 2, 2058: 2, 1363: 2, 1120: 2, 1436: 2, 995: 2, 1426: 2, 1352: 2, 1031: 2, 1127: 2, 1416: 2, 1318: 2, 1477: 2, 1265: 2, 804: 2, 793: 2, 1106: 2, 1720: 2, 671: 2, 1329: 2, 937: 2, 1452: 2, 934: 2, 1508: 2, 1094: 2, 1466: 2, 1750: 2, 787: 2, 1221: 2, 1446: 2, 1424: 2, 729: 2, 652: 2, 1171: 2, 779: 2, 1071: 2, 1612: 2, 1704: 2, 1069: 2, 1039: 1, 1229: 1, 1641: 1, 1404: 1, 868: 1, 2811: 1, 2095: 1, 1528: 1, 2300: 1, 1659: 1, 1349: 1, 1138: 1, 1169: 1, 1294: 1, 1525: 1, 1512: 1, 1096: 1, 1283: 1, 1486: 1, 1212: 1, 1153: 1, 1093: 1, 1711: 1, 941: 1, 1876: 1, 3227: 1, 1467: 1, 2198: 1, 2255: 1, 1735: 1, 1316: 1, 3206: 1, 1771: 1, 1114: 1, 2085: 1, 782: 1, 2809: 1, 2156: 1, 1080: 1, 1733: 1, 2081: 1, 1122: 1, 1370: 1, 2424: 1, 1220: 1, 1757: 1, 1987: 1, 2722: 1, 1578: 1, 1841: 1, 2019: 1, 1654: 1, 1087: 1, 3132: 1, 3084: 1, 1754: 1, 1758: 1, 1663: 1, 1850: 1, 977: 1, 2376: 1, 2320: 1, 1108: 1, 2469: 1, 2188: 1, 1492: 1, 1095: 1, 1301: 1, 1652: 1, 2247: 1, 1830: 1, 1531: 1, 1975: 1, 1259: 1, 1286: 1, 2068: 1, 1433: 1, 2456: 1, 1223: 1, 2104: 1, 2601: 1, 38: 1, 1820: 1, 2013: 1, 1288: 1, 1521: 1, 1276: 1, 1386: 1, 1227: 1, 2365: 1, 1188: 1, 2415: 1, 2028: 1, 2487: 1, 1056: 1, 2108: 1, 2670: 1, 1618: 1, 2574: 1, 2316: 1, 1971: 1, 1800: 1, 2411: 1, 2521: 1, 1683: 1, 1749: 1, 1988: 1, 1061: 1, 3197: 1, 1799: 1, 979: 1, 810: 1, 1869: 1, 2129: 1, 690: 1, 1319: 1, 2852: 1, 1534: 1, 3326: 1, 1251: 1, 2187: 1, 1285: 1, 1025: 1, 1559: 1, 1203: 1, 807: 1, 961: 1, 2020: 1, 1655: 1, 1234: 1, 1665: 1, 2145: 1, 1996: 1, 1845: 1, 2175: 1, 939: 1, 2149: 1, 1472: 1, 1030: 1, 983: 1, 1740: 1, 1110: 1, 806: 1, 1582: 1, 1767: 1, 933: 1, 1156: 1, 1029: 1, 1864: 1, 2489: 1, 1103: 1, 1964: 1, 1262: 1, 1488: 1, 1816: 1, 1465: 1, 980: 1, 1637: 1, 1274: 1, 1396: 1, 871: 1, 1698: 1, 1715: 1, 2725: 1, 1487: 1, 924: 1, 809: 1, 1712: 1, 2359: 1, 1560: 1, 1662: 1, 1691: 1, 749: 1, 1134: 1, 1630: 1, 2218: 1, 1317: 1, 1644: 1, 2180: 1, 1959: 1, 2505: 1, 1196: 1, 1102: 1, 1790: 1, 1091: 1, 1591: 1, 1131: 1, 1909: 1, 1931: 1, 1249: 1, 847: 1, 2184: 1, 2650: 1, 911: 1, 815: 1, 969: 1, 1385: 1, 1074: 1, 2097: 1, 1443: 1, 1277: 1, 1705: 1, 1173: 1, 1503: 1, 2331: 1, 2245: 1, 1033: 1, 2208: 1, 1670: 1, 1942: 1, 1397: 1, 2887: 1, 1480: 1, 1001: 1, 1399: 1, 2100: 1, 1150: 1, 1555: 1, 1242: 1, 2053: 1, 1432: 1, 887: 1, 728: 1, 1464: 1, 1888: 1, 773: 1, 1345: 1, 1501: 1, 1527: 1, 1999: 1, 1548: 1, 1218: 1, 917: 1, 1656: 1, 2264: 1, 1035: 1, 1828: 1, 952: 1, 1343: 1, 1545: 1, 1694: 1, 1786: 1, 1526: 1, 3405: 1, 2354: 1, 864: 1, 1723: 1, 1609: 1, 1546: 1, 1556: 1, 1829: 1, 2173: 1, 811: 1, 1000: 1, 2263: 1, 1032: 1, 3559: 1, 1455: 1, 2015: 1, 1348: 1, 1323: 1, 2428: 1, 1383: 1, 795: 1, 1709: 1, 2396: 1, 1635: 1, 1415: 1, 2087: 1, 756: 1, 1113: 1, 1724: 1, 2203: 1, 2231: 1, 2154: 1, 2898: 1, 1070: 1, 1595: 1, 1177: 1, 1965: 1, 2089: 1, 2299: 1, 1410: 1, 936: 1, 913: 1, 1797: 1, 1692: 1, 1497: 1, 715: 1, 1250: 1, 2651: 1, 2048: 1, 2220: 1, 2465: 1, 805: 1, 1315: 1, 2695: 1, 1164: 1, 1543: 1, 915: 1, 1762: 1, 1129: 1, 2147: 1, 841: 1, 1210: 1, 1702: 1, 1969: 1, 1222: 1, 1973: 1, 2682: 1, 1099: 1, 1456: 1, 1565: 1, 2017: 1, 1853: 1, 1303: 1, 662: 1, 37: 1, 1727: 1, 1009: 1, 1176: 1, 1795: 1, 1431: 1, 1115: 1, 1998: 1, 1819: 1, 2051: 1, 602: 1, 1706: 1, 2153: 1, 1098: 1, 1886: 1, 733: 1, 1974: 1, 2616: 1, 1175: 1, 2649: 1, 1753: 1, 1007: 1, 907: 1, 2292: 1, 2117: 1, 2953: 1, 1972: 1, 1479: 1, 1756: 1, 2237: 1, 1261: 1, 1516: 1, 1956: 1, 2663: 1, 1781: 1, 1154: 1, 1244: 1, 1625: 1, 1613: 1, 1008: 1, 948: 1, 1953: 1, 1744: 1, 1954: 1, 682: 1, 720: 1, 1163: 1, 1287: 1, 1677: 1, 2275: 1, 2432: 1, 1155: 1, 886: 1, 1090: 1, 2409: 1, 1275: 1, 1382: 1, 2137: 1, 1994: 1, 831: 1, 1245: 1, 2125: 1, 1868: 1, 1226: 1, 2346: 1, 1375: 1, 1814: 1, 1986: 1, 755: 1, 1872: 1, 1906: 1, 1620: 1, 1599: 1, 1801: 1, 1268: 1, 1798: 1, 763: 1, 906: 1, 832: 1, 1024: 1, 1507: 1, 2001: 1, 2794: 1, 1406: 1, 2241: 1, 2099: 1, 1184: 1, 2063: 1, 1899: 1, 1499: 1, 721: 1, 1530: 1, 2301: 1, 944: 1, 1459: 1, 999: 1, 891: 1, 2819: 1, 1713: 1, 1326: 1, 1339: 1, 1297: 1, 1563: 1, 926: 1, 2721: 1, 2336: 1, 1066: 1, 1463: 1, 1806: 1, 1405: 1, 2269: 1, 1738: 1, 946: 1, 1063: 1, 1126: 1, 993: 1, 1187: 1, 2532: 1, 2555: 1, 1785: 1, 1296: 1, 1257: 1, 1552: 1, 925: 1, 1930: 1, 1707: 1, 1879: 1, 1047: 1, 1924: 1, 2515: 1, 1421: 1, 1831: 1, 1298: 1, 1159: 1, 2080: 1, 31: 1, 1588: 1, 988: 1, 2614: 1, 1600: 1, 1779: 1, 2211: 1, 1013: 1, 2423: 1, 714: 1, 624: 1, 1158: 1, 2565: 1, 1950: 1, 1854: 1, 1462: 1, 1639: 1, 1420: 1, 1717: 1, 1870: 1, 2537: 1, 35: 1, 1254: 1, 1394: 1, 1977: 1, 1067: 1, 2239: 1, 1485: 1, 1554: 1, 2566: 1, 1193: 1, 1183: 1, 1866: 1, 1215: 1, 1149: 1, 2018: 1, 1441: 1, 1566: 1, 1822: 1, 2223: 1, 2360: 1, 1167: 1, 2310: 1, 1483: 1, 1968: 1, 1450: 1, 843: 1, 1311: 1, 2044: 1, 1590: 1, 2495: 1, 1340: 1, 1536: 1, 1496: 1, 1643: 1, 2226: 1, 968: 1, 1414: 1, 2062: 1, 1605: 1, 2166: 1, 975: 1, 1766: 1, 1611: 1, 1310: 1, 1915: 1, 1457: 1, 2782: 1, 1945: 1, 1444: 1, 1376: 1, 2121: 1, 1437: 1, 2329: 1, 1629: 1, 2126: 1, 1474: 1, 2103: 1, 1374: 1, 1825: 1, 1773: 1, 1961: 1, 1714: 1, 1813: 1, 1881: 1, 2850: 1, 801: 1, 2541: 1, 666: 1, 2155: 1, 1616: 1, 1684: 1, 1239: 1, 1371: 1, 1246: 1, 2462: 1, 2229: 1, 2091: 1, 673: 1, 1558: 1, 1661: 1, 1022: 1, 996: 1, 1675: 1, 1856: 1, 1359: 1, 1384: 1, 1225: 1, 3434: 1, 938: 1, 1269: 1, 2192: 1, 2084: 1, 2343: 1, 1579: 1, 1718: 1, 1195: 1, 1861: 1, 964: 1, 2700: 1, 1589: 1, 1540: 1, 1912: 1, 1327: 1, 1092: 1, 1152: 1, 1051: 1, 1273: 1, 1538: 1, 1732: 1, 1770: 1, 2002: 1, 3369: 1}

  ── First 3 examples ──────────────────────────────────────
  ── Example 0 ────────────────────────────────────────
  question            : 'What type of organism is commonly used in preparation of foods such as cheese and yogurt?'
  distractor3         : 'viruses'
  distractor1         : 'protozoa'
  distractor2         : 'gymnosperms'
  correct_answer      : 'mesophilic organisms'
  support             : 'Mesophiles grow best in moderate temperature, typically between 25°C and 40°C (77°F and 104°F). Mesophiles are often found living in or on the bodies of humans or other animals. The optimal growth temperature of many pathogenic mesophiles is 37°C (9
