# Dataset Exploration

In [ ]:
!pip install datasets -q

### Explorer Helper

In [ ]:
import pandas as pd
import random
import hashlib
from datasets import load_dataset, get_dataset_split_names

def explore(path, name=None, split="train", n=3, sample=500, seed=42):
    print(f"{'='*60}")
    print(f"  {path}  |  config={name}")
    print(f"{'='*60}")

    try:
        splits = get_dataset_split_names(path, name) if name else get_dataset_split_names(path)
        print(f"  Available splits : {splits}")
    except Exception as e:
        print(f"  Could not fetch split names: {e}")

    print(f"  Loading split    : '{split}' ...")
    try:
        ds = load_dataset(path, name, split=split) if name else load_dataset(path, split=split)
    except Exception as e:
        print(f"  ERROR loading: {e}")
        return None

    df_full = ds.to_pandas()
    print(f"\n  ── Full dataset stats {'─'*38}")
    print(f"  Total rows  : {len(df_full)}")
    print(f"  Columns     : {df_full.columns.tolist()}")
    print()

    for col in df_full.columns:
      print(f"  [{col}]")
      print(f"    dtype      : {df_full[col].dtype}")
      print(f"    sample val : {repr(df_full[col].iloc[0])[:120]}")
      print(f"    nulls      : {df_full[col].isna().sum()}")
      try:
          n_unique = df_full[col].nunique()
          print(f"    n_unique   : {n_unique}")
          if n_unique <= 20:
              print(f"    counts     : {df_full[col].value_counts().to_dict()}")
      except TypeError:
          print(f"    n_unique   : unhashable (list/array column)")
      try:
          lengths = df_full[col].apply(len)
          print(f"    len dist   : {lengths.value_counts().to_dict()}")
      except (TypeError, AttributeError):
          pass
      print()

    print(f"  ── First {n} examples {'─'*38}")
    for i in range(min(n, len(df_full))):
        print(f"  ── Example {i} {'─'*40}")
        for k, v in ds[i].items():
            print(f"  {k:20s}: {repr(v)[:500]}")
        print()

    random.seed(seed)
    if sample is None:
        df_sampled = df_full.reset_index(drop=True)
    else:
        valid_indices = []
        for idx in range(len(df_full)):
            q = str(df_full.iloc[idx].get("question", ""))[:200].strip().lower()
            fp = hashlib.md5(q.encode()).hexdigest()
            if fp not in existing_fps:
                valid_indices.append(idx)
        print(f"  After dedup: {len(valid_indices)} available (excluded {len(df_full) - len(valid_indices)})")
        indices = random.sample(valid_indices, min(sample, len(valid_indices)))
        df_sampled = df_full.iloc[indices].reset_index(drop=True)
    print(f"  Returning sampled DataFrame — {len(df_sampled)} rows (seed={seed})")
    return df_sampled

In [ ]:
import hashlib

old_df = pd.read_csv("RouterReflector Combined Dataset.csv")  # upload this first
existing_fps = set()
for _, row in old_df.iterrows():
    fp = hashlib.md5(str(row["question"])[:200].strip().lower().encode()).hexdigest()
    existing_fps.add(fp)
print(f"Loaded {len(existing_fps)} existing question fingerprints for dedup")

Loaded 1480 existing question fingerprints for dedup

## MMLU
Link: https://huggingface.co/datasets/cais/mmlu

In [ ]:
df_mmlu = explore("cais/mmlu", name="all", split="auxiliary_train", n=3, sample=500)

============================================================
  cais/mmlu  |  config=all
============================================================

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md: 0.00B [00:00, ?B/s]

dataset_infos.json: 0.00B [00:00, ?B/s]

  Available splits : ['test', 'validation', 'dev', 'auxiliary_train']
  Loading split    : 'auxiliary_train' ...

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

all/test-00000-of-00001.parquet:   0%|          | 0.00/3.50M [00:00<?, ?B/s]

all/validation-00000-of-00001.parquet:   0%|          | 0.00/408k [00:00<?, ?B/s]

all/dev-00000-of-00001.parquet:   0%|          | 0.00/76.5k [00:00<?, ?B/s]

all/auxiliary_train-00000-of-00001.parqu(…):   0%|          | 0.00/47.5M [00:00<?, ?B/s]

Generating test split:   0%|          | 0/14042 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/1531 [00:00<?, ? examples/s]

Generating dev split:   0%|          | 0/285 [00:00<?, ? examples/s]

Generating auxiliary_train split:   0%|          | 0/99842 [00:00<?, ? examples/s]

  ── Full dataset stats ──────────────────────────────────────
  Total rows  : 99842
  Columns     : ['question', 'subject', 'choices', 'answer']

  [question]
    dtype      : object
    sample val : "Davis decided to kill Adams. He set out for Adams's house. Before he got there he saw Brooks, who resembled Adams. Thin
    nulls      : 0
    n_unique   : 98487

In [ ]:
# Number of questions per option count
df_mmlu["choices"].apply(len).value_counts()

choices
4    500
Name: count, dtype: int64

## AQuA-RAT
Math dataset, substitute for MathQA

In [ ]:
# AQuA-RAT — algebra word problems, MCQ with 5 options, clean Parquet format
df_aqua = explore("aqua_rat", name="raw", split="train", n=3, sample=500)

============================================================
  aqua_rat  |  config=raw
============================================================

README.md: 0.00B [00:00, ?B/s]

  Available splits : ['train', 'test', 'validation']
  Loading split    : 'train' ...

raw/train-00000-of-00001.parquet:   0%|          | 0.00/25.4M [00:00<?, ?B/s]

raw/test-00000-of-00001.parquet:   0%|          | 0.00/74.0k [00:00<?, ?B/s]

raw/validation-00000-of-00001.parquet:   0%|          | 0.00/76.1k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/97467 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/254 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/254 [00:00<?, ? examples/s]

  ── Full dataset stats ──────────────────────────────────────
  Total rows  : 97467
  Columns     : ['question', 'options', 'rationale', 'correct']

  [question]
    dtype      : object
    sample val : "Two friends plan to walk along a 43-km trail, starting at opposite ends of the trail at the same time. If Friend P's ra
    nulls      : 0
    n_unique   : 80924
    len dist   : {122: 722, 172: 716, 120: 692, 102: 673, 111: 662, 104: 657, 100: 653, 124: 621, 134: 619, 113: 614, 103: 603, 123: 597, 153: 585, 154: 585, 114: 583, 126: 579, 164: 578, 87: 575, 162: 572, 112: 567, 144: 566, 107: 563, 125: 559, 127: 558, 141: 549, 101: 548, 118: 548, 158: 543, 121: 542, 129: 538, 96: 538, 163: 532, 117: 531, 147: 531, 145: 529, 165: 526, 99: 526, 178: 525, 131: 523, 157: 516, 146: 516, 88: 511, 173: 511, 139: 508, 108: 505, 128: 496, 135: 489, 168: 488, 137: 484, 167: 481, 174: 478, 93: 478, 156: 475, 138: 469, 115: 467, 110: 464, 142: 462, 130: 459, 143: 459, 136: 458, 191: 456, 75: 455, 119: 455, 74: 454, 140: 450, 177: 447, 150: 446, 195: 446, 176: 445, 197: 443, 91: 442, 133: 441, 98: 441, 161: 439, 148: 437, 94: 432, 86: 430, 159: 427, 151: 426, 160: 424, 179: 420, 73: 419, 187: 418, 175: 416, 109: 414, 132: 413, 89: 413, 170: 412, 116: 411, 84: 410, 105: 409, 152: 406, 155: 403, 92: 402, 80: 401, 78: 400, 169: 399, 166: 398, 192: 396, 97: 396, 82: 394, 218: 387, 90: 384, 95: 379, 149: 378, 85: 376, 180: 375, 81: 372, 83: 371, 77: 370, 188: 369, 186: 368, 184: 364, 198: 363, 106: 360, 181: 358, 71: 354, 196: 346, 183: 346, 49: 346, 194: 338, 76: 335, 48: 335, 182: 333, 72: 328, 69: 327, 193: 327, 79: 322, 205: 320, 50: 316, 65: 315, 199: 314, 185: 310, 209: 308, 45: 305, 171: 296, 70: 290, 200: 287, 211: 287, 201: 284, 56: 283, 189: 282, 216: 278, 204: 276, 60: 276, 68: 275, 214: 274, 207: 273, 190: 271, 227: 271, 54: 269, 43: 268, 203: 267, 66: 267, 219: 264, 63: 264, 46: 260, 242: 258, 62: 257, 224: 256, 53: 254, 64: 252, 67: 252, 61: 251, 208: 249, 206: 247, 47: 246, 55: 245, 51: 243, 220: 242, 258: 242, 223: 239, 59: 239, 212: 237, 237: 237, 215: 236, 228: 234, 231: 232, 217: 232, 235: 226, 44: 226, 249: 224, 250: 223, 210: 222, 225: 220, 57: 218, 244: 218, 40: 215, 221: 213, 246: 213, 213: 212, 232: 210, 251: 210, 243: 210, 222: 209, 229: 207, 39: 206, 202: 206, 52: 203, 230: 202, 259: 201, 236: 200, 240: 198, 245: 196, 248: 196, 247: 196, 233: 195, 241: 193, 234: 192, 239: 191, 35: 190, 269: 187, 42: 186, 58: 185, 252: 183, 254: 171, 37: 171, 238: 169, 33: 166, 278: 163, 226: 161, 25: 156, 266: 154, 260: 153, 263: 151, 296: 146, 36: 145, 274: 144, 289: 144, 29: 143, 286: 142, 255: 142, 288: 141, 262: 140, 41: 139, 265: 135, 298: 134, 264: 134, 267: 133, 292: 132, 257: 132, 32: 131, 27: 131, 285: 131, 291: 130, 26: 129, 253: 128, 31: 128, 276: 128, 290: 127, 256: 126, 304: 125, 319: 124, 272: 123, 28: 123, 23: 121, 34: 121, 271: 120, 299: 119, 268: 119, 261: 118, 316: 118, 280: 118, 282: 117, 19: 116, 277: 113, 279: 112, 300: 112, 270: 111, 38: 109, 320: 109, 30: 108, 294: 108, 332: 106, 22: 103, 314: 102, 301: 102, 293: 101, 313: 100, 15: 99, 325: 99, 295: 98, 273: 97, 24: 96, 283: 96, 315: 94, 334: 94, 329: 93, 281: 93, 305: 92, 21: 91, 318: 91, 306: 87, 284: 87, 287: 86, 303: 84, 13: 84, 275: 83, 336: 81, 322: 80, 328: 79, 324: 78, 337: 77, 302: 77, 308: 74, 326: 73, 310: 73, 346: 72, 335: 72, 327: 71, 309: 70, 297: 70, 349: 70, 364: 69, 311: 69, 16: 68, 339: 68, 345: 66, 348: 66, 340: 66, 353: 66, 343: 65, 321: 63, 20: 63, 330: 63, 17: 62, 312: 61, 307: 60, 18: 59, 351: 58, 317: 57, 361: 56, 368: 54, 342: 53, 354: 53, 323: 52, 436: 51, 344: 50, 331: 50, 362: 49, 393: 49, 376: 49, 333: 49, 359: 48, 367: 48, 352: 48, 372: 46, 356: 46, 399: 46, 338: 45, 350: 44, 355: 44, 365: 44, 360: 42, 417: 42, 380: 42, 386: 42, 347: 42, 12: 42, 358: 41, 374: 41, 366: 40, 369: 39, 426: 39, 11: 39, 383: 38, 371: 38, 402: 37, 373: 36, 363: 35, 419: 34, 388: 34, 400: 34, 370: 34, 14: 33, 357: 33, 439: 33, 341: 32, 433: 31, 401: 31, 394: 31, 387: 30, 407: 29, 398: 29, 390: 28, 434: 28, 381: 28, 448: 28, 378: 27, 385: 26, 392: 26, 384: 26, 405: 26, 418: 25, 440: 25, 413: 24, 423: 24, 379: 24, 396: 23, 406: 23, 389: 23, 391: 22, 450: 22, 446: 22, 382: 22, 410: 22, 409: 22, 441: 21, 453: 21, 414: 21, 404: 21, 460: 21, 403: 21, 427: 20, 411: 20, 412: 20, 435: 20, 422: 20, 420: 19, 377: 19, 416: 19, 451: 18, 415: 18, 395: 17, 375: 17, 442: 16, 425: 16, 431: 16, 438: 16, 421: 16, 509: 16, 562: 16, 486: 16, 508: 15, 557: 15, 462: 14, 455: 14, 430: 14, 473: 14, 583: 13, 469: 13, 445: 13, 463: 13, 461: 12, 499: 12, 500: 12, 523: 12, 496: 12, 542: 12, 424: 12, 457: 12, 408: 12, 478: 12, 465: 11, 437: 11, 444: 11, 447: 11, 488: 11, 479: 11, 529: 10, 530: 10, 464: 10, 503: 10, 452: 10, 397: 9, 429: 9, 533: 9, 511: 9, 475: 9, 480: 9, 498: 9, 543: 9, 474: 9, 619: 8, 8: 8, 515: 8, 467: 8, 477: 8, 449: 8, 471: 8, 466: 8, 531: 8, 3: 8, 620: 8, 497: 7, 538: 7, 468: 7, 501: 7, 518: 7, 476: 7, 519: 7, 525: 7, 605: 7, 493: 7, 540: 7, 481: 7, 534: 6, 735: 6, 10: 6, 598: 6, 574: 6, 484: 6, 551: 6, 632: 6, 600: 6, 590: 6, 490: 6, 432: 6, 622: 6, 494: 6, 577: 5, 720: 5, 566: 5, 535: 5, 510: 5, 698: 5, 458: 5, 428: 5, 559: 5, 541: 5, 652: 5, 641: 5, 668: 5, 646: 5, 572: 5, 9: 5, 495: 5, 582: 5, 472: 5, 716: 5, 532: 5, 482: 5, 552: 4, 470: 4, 7: 4, 623: 4, 487: 4, 545: 4, 604: 4, 454: 4, 483: 4, 504: 4, 502: 4, 573: 4, 492: 3, 634: 3, 576: 3, 520: 3, 553: 3, 485: 3, 639: 3, 5: 3, 459: 3, 613: 3, 537: 2, 456: 2, 614: 2, 549: 2, 548: 2, 6: 2, 628: 2, 621: 2, 617: 2, 625: 2, 489: 2, 615: 2, 744: 2, 550: 2, 618: 2, 491: 2, 513: 2, 567: 2, 512: 2, 539: 2, 565: 2, 642: 2, 746: 2, 522: 1, 514: 1, 663: 1, 564: 1, 563: 1, 593: 1, 579: 1, 754: 1, 524: 1, 527: 1, 544: 1, 1033: 1, 665: 1, 671: 1, 507: 1, 729: 1, 650: 1, 882: 1, 685: 1, 602: 1, 599: 1, 597: 1, 636: 1, 931: 1, 568: 1, 578: 1, 783: 1, 516: 1, 778: 1, 546: 1, 739: 1, 607: 1, 505: 1, 560: 1, 536: 1, 630: 1, 1087: 1, 526: 1, 810: 1, 443: 1, 631: 1, 586: 1, 1137: 1, 581: 1, 624: 1, 627: 1, 638: 1, 584: 1, 694: 1}

  [options]
    dtype      : object
    sample val : array(['A)21', 'B)21.5', 'C)22', 'D)22.5', 'E)23'], dtype=object)
    nulls      : 0
    n_unique   : unhashable (list/array column)
    len dist   : {5: 97467}

  [rationale]
    dtype      : object
    sample val : 'If Q complete x kilometers, then P completes 1.15x kilometers.\nx + 1.15x = 43\n2.15x=43\nx = 43/2.15 = 20\nThen P will
    nulls      : 0
    n_unique   : 90941
    len dist   : {94: 487, 137: 471, 131: 465, 107: 463, 112: 457, 127: 451, 69: 451, 119: 445, 95: 438, 100: 438, 96: 434, 130: 427, 104: 423, 141: 423, 109: 419, 91: 418, 156: 412, 108: 412, 80: 411, 79: 411, 78: 411, 143: 410, 92: 410, 106: 408, 118: 408, 89: 406, 54: 406, 145: 406, 124: 405, 81: 404, 93: 403, 113: 402, 67: 402, 128: 402, 70: 402, 162: 401, 90: 400, 114: 400, 102: 400, 158: 398, 76: 397, 136: 397, 56: 396, 129: 395, 144: 394, 126: 392, 123: 391, 134: 391, 110: 388, 99: 387, 160: 386, 82: 385, 138: 385, 125: 385, 73: 385, 101: 384, 49: 384, 53: 383, 86: 383, 111: 381, 55: 381, 57: 381, 161: 381, 132: 381, 103: 377, 180: 376, 97: 376, 148: 375, 117: 374, 87: 374, 115: 374, 88: 372, 59: 372, 146: 371, 71: 370, 51: 369, 164: 368, 147: 368, 83: 368, 184: 366, 66: 366, 159: 365, 142: 364, 65: 364, 98: 363, 122: 362, 150: 361, 41: 361, 120: 359, 68: 359, 75: 359, 155: 358, 186: 357, 74: 356, 157: 353, 121: 353, 72: 352, 77: 351, 47: 351, 61: 350, 151: 349, 52: 347, 105: 346, 139: 344, 185: 343, 154: 342, 135: 341, 168: 340, 58: 339, 133: 337, 46: 336, 84: 336, 116: 335, 48: 334, 40: 334, 181: 332, 166: 332, 39: 328, 37: 328, 43: 327, 153: 326, 42: 324, 64: 322, 171: 322, 200: 321, 45: 321, 149: 321, 140: 320, 163: 318, 169: 318, 44: 316, 63: 315, 165: 314, 85: 313, 172: 312, 62: 310, 50: 310, 38: 307, 152: 305, 170: 305, 183: 303, 175: 301, 182: 299, 176: 297, 190: 296, 193: 295, 178: 293, 174: 293, 32: 292, 173: 291, 192: 291, 33: 289, 36: 288, 203: 287, 197: 282, 60: 281, 187: 280, 35: 279, 177: 277, 205: 273, 189: 272, 191: 270, 194: 269, 167: 269, 179: 267, 204: 265, 210: 261, 206: 261, 188: 260, 218: 259, 213: 259, 34: 256, 195: 254, 225: 254, 201: 252, 223: 251, 196: 251, 207: 251, 202: 250, 208: 247, 212: 246, 226: 245, 211: 239, 199: 237, 198: 235, 222: 235, 219: 233, 231: 232, 224: 228, 217: 227, 239: 226, 220: 217, 233: 217, 28: 215, 238: 214, 230: 214, 259: 210, 227: 210, 209: 210, 216: 209, 229: 207, 232: 206, 215: 206, 236: 203, 235: 202, 214: 201, 251: 195, 249: 192, 237: 192, 253: 192, 244: 191, 234: 189, 31: 189, 228: 189, 29: 186, 247: 184, 257: 176, 243: 176, 248: 173, 245: 173, 265: 170, 262: 167, 277: 167, 256: 167, 260: 166, 30: 163, 250: 163, 221: 162, 25: 160, 246: 159, 258: 156, 252: 155, 278: 155, 276: 152, 263: 151, 279: 151, 269: 149, 266: 148, 241: 147, 261: 146, 268: 146, 240: 146, 242: 146, 282: 143, 329: 143, 292: 143, 267: 142, 281: 141, 306: 141, 255: 139, 285: 136, 272: 135, 280: 135, 309: 132, 288: 131, 302: 130, 283: 130, 24: 129, 290: 129, 311: 128, 264: 128, 289: 128, 287: 127, 284: 123, 291: 122, 321: 120, 26: 119, 314: 119, 298: 119, 271: 118, 301: 116, 308: 116, 274: 115, 295: 115, 254: 114, 10: 114, 307: 111, 273: 111, 270: 110, 305: 109, 313: 109, 27: 109, 293: 108, 8: 107, 275: 107, 297: 106, 317: 105, 303: 105, 318: 105, 304: 105, 300: 101, 299: 100, 326: 99, 286: 99, 327: 99, 320: 98, 310: 98, 294: 97, 322: 96, 367: 96, 312: 96, 296: 95, 319: 95, 328: 95, 389: 94, 348: 94, 331: 94, 324: 93, 333: 93, 342: 92, 347: 92, 364: 91, 323: 90, 341: 89, 335: 89, 330: 87, 340: 86, 375: 85, 332: 84, 337: 83, 316: 83, 351: 82, 365: 81, 22: 80, 315: 80, 380: 79, 325: 79, 366: 78, 363: 78, 334: 78, 357: 78, 344: 77, 356: 76, 345: 76, 397: 76, 387: 76, 346: 76, 369: 74, 373: 74, 354: 74, 371: 73, 403: 73, 362: 73, 336: 72, 377: 72, 339: 72, 404: 72, 343: 72, 401: 71, 353: 70, 23: 70, 20: 70, 352: 69, 381: 69, 359: 69, 378: 68, 413: 68, 349: 68, 361: 68, 376: 67, 394: 67, 402: 67, 379: 66, 19: 66, 350: 66, 370: 66, 390: 65, 391: 65, 21: 64, 338: 63, 383: 62, 374: 62, 382: 62, 399: 62, 384: 62, 360: 60, 388: 60, 395: 60, 407: 59, 405: 59, 368: 59, 420: 58, 406: 58, 409: 58, 385: 57, 372: 56, 429: 56, 418: 56, 419: 56, 13: 55, 355: 53, 417: 53, 358: 53, 1: 52, 393: 52, 392: 51, 464: 51, 410: 50, 9: 49, 411: 49, 400: 48, 426: 48, 408: 48, 423: 48, 16: 48, 425: 48, 443: 48, 412: 48, 447: 47, 431: 47, 398: 47, 386: 47, 415: 46, 469: 46, 438: 45, 512: 45, 480: 45, 436: 45, 506: 44, 452: 43, 473: 43, 424: 43, 440: 43, 14: 43, 427: 42, 433: 42, 396: 42, 17: 42, 432: 42, 460: 42, 445: 42, 482: 42, 18: 41, 461: 40, 450: 40, 444: 40, 430: 39, 414: 38, 522: 38, 441: 38, 428: 38, 422: 37, 472: 37, 485: 37, 421: 37, 416: 37, 501: 36, 496: 36, 446: 35, 495: 35, 439: 35, 457: 35, 435: 35, 507: 35, 458: 34, 534: 34, 540: 34, 528: 33, 483: 33, 546: 33, 437: 33, 491: 32, 468: 32, 479: 32, 456: 32, 503: 31, 488: 31, 449: 31, 434: 31, 5: 31, 463: 31, 459: 30, 490: 30, 510: 30, 465: 30, 487: 30, 617: 29, 564: 29, 470: 29, 516: 29, 475: 29, 476: 29, 542: 28, 448: 28, 489: 28, 442: 28, 451: 28, 477: 28, 493: 28, 520: 28, 453: 28, 509: 28, 11: 27, 505: 27, 455: 27, 499: 27, 4: 27, 521: 27, 492: 27, 526: 27, 504: 27, 558: 26, 577: 26, 486: 26, 497: 25, 467: 25, 15: 25, 511: 25, 587: 25, 519: 25, 601: 25, 514: 25, 517: 24, 537: 24, 536: 24, 454: 24, 538: 24, 602: 24, 563: 24, 606: 24, 12: 23, 523: 23, 6: 23, 532: 23, 589: 23, 484: 23, 527: 23, 635: 22, 599: 22, 566: 22, 471: 22, 466: 22, 560: 22, 478: 22, 610: 21, 565: 21, 571: 21, 609: 21, 474: 21, 579: 21, 541: 21, 655: 20, 559: 20, 561: 20, 525: 20, 531: 20, 547: 20, 785: 20, 535: 20, 621: 20, 502: 19, 462: 19, 494: 19, 581: 19, 513: 19, 614: 19, 530: 19, 533: 18, 544: 18, 529: 18, 666: 18, 576: 18, 555: 18, 597: 18, 596: 18, 582: 17, 584: 17, 646: 17, 570: 17, 608: 17, 624: 17, 715: 17, 481: 17, 604: 17, 572: 17, 551: 17, 508: 16, 498: 16, 738: 16, 629: 16, 662: 16, 690: 16, 539: 16, 640: 16, 668: 16, 644: 16, 557: 16, 500: 16, 615: 16, 684: 16, 632: 15, 592: 15, 779: 15, 518: 15, 628: 15, 616: 15, 548: 15, 605: 15, 652: 15, 573: 15, 552: 15, 3: 15, 636: 15, 654: 15, 569: 15, 603: 14, 758: 14, 524: 14, 549: 14, 586: 14, 607: 14, 598: 14, 556: 14, 578: 14, 796: 14, 625: 14, 784: 14, 657: 14, 553: 14, 673: 14, 631: 14, 545: 14, 574: 14, 620: 13, 672: 13, 647: 13, 639: 13, 619: 13, 591: 13, 622: 13, 567: 13, 692: 13, 543: 13, 689: 13, 575: 13, 656: 13, 724: 13, 713: 13, 788: 12, 600: 12, 773: 12, 667: 12, 695: 12, 611: 12, 734: 12, 515: 12, 653: 12, 594: 12, 824: 12, 634: 12, 670: 12, 7: 12, 671: 12, 756: 11, 1001: 11, 568: 11, 627: 11, 851: 11, 626: 11, 669: 11, 612: 11, 554: 11, 798: 11, 776: 11, 783: 11, 642: 11, 650: 11, 707: 11, 735: 11, 704: 11, 891: 11, 741: 11, 1637: 10, 637: 10, 823: 10, 721: 10, 693: 10, 595: 10, 674: 10, 701: 10, 660: 10, 838: 10, 934: 10, 777: 10, 904: 10, 633: 10, 649: 10, 630: 10, 729: 10, 2: 10, 688: 9, 550: 9, 754: 9, 749: 9, 694: 9, 658: 9, 849: 9, 979: 9, 782: 9, 613: 9, 832: 9, 580: 9, 714: 9, 956: 9, 664: 9, 812: 9, 752: 9, 665: 9, 746: 9, 852: 9, 593: 9, 775: 8, 913: 8, 562: 8, 811: 8, 866: 8, 623: 8, 911: 8, 765: 8, 819: 8, 850: 8, 585: 8, 726: 8, 583: 8, 728: 8, 706: 8, 750: 8, 696: 8, 803: 8, 685: 8, 742: 8, 757: 8, 825: 8, 839: 8, 813: 8, 787: 8, 800: 8, 921: 8, 590: 8, 745: 8, 691: 8, 874: 7, 663: 7, 736: 7, 648: 7, 725: 7, 954: 7, 1147: 7, 808: 7, 686: 7, 732: 7, 778: 7, 815: 7, 720: 7, 890: 7, 833: 7, 1019: 7, 682: 7, 710: 7, 697: 7, 755: 7, 743: 7, 834: 7, 885: 7, 678: 7, 748: 7, 588: 7, 1073: 7, 638: 7, 1459: 6, 791: 6, 703: 6, 790: 6, 1678: 6, 795: 6, 618: 6, 1105: 6, 1080: 6, 1387: 6, 831: 6, 676: 6, 718: 6, 717: 6, 883: 6, 1024: 6, 683: 6, 659: 6, 687: 6, 915: 6, 679: 6, 722: 6, 940: 6, 949: 6, 1122: 6, 865: 6, 700: 6, 958: 6, 733: 6, 799: 6, 919: 6, 1259: 5, 1547: 5, 983: 5, 841: 5, 709: 5, 769: 5, 1962: 5, 945: 5, 1190: 5, 770: 5, 1207: 5, 1373: 5, 1039: 5, 1304: 5, 2107: 5, 1162: 5, 1124: 5, 1052: 5, 843: 5, 719: 5, 1450: 5, 699: 5, 723: 5, 1475: 5, 677: 5, 1467: 5, 1699: 5, 1056: 5, 994: 5, 737: 5, 1301: 5, 744: 5, 1129: 5, 905: 5, 2490: 5, 1002: 5, 731: 5, 809: 5, 1142: 5, 643: 5, 855: 5, 1114: 5, 1223: 5, 1800: 5, 1082: 5, 1070: 5, 900: 5, 675: 5, 899: 5, 820: 5, 3684: 5, 681: 5, 991: 4, 1411: 4, 730: 4, 1228: 4, 896: 4, 998: 4, 661: 4, 766: 4, 1121: 4, 827: 4, 830: 4, 966: 4, 1679: 4, 875: 4, 753: 4, 837: 4, 805: 4, 1027: 4, 910: 4, 1123: 4, 881: 4, 786: 4, 712: 4, 698: 4, 1364: 4, 727: 4, 645: 4, 903: 4, 1479: 4, 1757: 4, 857: 4, 739: 4, 794: 4, 705: 4, 1157: 4, 864: 3, 870: 3, 821: 3, 814: 3, 952: 3, 862: 3, 1292: 3, 1048: 3, 1107: 3, 1254: 3, 702: 3, 1294: 3, 641: 3, 1021: 3, 711: 3, 1000: 3, 759: 3, 878: 3, 1230: 3, 977: 3, 889: 3, 822: 3, 767: 3, 950: 3, 772: 3, 884: 3, 933: 3, 761: 3, 918: 3, 1193: 3, 802: 3, 871: 3, 771: 3, 1305: 3, 975: 3, 1192: 3, 912: 3, 880: 3, 1321: 3, 768: 3, 1028: 3, 970: 3, 762: 3, 1029: 3, 1008: 3, 751: 3, 1172: 3, 968: 3, 774: 3, 1488: 3, 867: 3, 1233: 3, 989: 3, 806: 3, 1541: 3, 1079: 3, 888: 3, 792: 3, 2635: 3, 986: 2, 1171: 2, 974: 2, 926: 2, 1169: 2, 957: 2, 1064: 2, 1018: 2, 971: 2, 869: 2, 947: 2, 1264: 2, 1053: 2, 1706: 2, 929: 2, 1303: 2, 1216: 2, 990: 2, 1941: 2, 801: 2, 747: 2, 860: 2, 948: 2, 829: 2, 965: 2, 1026: 2, 848: 2, 835: 2, 1004: 2, 937: 2, 972: 2, 942: 2, 1054: 2, 1823: 2, 1452: 2, 1773: 2, 1010: 2, 817: 2, 924: 2, 1133: 2, 1164: 2, 1243: 2, 922: 2, 1012: 2, 740: 2, 953: 2, 1263: 2, 914: 2, 1392: 2, 760: 2, 708: 2, 1083: 2, 1014: 2, 893: 2, 892: 2, 1231: 2, 920: 2, 1323: 2, 935: 2, 1478: 2, 1141: 2, 842: 2, 1096: 2, 1017: 2, 826: 2, 907: 2, 845: 2, 1175: 2, 908: 2, 969: 2, 1359: 2, 1237: 2, 846: 2, 789: 2, 780: 2, 1252: 2, 879: 2, 716: 2, 1297: 2, 1062: 2, 886: 2, 861: 2, 840: 2, 844: 2, 1020: 1, 1447: 1, 1138: 1, 961: 1, 909: 1, 1170: 1, 1350: 1, 1090: 1, 901: 1, 1040: 1, 944: 1, 1473: 1, 2209: 1, 936: 1, 763: 1, 859: 1, 1485: 1, 1240: 1, 1687: 1, 2885: 1, 1352: 1, 1120: 1, 925: 1, 955: 1, 853: 1, 1544: 1, 1482: 1, 1236: 1, 1976: 1, 1789: 1, 1722: 1, 876: 1, 1066: 1, 1111: 1, 1432: 1, 1038: 1, 895: 1, 858: 1, 1148: 1, 1298: 1, 680: 1, 1058: 1, 1503: 1, 1144: 1, 1412: 1, 1092: 1, 951: 1, 1168: 1, 1262: 1, 810: 1, 1433: 1, 1360: 1, 1662: 1, 1692: 1, 997: 1, 1077: 1, 887: 1, 1022: 1, 928: 1, 1195: 1, 1734: 1, 1354: 1, 993: 1, 1334: 1, 1110: 1, 1363: 1, 1540: 1, 1522: 1, 1336: 1, 1043: 1, 1333: 1, 1428: 1, 1187: 1, 818: 1, 939: 1, 797: 1, 1930: 1, 1245: 1, 1069: 1, 1437: 1, 1796: 1, 2411: 1, 1239: 1, 781: 1, 1176: 1, 1155: 1, 2154: 1, 1410: 1, 1362: 1, 1310: 1, 1106: 1, 1314: 1, 1025: 1, 1116: 1, 1850: 1, 985: 1, 1424: 1, 1358: 1, 2636: 1, 873: 1, 2632: 1, 894: 1, 854: 1, 1091: 1, 1246: 1, 1756: 1, 1460: 1, 1367: 1, 816: 1, 1353: 1, 1355: 1, 1158: 1, 1451: 1, 1560: 1, 1293: 1, 1221: 1, 1182: 1, 1078: 1, 1042: 1, 1308: 1, 1076: 1, 1542: 1, 1183: 1, 1023: 1, 1060: 1, 1242: 1, 1846: 1, 1103: 1, 1031: 1, 868: 1, 1033: 1, 1783: 1, 2005: 1, 1013: 1, 1688: 1, 980: 1, 1279: 1, 1225: 1, 1568: 1, 1206: 1, 1287: 1, 1191: 1, 930: 1, 1550: 1, 882: 1, 1095: 1, 1397: 1, 1130: 1, 1943: 1, 1980: 1, 1916: 1, 1072: 1, 2382: 1, 2160: 1, 863: 1, 1160: 1, 828: 1, 1229: 1, 927: 1, 1487: 1, 1011: 1, 1075: 1, 793: 1, 902: 1, 1261: 1, 906: 1, 963: 1, 2003: 1, 1137: 1, 836: 1, 982: 1, 2386: 1, 1312: 1, 1087: 1, 1041: 1, 1794: 1, 931: 1, 1094: 1, 1300: 1, 1572: 1, 1125: 1, 1434: 1, 1055: 1, 1068: 1, 1104: 1, 1707: 1, 1790: 1, 1047: 1, 1545: 1}

  [correct]
    dtype      : object
    sample val : 'E'
    nulls      : 0
    n_unique   : 5
    counts     : {'C': 22290, 'B': 21446, 'A': 20494, 'D': 19441, 'E': 13796}
    len dist   : {1: 97467}

  ── First 3 examples ──────────────────────────────────────
  ── Example 0 ────────────────────────────────────────
  question            : "Two friends plan to walk along a 43-km trail, starting at opposite ends of the trail at the same time. If Friend P's rate is 15% faster than Friend Q's, how many kilometers will Friend P have walked when they pass each other?"
  options             : ['A)21', 'B)21.5', 'C)22', 'D)22.5', 'E)23']
  rationale           : 'If Q complete x kilometers, then P completes 1.15x kilometers.\nx + 1.15x = 43\n2.15x=43\nx = 43/2.15 = 20\nThen P will have have walked 1.15*20=23 km.\nThe answer is E.'
  correct             : 'E'

  ── Example 1 ────────────────────────────────────────
  question            : 'In the coordinate plane, points (x, 1) and (5, y) are on line k. If line k passes through the origin and has slope 1/5, then what are the values of x and y respectively?'
  options             : ['A)4 and 1', 'B)1 and 5', 'C)5 and 1', 'D)3 and 5', 'E)5 and 3']
  rationale           : 'Line k passes through the origin and has slope 1/5 means that its equation is y=1/5*x.\nThus: (x, 1)=(5, 1) and (5, y) = (5,1) -->x=5 and y=1\nAnswer: C'
  correct             : 'C'

  ── Example 2 ────────────────────────────────────────
  question            : 'For all numbers p and q, the operation @ is defined by p@q = p^2 - pq. If xy ≠ 0, then which of the following can be equal to zero?\nI. x@y\nII. (xy)@y\nIII. x@(x + y)'
  options             : ['A)II', 'B)I and II', 'C)I and III', 'D)II and III', 'E)All of the above']
  rationale           : 'p@q = p^2 - pq=p(p-q).... so p@q will be zero if p=q or p=0.. but a cannot be equal to 0.. as per Q, x and y can take any int value except 0...\nnow lets look at the choices..\nwhen x=y, it will be 0... so ok...\nwhen we put xy=y, it is possible when x=1 and y any integer... so ok again\nwhen we put x=x+y.... only possibility when y=0 and it is given x and y cannot be 0....so not possible\nonly l and ll possible ans B....'
  correct             : 'B'

  After dedup: 96844 available (excluded 623)
  Returning sampled DataFrame — 500 rows (seed=42)

In [ ]:
# What fields do we have?
print(df_aqua.columns.tolist())
print()

# What does the answer field look like?
print(df_aqua["correct"].value_counts())
print()

# How many options per question?
df_aqua["options"].apply(len).value_counts()

['question', 'options', 'rationale', 'correct']

correct
C    122
B    116
A    108
D     97
E     57
Name: count, dtype: int64

options
5    500
Name: count, dtype: int64

## ReClor
Logical reasoning (substitute for LogiQA)

In [ ]:
df_reclor = explore("metaeval/reclor", name=None, split="train", n=3, sample=500)

============================================================
  metaeval/reclor  |  config=None
============================================================

README.md:   0%|          | 0.00/407 [00:00<?, ?B/s]

  Available splits : ['train', 'validation']
  Loading split    : 'train' ...

train.json: 0.00B [00:00, ?B/s]

val.json: 0.00B [00:00, ?B/s]

Generating train split:   0%|          | 0/4638 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/500 [00:00<?, ? examples/s]

  ── Full dataset stats ──────────────────────────────────────
  Total rows  : 4638
  Columns     : ['answers', 'context', 'label', 'id_string', 'question']

  [answers]
    dtype      : object
    sample val : array(['Unlike aspirin and other medications that reduce pain and swelling and that are currently available, the new med
    nulls      : 0
    n_unique   : unhashable (list/array column)
    len dist   : {4: 4638}

  [context]
    dtype      : object
    sample val : "In rheumatoid arthritis, the body' s immune system misfunctions by attacking healthy cells in the joints causing the re
    nulls      : 0
    n_unique   : 4628
    len dist   : {361: 26, 445: 25, 317: 23, 391: 23, 358: 21, 430: 21, 341: 20, 398: 20, 466: 20, 441: 20, 334: 19, 421: 19, 350: 19, 351: 19, 382: 18, 458: 18, 429: 18, 316: 18, 370: 18, 432: 18, 483: 18, 438: 18, 359: 18, 383: 18, 425: 18, 392: 18, 328: 18, 427: 17, 418: 17, 414: 17, 374: 17, 461: 17, 385: 17, 456: 17, 356: 17, 371: 17, 368: 17, 387: 17, 515: 17, 397: 17, 396: 17, 450: 17, 494: 16, 491: 16, 417: 16, 453: 16, 333: 16, 451: 16, 411: 16, 363: 16, 403: 16, 342: 16, 365: 16, 479: 16, 330: 16, 399: 16, 420: 16, 288: 16, 444: 16, 401: 16, 307: 16, 454: 16, 322: 16, 409: 16, 460: 16, 434: 16, 353: 15, 507: 15, 506: 15, 308: 15, 354: 15, 424: 15, 384: 15, 407: 15, 339: 15, 381: 15, 412: 15, 343: 15, 508: 15, 390: 15, 435: 15, 410: 15, 426: 15, 416: 14, 335: 14, 462: 14, 315: 14, 437: 14, 326: 14, 394: 14, 324: 14, 468: 14, 369: 14, 500: 14, 373: 14, 442: 14, 289: 14, 480: 14, 395: 14, 471: 14, 293: 14, 388: 14, 431: 14, 475: 14, 389: 14, 465: 14, 376: 14, 346: 14, 337: 13, 352: 13, 362: 13, 386: 13, 405: 13, 484: 13, 404: 13, 467: 13, 440: 13, 482: 13, 323: 13, 510: 13, 447: 13, 413: 13, 436: 13, 378: 13, 364: 13, 472: 13, 408: 13, 487: 13, 419: 13, 485: 13, 375: 13, 457: 13, 446: 13, 366: 13, 348: 13, 402: 13, 347: 13, 331: 13, 455: 13, 481: 13, 312: 13, 499: 12, 452: 12, 406: 12, 314: 12, 469: 12, 493: 12, 514: 12, 311: 12, 321: 12, 522: 12, 400: 12, 476: 12, 448: 12, 340: 12, 393: 12, 511: 12, 304: 12, 490: 12, 439: 12, 377: 12, 423: 12, 488: 12, 310: 12, 464: 12, 332: 12, 516: 12, 320: 12, 477: 12, 360: 11, 336: 11, 319: 11, 305: 11, 502: 11, 443: 11, 349: 11, 463: 11, 327: 11, 282: 11, 275: 11, 338: 11, 279: 11, 298: 11, 296: 11, 449: 11, 345: 11, 344: 11, 498: 11, 309: 11, 367: 11, 355: 11, 415: 11, 277: 11, 285: 11, 459: 11, 318: 11, 542: 11, 259: 11, 504: 10, 280: 10, 505: 10, 292: 10, 209: 10, 380: 10, 486: 10, 531: 10, 433: 10, 258: 10, 577: 10, 291: 10, 263: 10, 325: 10, 521: 10, 300: 10, 303: 10, 503: 10, 537: 10, 268: 10, 428: 10, 232: 10, 254: 10, 549: 10, 530: 9, 281: 9, 496: 9, 266: 9, 372: 9, 264: 9, 265: 9, 512: 9, 552: 9, 524: 9, 250: 9, 313: 9, 605: 9, 544: 9, 497: 9, 240: 9, 215: 9, 299: 9, 261: 9, 495: 9, 357: 9, 422: 9, 526: 8, 329: 8, 276: 8, 553: 8, 222: 8, 297: 8, 564: 8, 538: 8, 233: 8, 474: 8, 235: 8, 525: 8, 302: 8, 545: 8, 225: 8, 520: 8, 267: 8, 257: 8, 284: 8, 509: 8, 513: 7, 631: 7, 561: 7, 218: 7, 241: 7, 379: 7, 565: 7, 533: 7, 535: 7, 519: 7, 192: 7, 501: 7, 527: 7, 230: 7, 295: 7, 585: 7, 536: 7, 234: 7, 528: 7, 278: 7, 247: 7, 559: 7, 566: 7, 273: 7, 270: 6, 478: 6, 221: 6, 156: 6, 541: 6, 272: 6, 532: 6, 632: 6, 473: 6, 210: 6, 238: 6, 568: 6, 551: 6, 294: 6, 231: 6, 518: 6, 252: 6, 271: 6, 563: 6, 204: 6, 489: 6, 287: 6, 286: 6, 239: 6, 260: 6, 220: 6, 492: 6, 306: 6, 249: 6, 540: 6, 255: 6, 576: 5, 596: 5, 547: 5, 283: 5, 641: 5, 651: 5, 517: 5, 269: 5, 594: 5, 604: 5, 246: 5, 608: 5, 560: 5, 581: 5, 567: 5, 572: 5, 251: 5, 803: 5, 219: 5, 642: 5, 539: 5, 290: 5, 256: 5, 571: 5, 301: 5, 189: 5, 570: 5, 182: 5, 174: 5, 181: 5, 211: 5, 575: 5, 470: 5, 195: 5, 199: 5, 262: 5, 248: 5, 227: 5, 674: 5, 217: 5, 610: 5, 245: 5, 164: 5, 229: 5, 603: 5, 543: 5, 679: 4, 597: 4, 684: 4, 687: 4, 226: 4, 236: 4, 586: 4, 580: 4, 827: 4, 224: 4, 609: 4, 600: 4, 660: 4, 196: 4, 772: 4, 200: 4, 598: 4, 583: 4, 649: 4, 244: 4, 557: 4, 198: 4, 523: 4, 216: 4, 593: 4, 573: 4, 619: 4, 179: 4, 550: 4, 201: 4, 529: 4, 606: 4, 574: 4, 591: 4, 212: 4, 140: 4, 160: 4, 657: 4, 569: 4, 214: 4, 147: 3, 618: 3, 621: 3, 582: 3, 735: 3, 705: 3, 719: 3, 578: 3, 177: 3, 207: 3, 711: 3, 136: 3, 611: 3, 622: 3, 168: 3, 142: 3, 658: 3, 623: 3, 676: 3, 725: 3, 764: 3, 712: 3, 702: 3, 692: 3, 159: 3, 616: 3, 691: 3, 588: 3, 145: 3, 175: 3, 650: 3, 208: 3, 713: 3, 602: 3, 751: 3, 724: 3, 169: 3, 638: 3, 190: 3, 197: 3, 624: 3, 599: 3, 730: 3, 648: 3, 761: 3, 202: 3, 184: 3, 206: 3, 187: 3, 683: 3, 670: 3, 554: 3, 158: 3, 617: 3, 274: 3, 644: 3, 185: 3, 148: 3, 555: 3, 704: 2, 656: 2, 188: 2, 149: 2, 144: 2, 146: 2, 637: 2, 663: 2, 253: 2, 237: 2, 155: 2, 646: 2, 587: 2, 133: 2, 690: 2, 171: 2, 717: 2, 768: 2, 612: 2, 163: 2, 205: 2, 633: 2, 183: 2, 795: 2, 558: 2, 647: 2, 151: 2, 584: 2, 176: 2, 709: 2, 626: 2, 682: 2, 170: 2, 673: 2, 123: 2, 753: 2, 161: 2, 847: 2, 223: 2, 694: 2, 748: 2, 669: 2, 706: 2, 243: 2, 203: 2, 747: 2, 191: 2, 548: 2, 613: 2, 645: 2, 675: 2, 773: 2, 228: 2, 715: 2, 710: 2, 193: 2, 716: 2, 590: 2, 154: 2, 562: 2, 728: 2, 534: 2, 167: 2, 143: 2, 793: 2, 886: 2, 697: 2, 634: 2, 636: 2, 681: 2, 655: 2, 740: 2, 242: 2, 708: 2, 589: 2, 126: 2, 654: 2, 141: 2, 699: 2, 782: 2, 742: 2, 800: 1, 579: 1, 925: 1, 727: 1, 615: 1, 556: 1, 116: 1, 757: 1, 680: 1, 766: 1, 877: 1, 798: 1, 677: 1, 601: 1, 732: 1, 166: 1, 659: 1, 869: 1, 854: 1, 178: 1, 784: 1, 546: 1, 111: 1, 595: 1, 152: 1, 165: 1, 738: 1, 162: 1, 783: 1, 823: 1, 775: 1, 114: 1, 186: 1, 671: 1, 718: 1, 607: 1, 832: 1, 788: 1, 688: 1, 703: 1, 729: 1, 667: 1, 720: 1, 726: 1, 736: 1, 701: 1, 1005: 1, 157: 1, 696: 1, 134: 1, 814: 1, 194: 1, 698: 1, 665: 1, 672: 1, 127: 1, 744: 1, 627: 1, 128: 1, 790: 1, 749: 1, 842: 1, 640: 1, 754: 1, 125: 1, 614: 1, 94: 1, 769: 1, 988: 1, 678: 1, 135: 1, 734: 1, 707: 1, 95: 1, 592: 1, 131: 1, 760: 1, 172: 1, 180: 1, 653: 1, 150: 1, 661: 1, 685: 1, 750: 1, 628: 1, 119: 1, 620: 1, 643: 1, 741: 1, 781: 1, 102: 1, 108: 1, 901: 1, 1135: 1, 945: 1, 173: 1, 746: 1, 153: 1, 745: 1, 786: 1}

  [label]
    dtype      : int64
    sample val : np.int64(1)
    nulls      : 0
    n_unique   : 4
    counts     : {0: 1171, 1: 1170, 2: 1154, 3: 1143}

  [id_string]
    dtype      : object
    sample val : 'train_0'
    nulls      : 0
    n_unique   : 4638
    len dist   : {10: 3638, 9: 900, 8: 90, 7: 10}

  [question]
    dtype      : object
    sample val : 'The statements above, if true, most strongly support which one of the following conclusions?'
    nulls      : 0
    n_unique   : 3372
    len dist   : {74: 138, 79: 123, 69: 112, 84: 110, 86: 105, 80: 104, 60: 102, 90: 99, 67: 94, 94: 93, 73: 90, 83: 87, 70: 87, 89: 84, 78: 83, 91: 82, 81: 79, 95: 73, 87: 71, 77: 70, 85: 70, 82: 69, 63: 68, 88: 68, 101: 66, 92: 66, 100: 65, 96: 63, 109: 63, 93: 60, 104: 60, 98: 57, 76: 56, 71: 56, 108: 55, 75: 54, 103: 54, 65: 49, 105: 47, 99: 47, 106: 47, 72: 46, 111: 44, 97: 43, 102: 40, 68: 39, 66: 39, 107: 38, 112: 34, 113: 34, 64: 31, 114: 30, 61: 29, 115: 28, 110: 27, 125: 25, 55: 24, 118: 22, 117: 22, 126: 21, 128: 21, 120: 20, 121: 20, 124: 20, 123: 20, 122: 19, 116: 19, 56: 19, 62: 19, 119: 17, 129: 16, 43: 16, 41: 15, 127: 14, 53: 14, 24: 14, 58: 14, 130: 14, 135: 13, 136: 13, 50: 13, 137: 13, 59: 11, 144: 11, 132: 11, 134: 10, 45: 10, 49: 10, 54: 10, 150: 10, 40: 9, 38: 9, 138: 9, 131: 9, 133: 9, 39: 9, 48: 9, 162: 8, 152: 8, 47: 8, 147: 8, 146: 8, 149: 8, 139: 8, 57: 7, 153: 7, 156: 7, 46: 7, 145: 7, 51: 7, 25: 7, 142: 7, 141: 7, 33: 7, 158: 7, 148: 6, 155: 6, 160: 6, 44: 6, 170: 6, 35: 6, 177: 6, 161: 6, 31: 6, 143: 5, 175: 5, 189: 5, 163: 5, 36: 5, 52: 5, 37: 5, 154: 5, 34: 4, 173: 4, 168: 4, 27: 4, 205: 4, 169: 4, 172: 4, 166: 4, 157: 4, 29: 4, 198: 4, 164: 4, 140: 3, 181: 3, 179: 3, 28: 3, 184: 3, 30: 3, 194: 3, 219: 3, 192: 3, 200: 3, 151: 3, 187: 3, 180: 3, 212: 3, 185: 3, 196: 3, 26: 3, 206: 2, 165: 2, 234: 2, 171: 2, 191: 2, 204: 2, 202: 2, 193: 2, 42: 2, 237: 2, 159: 2, 183: 2, 230: 2, 167: 2, 213: 2, 311: 1, 293: 1, 195: 1, 278: 1, 232: 1, 342: 1, 291: 1, 259: 1, 217: 1, 257: 1, 222: 1, 228: 1, 201: 1, 292: 1, 262: 1, 214: 1, 216: 1, 182: 1, 211: 1, 275: 1, 188: 1, 238: 1, 226: 1, 32: 1, 231: 1, 186: 1, 242: 1, 326: 1, 225: 1, 210: 1, 174: 1}

  ── First 3 examples ──────────────────────────────────────
  ── Example 0 ────────────────────────────────────────
  answers             : ['Unlike aspirin and other medications that reduce pain and swelling and that are currently available, the new medication would repair existing cell damage that had been caused by rheumatoid arthritis.', 'A patient treated with the new medication for rheumatoid arthritis could sustain a joint injury without becoming aware of it.', 'Joint diseases other than rheumatoid arthritis would not be affected by the new medication.', "The benefits to rheumatoid arthritis sufferers of the new medication wo
  context             : "In rheumatoid arthritis, the body' s immune system misfunctions by attacking healthy cells in the joints causing the release of a hormone that in turn causes pain and swelling. This hormone is normally activated only in reaction to injury or infection. A new arthritis medication will contain a protein that inhibits the functioning of the hormone that causes pain and swelling in the joints."
  label               : 1
  id_string           : 'train_0'
  question            : 'The statements above, if true, most strongly support which one of the following conclusions?'

  ── Example 1 ────────────────────────────────────────
  answers             : ['attempting to discredit a position by questioning the motives of the proponents of that position', 'rejecting a questionable position on the grounds that the general public does not support that position', "pointing out an unstated assumption on which the pharmacists' argument relies and then refuting it", 'asserting that pharmacists lack the appropriate knowledge to have informed opinions on the subject under discussion']
  context             : 'Patient: Pharmacists maintain that doctors should not be permitted to sell the medicine that they prescribe because doctors would then be tempted to prescribe unnecessary medicines in order to earn extra income. But pharmacists have a financial interest in having a monopoly on the sale of prescription medicines, so their objection to the sale of medicines by doctors cannot be taken seriously.'
  label               : 0
  id_string           : 'train_1'
  question            : "The patient's argument proceeds by"

  ── Example 2 ────────────────────────────────────────
  answers             : ['If Marge goes to the bank today, Lauren will not cash her check tomorrow. Marge will not wash her car unless it is sunny. However, it is sunny, so Marge will wash her car and go shopping with Lauren.', 'Kevin will wash his car tomorrow only if Brittany has to go visit her grandmother. Unless Aunt Susan has to run errands, Brittany will not have to go visit her grandmother. Since Aunt Susan does not have to run errands, Kevin will not wash his car tomorrow.', 'Renee will do her homework tonight
  context             : 'Paula will visit the dentist tomorrow morning only if Bill goes golfing in the morning. Bill will not go golfing unless Damien agrees to go golfing too. However, Damien has decided not to go golfing. Ttherefore, Paula will not be visiting the dentist tomorrow morning.'
  label               : 1
  id_string           : 'train_2'
  question            : 'The pattern of reasoning displayed above most closely parallels which of the following?'

  After dedup: 3902 available (excluded 736)
  Returning sampled DataFrame — 500 rows (seed=42)

In [ ]:
print(df_reclor.columns.tolist())
print()
print(df_reclor["label"].value_counts())
print()
df_reclor["answers"].apply(len).value_counts()

['answers', 'context', 'label', 'id_string', 'question']

label
3    138
2    129
1    122
0    111
Name: count, dtype: int64

answers
4    500
Name: count, dtype: int64

## ARC Easy
Reasoning

In [ ]:
from datasets import get_dataset_config_names
print(get_dataset_config_names("allenai/ai2_arc"))

README.md: 0.00B [00:00, ?B/s]

['ARC-Challenge', 'ARC-Easy']

In [ ]:
df_arc_easy = explore("allenai/ai2_arc", name="ARC-Easy", split="train", n=3, sample=500)

============================================================
  allenai/ai2_arc  |  config=ARC-Easy
============================================================
  Available splits : ['train', 'test', 'validation']
  Loading split    : 'train' ...

ARC-Easy/train-00000-of-00001.parquet:   0%|          | 0.00/331k [00:00<?, ?B/s]

ARC-Easy/test-00000-of-00001.parquet:   0%|          | 0.00/346k [00:00<?, ?B/s]

ARC-Easy/validation-00000-of-00001.parqu(…):   0%|          | 0.00/86.1k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/2251 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/2376 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/570 [00:00<?, ? examples/s]

  ── Full dataset stats ──────────────────────────────────────
  Total rows  : 2251
  Columns     : ['id', 'question', 'choices', 'answerKey']

  [id]
    dtype      : object
    sample val : 'Mercury_7220990'
    nulls      : 0
    n_unique   : 2251
    len dist   : {15: 911, 17: 459, 14: 351, 22: 147, 16: 125, 13: 104, 21: 63, 19: 44, 12: 17, 8: 16, 18: 14}

  [question]
    dtype      : object
    sample val : 'Which factor will most likely cause a person to develop a fever?'
    nulls      : 0
    n_unique   : 2245
    len dist   : {54: 34, 69: 32, 74: 32, 57: 27, 55: 25, 63: 24, 77: 24, 47: 24, 56: 24, 70: 24, 60: 24, 53: 23, 78: 23, 87: 23, 62: 22, 50: 22, 72: 22, 79: 22, 71: 22, 58: 21, 59: 21, 64: 21, 75: 21, 61: 20, 92: 19, 38: 19, 84: 19, 52: 19, 66: 19, 85: 19, 80: 19, 73: 19, 48: 19, 46: 19, 97: 18, 68: 18, 81: 18, 65: 18, 104: 18, 82: 18, 91: 18, 96: 18, 37: 17, 67: 17, 110: 17, 43: 17, 120: 17, 40: 16, 76: 16, 134: 15, 83: 15, 122: 15, 51: 15, 86: 14, 103: 14, 41: 14, 49: 14, 88: 14, 94: 14, 44: 13, 109: 13, 111: 13, 42: 13, 39: 13, 90: 12, 116: 12, 100: 12, 115: 12, 93: 11, 136: 11, 121: 11, 117: 11, 108: 11, 119: 11, 107: 10, 128: 10, 113: 10, 105: 10, 132: 10, 45: 10, 36: 10, 95: 10, 98: 10, 102: 10, 125: 10, 155: 10, 126: 10, 114: 9, 149: 9, 160: 9, 31: 9, 204: 9, 133: 9, 171: 9, 144: 9, 138: 9, 141: 9, 99: 9, 28: 8, 168: 8, 35: 8, 140: 8, 89: 8, 106: 8, 124: 8, 142: 8, 158: 8, 175: 8, 192: 8, 207: 7, 33: 7, 157: 7, 156: 7, 127: 7, 145: 7, 131: 7, 191: 7, 146: 7, 130: 7, 162: 7, 254: 7, 101: 7, 152: 7, 167: 7, 137: 7, 170: 7, 181: 6, 189: 6, 27: 6, 190: 6, 206: 6, 147: 6, 195: 6, 135: 6, 159: 6, 123: 6, 184: 6, 118: 6, 193: 6, 176: 6, 166: 6, 139: 6, 183: 6, 209: 6, 199: 6, 151: 6, 186: 6, 172: 5, 201: 5, 112: 5, 161: 5, 30: 5, 244: 5, 187: 5, 212: 5, 185: 5, 153: 5, 174: 5, 177: 5, 29: 5, 129: 5, 164: 4, 218: 4, 169: 4, 154: 4, 196: 4, 32: 4, 213: 4, 205: 4, 235: 4, 150: 4, 173: 4, 227: 4, 198: 4, 163: 4, 200: 3, 231: 3, 202: 3, 217: 3, 211: 3, 165: 3, 179: 3, 219: 3, 243: 3, 26: 3, 267: 3, 197: 3, 249: 3, 277: 3, 216: 3, 226: 3, 143: 3, 252: 3, 236: 3, 203: 3, 240: 3, 276: 3, 271: 3, 255: 2, 222: 2, 268: 2, 275: 2, 180: 2, 210: 2, 407: 2, 242: 2, 214: 2, 287: 2, 228: 2, 367: 2, 239: 2, 260: 2, 229: 2, 221: 2, 148: 2, 24: 2, 182: 2, 253: 2, 395: 2, 178: 2, 230: 2, 264: 2, 257: 2, 194: 2, 274: 2, 34: 2, 270: 2, 290: 2, 233: 2, 291: 2, 338: 2, 301: 2, 238: 2, 225: 2, 322: 2, 289: 2, 208: 2, 245: 2, 215: 2, 370: 1, 327: 1, 401: 1, 586: 1, 463: 1, 232: 1, 332: 1, 265: 1, 250: 1, 17: 1, 188: 1, 465: 1, 280: 1, 484: 1, 258: 1, 316: 1, 256: 1, 25: 1, 21: 1, 494: 1, 282: 1, 311: 1, 261: 1, 341: 1, 292: 1, 472: 1, 348: 1, 358: 1, 299: 1, 315: 1, 285: 1, 22: 1, 223: 1, 237: 1, 304: 1, 246: 1, 302: 1, 288: 1, 286: 1, 333: 1, 296: 1, 234: 1, 241: 1, 224: 1, 310: 1, 281: 1, 20: 1, 331: 1, 314: 1, 317: 1, 400: 1, 337: 1, 380: 1, 284: 1, 248: 1, 273: 1, 319: 1, 396: 1, 308: 1, 262: 1, 374: 1}

  [choices]
    dtype      : object
    sample val : {'text': array(['a leg muscle relaxing after exercise',
       'a bacterial population in the bloodstream',
       'seve
    nulls      : 0
    n_unique   : unhashable (list/array column)
    len dist   : {2: 2251}

  [answerKey]
    dtype      : object
    sample val : 'B'
    nulls      : 0
    n_unique   : 9
    counts     : {'B': 566, 'C': 545, 'A': 523, 'D': 513, '3': 33, '1': 25, '2': 22, '4': 22, 'E': 2}
    len dist   : {1: 2251}

  ── First 3 examples ──────────────────────────────────────
  ── Example 0 ────────────────────────────────────────
  id                  : 'Mercury_7220990'
  question            : 'Which factor will most likely cause a person to develop a fever?'
  choices             : {'text': ['a leg muscle relaxing after exercise', 'a bacterial population in the bloodstream', 'several viral particles on the skin', 'carbohydrates being digested in the stomach'], 'label': ['A', 'B', 'C', 'D']}
  answerKey           : 'B'

  ── Example 1 ────────────────────────────────────────
  id                  : 'MCAS_2007_8_5189'
  question            : 'Lichens are symbiotic organisms made of green algae and fungi. What do the green algae supply to the fungi in this symbiotic relationship?'
  choices             : {'text': ['carbon dioxide', 'food', 'protection', 'water'], 'label': ['A', 'B', 'C', 'D']}
  answerKey           : 'B'

  ── Example 2 ────────────────────────────────────────
  id                  : 'Mercury_SC_401169'
  question            : 'When a switch is used in an electrical circuit, the switch can'
  choices             : {'text': ['cause the charge to build.', 'increase and decrease the voltage.', 'cause the current to change direction.', 'stop and start the flow of current.'], 'label': ['A', 'B', 'C', 'D']}
  answerKey           : 'D'

  After dedup: 1991 available (excluded 260)
  Returning sampled DataFrame — 500 rows (seed=42)

In [ ]:
print("Columns:", df_arc_easy.columns.tolist())
print()
print("Answer key distribution:")
print(df_arc_easy["answerKey"].value_counts())
print()
print("Number of options per question:")
df_arc_easy["choices"].apply(lambda x: len(x["text"])).value_counts()

Columns: ['id', 'question', 'choices', 'answerKey']

Answer key distribution:
answerKey
D    132
B    117
C    116
A    114
4      7
3      7
2      4
1      3
Name: count, dtype: int64

Number of options per question:

choices
4    498
3      2
Name: count, dtype: int64

## MedQA USMLE

In [ ]:
df_medqa = explore("GBaker/MedQA-USMLE-4-options", name=None, split="train", n=3, sample=500)

============================================================
  GBaker/MedQA-USMLE-4-options  |  config=None
============================================================

README.md:   0%|          | 0.00/654 [00:00<?, ?B/s]

  Available splits : ['train', 'test']
  Loading split    : 'train' ...

phrases_no_exclude_train.jsonl:   0%|          | 0.00/16.2M [00:00<?, ?B/s]

phrases_no_exclude_test.jsonl: 0.00B [00:00, ?B/s]

Generating train split:   0%|          | 0/10178 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1273 [00:00<?, ? examples/s]

  ── Full dataset stats ──────────────────────────────────────
  Total rows  : 10178
  Columns     : ['question', 'answer', 'options', 'meta_info', 'answer_idx', 'metamap_phrases']

  [question]
    dtype      : object
    sample val : 'A 23-year-old pregnant woman at 22 weeks gestation presents with burning upon urination. She states it started 1 day ag
    nulls      : 0
    n_unique   : 10176
    len dist   : {633: 26, 532: 24, 576: 24, 678: 24, 624: 23, 755: 23, 555: 23, 601: 23, 535: 22, 700: 22, 638: 22, 652: 22, 778: 21, 545: 21, 626: 21, 740: 21, 542: 21, 717: 21, 666: 21, 692: 21, 695: 21, 579: 21, 699: 21, 475: 21, 512: 20, 546: 20, 756: 20, 674: 20, 655: 20, 524: 20, 726: 20, 707: 20, 605: 20, 693: 20, 432: 20, 784: 19, 617: 19, 809: 19, 683: 19, 609: 19, 690: 19, 815: 19, 704: 19, 688: 19, 639: 19, 565: 19, 574: 19, 722: 19, 648: 19, 541: 19, 623: 19, 493: 19, 548: 19, 822: 19, 727: 19, 882: 19, 568: 19, 711: 18, 572: 18, 575: 18, 879: 18, 714: 18, 553: 18, 600: 18, 491: 18, 580: 18, 495: 18, 663: 18, 817: 18, 672: 18, 651: 18, 559: 18, 488: 18, 668: 18, 640: 18, 779: 18, 480: 18, 713: 18, 610: 18, 520: 17, 790: 17, 630: 17, 584: 17, 761: 17, 720: 17, 628: 17, 731: 17, 774: 17, 846: 17, 701: 17, 611: 17, 732: 17, 525: 17, 643: 17, 502: 17, 877: 17, 670: 17, 705: 17, 689: 17, 567: 17, 653: 17, 538: 17, 620: 17, 888: 16, 562: 16, 659: 16, 561: 16, 552: 16, 531: 16, 585: 16, 571: 16, 743: 16, 597: 16, 490: 16, 591: 16, 697: 16, 800: 16, 560: 16, 953: 16, 577: 16, 602: 16, 539: 16, 595: 16, 526: 16, 898: 16, 835: 16, 858: 16, 662: 16, 599: 16, 813: 16, 658: 16, 455: 16, 752: 16, 390: 16, 586: 16, 650: 15, 847: 15, 608: 15, 785: 15, 671: 15, 673: 15, 594: 15, 637: 15, 675: 15, 929: 15, 878: 15, 508: 15, 686: 15, 906: 15, 396: 15, 819: 15, 900: 15, 603: 15, 921: 15, 741: 15, 866: 15, 660: 15, 851: 15, 614: 15, 730: 15, 715: 15, 769: 15, 443: 15, 440: 15, 618: 15, 474: 15, 556: 15, 667: 15, 708: 15, 476: 15, 558: 15, 709: 15, 856: 15, 747: 15, 389: 15, 573: 15, 764: 15, 464: 15, 706: 15, 384: 15, 912: 15, 467: 15, 489: 14, 550: 14, 437: 14, 527: 14, 777: 14, 557: 14, 786: 14, 448: 14, 631: 14, 596: 14, 590: 14, 449: 14, 543: 14, 592: 14, 734: 14, 528: 14, 504: 14, 703: 14, 797: 14, 905: 14, 890: 14, 862: 14, 619: 14, 725: 14, 438: 14, 685: 14, 807: 14, 766: 14, 753: 14, 547: 14, 509: 14, 770: 14, 799: 14, 808: 14, 793: 14, 801: 14, 751: 14, 647: 14, 645: 14, 691: 14, 759: 14, 681: 14, 702: 14, 570: 14, 864: 14, 501: 14, 910: 14, 483: 14, 466: 14, 899: 14, 516: 14, 615: 13, 518: 13, 424: 13, 780: 13, 649: 13, 964: 13, 435: 13, 445: 13, 682: 13, 676: 13, 529: 13, 514: 13, 859: 13, 830: 13, 782: 13, 416: 13, 981: 13, 810: 13, 644: 13, 1026: 13, 746: 13, 886: 13, 657: 13, 925: 13, 593: 13, 446: 13, 684: 13, 415: 13, 820: 13, 850: 13, 772: 13, 694: 13, 875: 13, 816: 13, 739: 13, 924: 13, 635: 13, 450: 13, 765: 13, 1056: 13, 665: 13, 507: 13, 903: 13, 587: 13, 698: 13, 950: 13, 787: 13, 616: 13, 503: 13, 632: 13, 750: 13, 533: 13, 876: 13, 441: 13, 729: 13, 661: 13, 621: 13, 470: 13, 948: 13, 880: 13, 523: 13, 506: 13, 664: 13, 511: 13, 669: 13, 622: 13, 710: 13, 869: 13, 589: 13, 998: 13, 814: 13, 505: 13, 718: 13, 472: 12, 417: 12, 737: 12, 380: 12, 917: 12, 872: 12, 408: 12, 680: 12, 868: 12, 938: 12, 471: 12, 767: 12, 629: 12, 811: 12, 544: 12, 566: 12, 783: 12, 656: 12, 975: 12, 771: 12, 831: 12, 728: 12, 821: 12, 646: 12, 430: 12, 983: 12, 818: 12, 431: 12, 634: 12, 409: 12, 794: 12, 985: 12, 395: 12, 487: 12, 1033: 12, 870: 12, 497: 12, 712: 12, 530: 12, 482: 12, 642: 12, 569: 12, 515: 12, 733: 12, 498: 12, 582: 12, 829: 12, 863: 12, 1020: 12, 937: 12, 884: 12, 654: 12, 804: 12, 719: 12, 867: 12, 838: 12, 812: 12, 364: 11, 563: 11, 834: 11, 873: 11, 791: 11, 372: 11, 795: 11, 889: 11, 947: 11, 796: 11, 957: 11, 679: 11, 410: 11, 428: 11, 907: 11, 383: 11, 860: 11, 788: 11, 460: 11, 429: 11, 1013: 11, 421: 11, 861: 11, 914: 11, 485: 11, 958: 11, 447: 11, 469: 11, 454: 11, 844: 11, 625: 11, 942: 11, 486: 11, 540: 11, 393: 11, 853: 11, 798: 11, 749: 11, 423: 11, 1148: 11, 855: 11, 554: 11, 463: 11, 578: 11, 500: 11, 1015: 11, 991: 11, 418: 11, 857: 11, 581: 11, 854: 11, 434: 11, 613: 11, 537: 11, 961: 11, 452: 11, 742: 11, 848: 11, 453: 11, 374: 11, 439: 11, 735: 11, 959: 11, 398: 11, 971: 11, 1024: 11, 534: 11, 461: 11, 901: 11, 583: 11, 468: 10, 745: 10, 427: 10, 946: 10, 465: 10, 386: 10, 776: 10, 902: 10, 473: 10, 598: 10, 895: 10, 736: 10, 517: 10, 426: 10, 636: 10, 1008: 10, 331: 10, 481: 10, 347: 10, 940: 10, 641: 10, 936: 10, 549: 10, 479: 10, 768: 10, 1045: 10, 402: 10, 363: 10, 1034: 10, 823: 10, 833: 10, 716: 10, 422: 10, 781: 10, 696: 10, 943: 10, 494: 10, 499: 10, 836: 10, 960: 10, 993: 10, 803: 10, 826: 10, 350: 10, 892: 10, 789: 10, 1051: 10, 456: 10, 970: 10, 904: 10, 513: 10, 378: 10, 405: 10, 404: 10, 510: 10, 832: 10, 894: 10, 425: 10, 976: 10, 1037: 10, 724: 10, 891: 10, 931: 9, 941: 9, 477: 9, 687: 9, 994: 9, 1083: 9, 1054: 9, 828: 9, 1072: 9, 536: 9, 842: 9, 827: 9, 744: 9, 433: 9, 919: 9, 399: 9, 677: 9, 805: 9, 607: 9, 754: 9, 738: 9, 802: 9, 849: 9, 459: 9, 588: 9, 918: 9, 992: 9, 348: 9, 932: 9, 564: 9, 825: 9, 881: 9, 484: 9, 1107: 9, 1068: 9, 407: 9, 1032: 9, 413: 9, 963: 9, 989: 9, 982: 9, 874: 9, 972: 9, 1004: 9, 419: 9, 723: 9, 885: 9, 478: 9, 1044: 9, 392: 9, 357: 9, 1052: 9, 420: 9, 290: 9, 980: 9, 312: 9, 1006: 9, 979: 9, 954: 9, 351: 9, 382: 9, 366: 9, 315: 9, 762: 9, 935: 9, 887: 9, 522: 9, 337: 9, 327: 9, 280: 9, 923: 9, 839: 9, 997: 9, 411: 8, 1058: 8, 606: 8, 458: 8, 1029: 8, 920: 8, 322: 8, 1000: 8, 1073: 8, 369: 8, 792: 8, 1105: 8, 385: 8, 1007: 8, 1147: 8, 896: 8, 944: 8, 721: 8, 775: 8, 1014: 8, 551: 8, 986: 8, 1108: 8, 457: 8, 988: 8, 758: 8, 349: 8, 845: 8, 757: 8, 1010: 8, 806: 8, 1048: 8, 865: 8, 521: 8, 376: 8, 359: 8, 1016: 8, 1041: 8, 977: 8, 952: 8, 1136: 8, 945: 8, 288: 8, 627: 8, 1093: 8, 612: 8, 909: 8, 346: 8, 824: 8, 1074: 8, 897: 7, 984: 7, 1031: 7, 1232: 7, 1154: 7, 287: 7, 397: 7, 928: 7, 999: 7, 403: 7, 1084: 7, 320: 7, 400: 7, 962: 7, 1190: 7, 317: 7, 436: 7, 1096: 7, 773: 7, 375: 7, 1043: 7, 1030: 7, 1046: 7, 371: 7, 387: 7, 973: 7, 321: 7, 1011: 7, 308: 7, 340: 7, 871: 7, 1017: 7, 519: 7, 1009: 7, 345: 7, 1200: 7, 852: 7, 303: 7, 763: 7, 1050: 7, 492: 7, 412: 7, 913: 7, 995: 7, 951: 7, 1069: 7, 268: 7, 1061: 7, 262: 7, 604: 7, 1071: 7, 1100: 7, 1215: 7, 1116: 6, 1156: 6, 1092: 6, 1157: 6, 307: 6, 356: 6, 260: 6, 1066: 6, 978: 6, 1118: 6, 355: 6, 1062: 6, 343: 6, 230: 6, 968: 6, 843: 6, 401: 6, 297: 6, 365: 6, 1112: 6, 451: 6, 760: 6, 496: 6, 1223: 6, 373: 6, 1027: 6, 1195: 6, 987: 6, 748: 6, 1091: 6, 414: 6, 394: 6, 1021: 6, 289: 6, 271: 6, 293: 6, 1122: 6, 965: 6, 1081: 6, 1018: 6, 1233: 6, 391: 6, 974: 6, 933: 6, 275: 6, 930: 6, 368: 6, 1172: 6, 1077: 6, 955: 6, 442: 6, 313: 6, 1152: 6, 212: 6, 1035: 6, 319: 6, 1139: 6, 1005: 6, 1002: 6, 342: 6, 301: 6, 883: 6, 1123: 6, 244: 6, 939: 6, 284: 6, 908: 6, 1042: 6, 1078: 6, 444: 6, 1222: 6, 1134: 6, 277: 6, 840: 5, 1022: 5, 1025: 5, 1378: 5, 235: 5, 1090: 5, 1088: 5, 1065: 5, 314: 5, 1192: 5, 1012: 5, 1252: 5, 256: 5, 1047: 5, 837: 5, 263: 5, 324: 5, 966: 5, 285: 5, 267: 5, 967: 5, 318: 5, 291: 5, 259: 5, 1067: 5, 926: 5, 370: 5, 257: 5, 1057: 5, 1001: 5, 1158: 5, 1129: 5, 377: 5, 1182: 5, 1101: 5, 302: 5, 1132: 5, 388: 5, 1234: 5, 1113: 5, 1206: 5, 893: 5, 1258: 5, 1003: 5, 911: 5, 1127: 5, 1137: 5, 286: 5, 927: 5, 1250: 5, 1217: 5, 379: 5, 335: 5, 358: 5, 1089: 5, 1244: 5, 1070: 5, 1167: 5, 1099: 5, 922: 5, 341: 5, 1039: 5, 949: 5, 1125: 5, 1121: 5, 1131: 5, 1175: 5, 462: 5, 996: 5, 294: 5, 339: 5, 1049: 5, 1111: 4, 229: 4, 990: 4, 209: 4, 296: 4, 1221: 4, 305: 4, 1211: 4, 915: 4, 1104: 4, 201: 4, 1076: 4, 333: 4, 1293: 4, 1191: 4, 381: 4, 1228: 4, 214: 4, 1170: 4, 316: 4, 1283: 4, 274: 4, 323: 4, 233: 4, 352: 4, 1259: 4, 353: 4, 1212: 4, 278: 4, 1213: 4, 1201: 4, 298: 4, 332: 4, 1019: 4, 1124: 4, 300: 4, 1181: 4, 1159: 4, 1028: 4, 196: 4, 1114: 4, 841: 4, 1332: 4, 1187: 4, 1120: 4, 1130: 4, 270: 4, 1126: 4, 1163: 4, 1086: 4, 367: 4, 264: 4, 248: 4, 1115: 4, 1386: 4, 295: 4, 328: 4, 1075: 4, 1059: 4, 1271: 4, 1186: 4, 1082: 4, 1102: 4, 361: 4, 1144: 4, 1087: 4, 239: 4, 1063: 4, 1197: 4, 1580: 4, 213: 4, 282: 4, 1395: 4, 1168: 4, 916: 4, 1256: 4, 1055: 4, 329: 4, 1106: 4, 272: 3, 1155: 3, 1196: 3, 1161: 3, 1287: 3, 1079: 3, 1596: 3, 226: 3, 1225: 3, 1185: 3, 249: 3, 1318: 3, 1493: 3, 1299: 3, 1171: 3, 1235: 3, 148: 3, 299: 3, 1140: 3, 1169: 3, 1023: 3, 309: 3, 1141: 3, 1060: 3, 1366: 3, 1334: 3, 956: 3, 1164: 3, 1040: 3, 1151: 3, 310: 3, 1322: 3, 1273: 3, 304: 3, 1484: 3, 1208: 3, 334: 3, 338: 3, 406: 3, 1204: 3, 1117: 3, 1349: 3, 1162: 3, 1053: 3, 1260: 3, 934: 3, 1257: 3, 1202: 3, 1085: 3, 1146: 3, 1288: 3, 1424: 3, 1143: 3, 360: 3, 1178: 3, 1094: 3, 283: 3, 1239: 3, 1237: 3, 1119: 3, 1183: 3, 330: 3, 232: 3, 1328: 3, 1193: 3, 1360: 3, 354: 3, 326: 3, 261: 2, 266: 2, 1737: 2, 1348: 2, 123: 2, 1231: 2, 1561: 2, 1207: 2, 1365: 2, 1176: 2, 344: 2, 1485: 2, 1180: 2, 1421: 2, 269: 2, 1519: 2, 1532: 2, 1226: 2, 276: 2, 1184: 2, 1368: 2, 1138: 2, 1458: 2, 1429: 2, 247: 2, 1036: 2, 1153: 2, 198: 2, 1229: 2, 1506: 2, 159: 2, 1224: 2, 1165: 2, 311: 2, 1301: 2, 231: 2, 1177: 2, 1403: 2, 1268: 2, 969: 2, 1203: 2, 1415: 2, 1674: 2, 1292: 2, 171: 2, 1236: 2, 1282: 2, 1354: 2, 1306: 2, 1133: 2, 1279: 2, 1255: 2, 254: 2, 279: 2, 210: 2, 1405: 2, 227: 2, 1314: 2, 1179: 2, 1080: 2, 1442: 2, 1270: 2, 1098: 2, 1227: 2, 246: 2, 1342: 2, 1323: 2, 1459: 2, 258: 2, 1240: 2, 242: 2, 1699: 2, 221: 2, 1265: 2, 216: 2, 1380: 2, 1216: 2, 1269: 2, 1463: 2, 1509: 2, 164: 2, 1274: 2, 1335: 2, 1297: 2, 336: 2, 224: 2, 325: 2, 1220: 2, 253: 2, 1128: 2, 1344: 2, 89: 2, 1689: 2, 1149: 2, 240: 2, 1241: 2, 1482: 2, 1188: 2, 1135: 2, 1410: 2, 1142: 2, 1350: 2, 1214: 2, 1284: 2, 1326: 2, 1097: 2, 1407: 2, 1589: 2, 1411: 2, 83: 2, 1160: 2, 1339: 2, 1358: 2, 1251: 2, 1336: 2, 1109: 2, 1194: 2, 1294: 2, 1110: 2, 243: 2, 186: 2, 1577: 2, 1296: 2, 202: 2, 1298: 2, 1376: 2, 1264: 2, 1330: 2, 1278: 2, 1347: 2, 1247: 2, 1630: 2, 281: 1, 1245: 1, 1550: 1, 1370: 1, 106: 1, 1209: 1, 182: 1, 1261: 1, 1305: 1, 273: 1, 1351: 1, 1724: 1, 111: 1, 143: 1, 125: 1, 190: 1, 3556: 1, 147: 1, 1399: 1, 1728: 1, 1584: 1, 2109: 1, 1291: 1, 1398: 1, 1563: 1, 1173: 1, 1356: 1, 3577: 1, 1174: 1, 1357: 1, 1511: 1, 1536: 1, 138: 1, 1362: 1, 1363: 1, 1324: 1, 208: 1, 1266: 1, 1373: 1, 174: 1, 1249: 1, 1379: 1, 1402: 1, 1711: 1, 1375: 1, 1692: 1, 1567: 1, 1353: 1, 223: 1, 1285: 1, 1492: 1, 1480: 1, 153: 1, 1621: 1, 1540: 1, 1662: 1, 183: 1, 1712: 1, 1337: 1, 1272: 1, 160: 1, 199: 1, 1473: 1, 191: 1, 1479: 1, 92: 1, 1846: 1, 237: 1, 1541: 1, 170: 1, 1595: 1, 1327: 1, 1428: 1, 1877: 1, 1413: 1, 177: 1, 200: 1, 1317: 1, 1542: 1, 1518: 1, 1343: 1, 1673: 1, 1562: 1, 1412: 1, 255: 1, 1800: 1, 172: 1, 1526: 1, 1277: 1, 1325: 1, 1303: 1, 2005: 1, 1392: 1, 1316: 1, 1393: 1, 1409: 1, 1647: 1, 1668: 1, 225: 1, 129: 1, 245: 1, 1467: 1, 1698: 1, 1230: 1, 228: 1, 1361: 1, 1372: 1, 1447: 1, 1145: 1, 1454: 1, 1438: 1, 1307: 1, 2142: 1, 1371: 1, 251: 1, 1189: 1, 1620: 1, 162: 1, 1280: 1, 1387: 1, 1404: 1, 1312: 1, 1477: 1, 1616: 1, 1456: 1, 1824: 1, 1064: 1, 1565: 1, 1262: 1, 1555: 1, 1503: 1, 218: 1, 1513: 1, 1697: 1, 169: 1, 2069: 1, 2015: 1, 2084: 1, 1359: 1, 250: 1, 1166: 1, 236: 1, 1537: 1, 1628: 1, 1253: 1, 113: 1, 1333: 1, 1500: 1, 215: 1, 1515: 1, 137: 1, 1524: 1, 1815: 1, 1539: 1, 1439: 1, 1556: 1, 1103: 1, 66: 1, 161: 1, 1481: 1, 1462: 1, 1394: 1, 265: 1, 1590: 1, 1198: 1, 81: 1, 151: 1, 1319: 1, 173: 1, 1210: 1, 238: 1, 178: 1, 1736: 1, 1437: 1, 1038: 1, 1502: 1, 1427: 1, 1488: 1, 1430: 1, 1472: 1, 1310: 1, 195: 1, 1338: 1, 1095: 1, 184: 1, 1845: 1, 1571: 1, 1341: 1, 1289: 1, 1900: 1, 1435: 1, 1499: 1, 1441: 1, 1821: 1, 70: 1, 1367: 1, 306: 1, 1150: 1, 1219: 1, 168: 1, 166: 1, 1558: 1, 1564: 1, 135: 1, 1723: 1, 1682: 1, 1451: 1, 1382: 1, 1755: 1, 1520: 1, 86: 1, 1417: 1, 145: 1, 1286: 1, 362: 1, 1199: 1, 1352: 1, 2122: 1, 1469: 1, 1381: 1, 1313: 1, 1433: 1, 1624: 1, 1950: 1, 1267: 1, 1434: 1, 1570: 1, 75: 1, 1598: 1, 1448: 1, 292: 1, 1281: 1, 1331: 1, 1295: 1, 205: 1, 1414: 1, 1321: 1, 121: 1, 72: 1, 188: 1, 108: 1, 1786: 1}

  [answer]
    dtype      : object
    sample val : 'Nitrofurantoin'
    nulls      : 0
    n_unique   : 8346
    len dist   : {11: 394, 10: 371, 18: 358, 20: 356, 12: 331, 22: 329, 17: 323, 16: 321, 21: 317, 19: 301, 9: 300, 25: 296, 14: 283, 24: 282, 15: 279, 13: 266, 23: 264, 28: 223, 27: 223, 26: 218, 29: 214, 30: 184, 7: 176, 32: 172, 35: 156, 8: 154, 33: 151, 31: 151, 34: 143, 36: 136, 38: 133, 39: 113, 37: 112, 40: 102, 44: 99, 42: 88, 41: 81, 43: 81, 6: 76, 3: 75, 46: 74, 45: 73, 4: 69, 48: 63, 47: 62, 5: 60, 53: 58, 50: 48, 49: 48, 54: 45, 52: 45, 51: 37, 55: 37, 63: 35, 61: 35, 56: 32, 58: 30, 57: 29, 66: 28, 60: 26, 64: 26, 67: 25, 62: 24, 1: 23, 70: 23, 68: 22, 65: 21, 74: 19, 69: 19, 72: 19, 59: 19, 71: 19, 2: 17, 75: 15, 73: 14, 78: 14, 76: 13, 89: 13, 79: 13, 80: 12, 94: 11, 87: 11, 82: 11, 85: 10, 77: 10, 88: 9, 83: 9, 96: 8, 84: 7, 90: 7, 91: 7, 109: 6, 104: 6, 81: 6, 102: 5, 97: 5, 117: 5, 123: 4, 106: 4, 95: 4, 86: 4, 124: 4, 93: 4, 92: 4, 99: 3, 113: 3, 107: 3, 140: 3, 149: 3, 114: 3, 110: 3, 103: 3, 108: 2, 142: 2, 126: 2, 158: 2, 129: 2, 134: 2, 118: 2, 105: 2, 100: 2, 111: 2, 161: 2, 98: 2, 119: 2, 122: 2, 125: 2, 130: 2, 160: 1, 186: 1, 145: 1, 164: 1, 168: 1, 157: 1, 162: 1, 133: 1, 147: 1, 131: 1, 153: 1, 150: 1, 195: 1, 101: 1, 191: 1, 156: 1, 183: 1, 112: 1, 141: 1, 116: 1, 159: 1, 167: 1, 136: 1, 230: 1, 152: 1}

  [options]
    dtype      : object
    sample val : {'A': 'Ampicillin', 'B': 'Ceftriaxone', 'C': 'Doxycycline', 'D': 'Nitrofurantoin'}
    nulls      : 0
    n_unique   : unhashable (list/array column)
    len dist   : {4: 10178}

  [meta_info]
    dtype      : object
    sample val : 'step2&3'
    nulls      : 0
    n_unique   : 2
    counts     : {'step1': 5629, 'step2&3': 4549}
    len dist   : {5: 5629, 7: 4549}

  [answer_idx]
    dtype      : object
    sample val : 'D'
    nulls      : 0
    n_unique   : 4
    counts     : {'B': 2654, 'A': 2584, 'C': 2557, 'D': 2383}
    len dist   : {1: 10178}

  [metamap_phrases]
    dtype      : object
    sample val : array(['23 year old pregnant woman', 'weeks presents', 'burning',
       'urination', 'states', 'started 1 day', 'worsen
    nulls      : 0
    n_unique   : unhashable (list/array column)
    len dist   : {30: 312, 31: 306, 27: 302, 34: 287, 26: 271, 29: 268, 28: 263, 23: 261, 32: 260, 35: 257, 33: 257, 25: 257, 24: 254, 41: 246, 22: 246, 36: 244, 40: 239, 39: 238, 37: 238, 42: 237, 38: 235, 21: 232, 43: 211, 45: 211, 20: 209, 19: 198, 48: 196, 18: 183, 47: 183, 44: 179, 46: 163, 49: 155, 17: 154, 50: 148, 52: 141, 51: 136, 16: 132, 53: 116, 54: 116, 15: 102, 56: 101, 14: 97, 55: 97, 13: 89, 59: 79, 58: 77, 12: 72, 57: 68, 60: 66, 11: 64, 61: 56, 63: 51, 65: 51, 62: 46, 10: 44, 64: 40, 66: 35, 9: 33, 68: 30, 69: 27, 70: 26, 67: 21, 73: 21, 8: 18, 78: 18, 71: 17, 72: 15, 75: 13, 76: 11, 74: 11, 6: 11, 7: 11, 77: 11, 79: 9, 80: 8, 84: 8, 3: 7, 87: 7, 4: 6, 85: 6, 5: 6, 82: 5, 91: 5, 88: 5, 89: 4, 81: 4, 86: 4, 83: 3, 92: 3, 127: 2, 93: 2, 116: 1, 103: 1, 104: 1, 97: 1, 123: 1, 99: 1, 106: 1, 95: 1, 1: 1, 184: 1, 108: 1, 120: 1, 100: 1, 177: 1}

  ── First 3 examples ──────────────────────────────────────
  ── Example 0 ────────────────────────────────────────
  question            : 'A 23-year-old pregnant woman at 22 weeks gestation presents with burning upon urination. She states it started 1 day ago and has been worsening despite drinking more water and taking cranberry extract. She otherwise feels well and is followed by a doctor for her pregnancy. Her temperature is 97.7°F (36.5°C), blood pressure is 122/77 mmHg, pulse is 80/min, respirations are 19/min, and oxygen saturation is 98% on room air. Physical exam is notable for an absence of costovertebral angle tenderness
  answer              : 'Nitrofurantoin'
  options             : {'A': 'Ampicillin', 'B': 'Ceftriaxone', 'C': 'Doxycycline', 'D': 'Nitrofurantoin'}
  meta_info           : 'step2&3'
  answer_idx          : 'D'
  metamap_phrases     : ['23 year old pregnant woman', 'weeks presents', 'burning', 'urination', 'states', 'started 1 day', 'worsening', 'drinking', 'water', 'taking cranberry extract', 'feels well', 'followed by', 'doctor', 'pregnancy', 'temperature', '97', '36', 'blood pressure', 'mmHg', 'pulse', '80 min', 'respirations', 'min', 'oxygen saturation', '98', 'room air', 'Physical exam', 'notable', 'absence', 'costovertebral angle tenderness', 'gravid uterus', 'following', 'best treatment', 'patient']

  ── Example 1 ────────────────────────────────────────
  question            : 'A 3-month-old baby died suddenly at night while asleep. His mother noticed that he had died only after she awoke in the morning. No cause of death was determined based on the autopsy. Which of the following precautions could have prevented the death of the baby?'
  answer              : 'Placing the infant in a supine position on a firm mattress while sleeping'
  options             : {'A': 'Placing the infant in a supine position on a firm mattress while sleeping', 'B': 'Keeping the infant covered and maintaining a high room temperature', 'C': 'Application of a device to maintain the sleeping position', 'D': 'Avoiding pacifier use during sleep'}
  meta_info           : 'step2&3'
  answer_idx          : 'A'
  metamap_phrases     : ['3 month old baby died', 'night', 'asleep', 'mother', 'died only', 'awoke in', 'morning', 'cause of death', 'based', 'autopsy', 'following precautions', 'prevented', 'death', 'baby']

  ── Example 2 ────────────────────────────────────────
  question            : "A mother brings her 3-week-old infant to the pediatrician's office because she is concerned about his feeding habits. He was born without complications and has not had any medical problems up until this time. However, for the past 4 days, he has been fussy, is regurgitating all of his feeds, and his vomit is yellow in color. On physical exam, the child's abdomen is minimally distended but no other abnormalities are appreciated. Which of the following embryologic errors could account for this pr
  answer              : 'Abnormal migration of ventral pancreatic bud'
  options             : {'A': 'Abnormal migration of ventral pancreatic bud', 'B': 'Complete failure of proximal duodenum to recanalize', 'C': 'Abnormal hypertrophy of the pylorus', 'D': 'Failure of lateral body folds to move ventrally and fuse in the midline'}
  meta_info           : 'step1'
  answer_idx          : 'A'
  metamap_phrases     : ['mother', 'week old infant', "pediatrician's office", 'concerned', 'feeding habits', 'born', 'complications', 'not', 'medical problems', 'time', 'past', 'days', 'fussy', 'regurgitating', 'feeds', 'vomit', 'yellow', 'color', 'physical exam', "child's abdomen", 'distended', 'abnormalities', 'following embryologic errors', 'account', 'presentation']

  After dedup: 9928 available (excluded 250)
  Returning sampled DataFrame — 500 rows (seed=42)

In [ ]:
print("Columns:", df_medqa.columns.tolist())
print()
print("Answer distribution:")
print(df_medqa["answer_idx"].value_counts())
print()
print("Number of options per question:")
df_medqa["options"].apply(lambda x: len(x)).value_counts()
print()
print("Meta info distribution:")
print(df_medqa["meta_info"].value_counts())

Columns: ['question', 'answer', 'options', 'meta_info', 'answer_idx', 'metamap_phrases']

Answer distribution:
answer_idx
B    131
D    127
A    124
C    118
Name: count, dtype: int64

Number of options per question:

Meta info distribution:
meta_info
step1      273
step2&3    227
Name: count, dtype: int64

## SciQA

In [ ]:
df_sciq = explore("allenai/sciq", name=None, split="train", n=3, sample=500)

============================================================
  allenai/sciq  |  config=None
============================================================

README.md: 0.00B [00:00, ?B/s]

  Available splits : ['train', 'validation', 'test']
  Loading split    : 'train' ...

data/train-00000-of-00001.parquet:   0%|          | 0.00/3.99M [00:00<?, ?B/s]

data/validation-00000-of-00001.parquet:   0%|          | 0.00/339k [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/343k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/11679 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/1000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1000 [00:00<?, ? examples/s]

  ── Full dataset stats ──────────────────────────────────────
  Total rows  : 11679
  Columns     : ['question', 'distractor3', 'distractor1', 'distractor2', 'correct_answer', 'support']

  [question]
    dtype      : object
    sample val : 'What type of organism is commonly used in preparation of foods such as cheese and yogurt?'
    nulls      : 0
    n_unique   : 11609
    len dist   : {61: 213, 64: 199, 51: 192, 69: 189, 59: 185, 58: 182, 57: 182, 52: 182, 56: 181, 55: 180, 50: 179, 54: 178, 66: 177, 49: 175, 62: 175, 67: 172, 71: 172, 60: 170, 68: 170, 53: 170, 65: 167, 73: 165, 72: 162, 63: 162, 48: 162, 77: 158, 70: 156, 76: 154, 44: 151, 74: 148, 83: 148, 46: 147, 82: 147, 45: 147, 81: 144, 47: 144, 79: 143, 75: 142, 42: 138, 43: 137, 85: 135, 80: 134, 78: 133, 87: 130, 90: 129, 84: 128, 86: 124, 89: 119, 91: 118, 88: 111, 92: 109, 95: 107, 41: 106, 39: 102, 38: 98, 40: 96, 98: 95, 93: 92, 99: 91, 102: 89, 97: 89, 94: 88, 104: 87, 36: 79, 96: 76, 100: 75, 106: 73, 101: 73, 37: 69, 105: 69, 35: 67, 107: 64, 103: 59, 113: 59, 109: 58, 114: 57, 116: 54, 110: 53, 34: 51, 108: 51, 111: 42, 119: 41, 33: 40, 120: 39, 121: 39, 125: 38, 123: 38, 112: 38, 117: 38, 115: 37, 32: 36, 124: 35, 118: 33, 31: 32, 30: 32, 131: 29, 136: 29, 29: 28, 122: 27, 127: 24, 130: 24, 129: 23, 126: 22, 128: 22, 151: 21, 137: 20, 143: 18, 138: 18, 28: 17, 132: 17, 134: 17, 145: 16, 133: 16, 147: 16, 139: 15, 27: 14, 150: 14, 144: 13, 154: 12, 146: 12, 26: 12, 142: 12, 140: 12, 148: 11, 153: 11, 164: 10, 135: 10, 155: 10, 25: 10, 149: 10, 156: 9, 159: 9, 23: 8, 161: 8, 24: 8, 152: 8, 141: 8, 158: 7, 178: 7, 22: 7, 170: 6, 183: 6, 179: 6, 163: 6, 171: 6, 176: 5, 177: 5, 203: 5, 169: 5, 157: 5, 166: 4, 212: 4, 167: 4, 160: 4, 165: 4, 21: 4, 172: 4, 181: 4, 173: 4, 202: 3, 174: 3, 168: 3, 190: 3, 189: 3, 175: 3, 235: 3, 200: 2, 211: 2, 205: 2, 197: 2, 228: 2, 20: 2, 289: 2, 162: 2, 210: 2, 185: 2, 193: 2, 198: 2, 182: 2, 187: 2, 291: 2, 19: 2, 275: 2, 191: 2, 180: 2, 199: 2, 276: 2, 194: 2, 196: 2, 230: 2, 192: 2, 236: 1, 340: 1, 298: 1, 280: 1, 247: 1, 208: 1, 227: 1, 243: 1, 232: 1, 233: 1, 221: 1, 215: 1, 313: 1, 14: 1, 184: 1, 231: 1, 240: 1, 16: 1, 207: 1, 248: 1, 269: 1, 295: 1, 201: 1, 250: 1, 209: 1, 206: 1, 244: 1, 261: 1, 358: 1, 399: 1, 217: 1, 296: 1, 264: 1, 369: 1, 348: 1, 223: 1, 253: 1, 279: 1, 257: 1, 239: 1, 216: 1, 309: 1, 17: 1, 226: 1, 388: 1, 186: 1}

  [distractor3]
    dtype      : object
    sample val : 'viruses'
    nulls      : 0
    n_unique   : 6960
    len dist   : {7: 1174, 8: 1137, 9: 1131, 6: 971, 5: 938, 10: 793, 11: 773, 12: 583, 4: 538, 13: 516, 14: 484, 15: 454, 16: 370, 17: 321, 18: 286, 3: 205, 19: 189, 20: 176, 21: 145, 22: 97, 23: 75, 24: 68, 25: 36, 2: 34, 26: 25, 27: 25, 1: 25, 29: 20, 28: 18, 32: 13, 30: 10, 34: 8, 37: 6, 38: 5, 31: 5, 36: 4, 35: 4, 33: 3, 41: 2, 51: 2, 43: 2, 57: 1, 39: 1, 59: 1, 52: 1, 40: 1, 55: 1, 63: 1, 45: 1}

  [distractor1]
    dtype      : object
    sample val : 'protozoa'
    nulls      : 0
    n_unique   : 6991
    len dist   : {8: 1150, 7: 1128, 9: 1098, 6: 1041, 5: 869, 10: 838, 11: 775, 12: 561, 4: 547, 13: 538, 14: 493, 15: 437, 17: 334, 16: 317, 18: 291, 19: 229, 3: 219, 20: 175, 21: 156, 22: 106, 23: 71, 24: 65, 25: 36, 2: 33, 1: 27, 27: 25, 26: 25, 28: 17, 31: 10, 29: 10, 32: 10, 34: 9, 38: 7, 30: 6, 35: 4, 33: 3, 37: 3, 44: 2, 43: 2, 39: 2, 56: 1, 57: 1, 46: 1, 54: 1, 40: 1, 48: 1, 42: 1, 45: 1, 41: 1, 36: 1}

  [distractor2]
    dtype      : object
    sample val : 'gymnosperms'
    nulls      : 0
    n_unique   : 6900
    len dist   : {7: 1154, 9: 1136, 8: 1114, 6: 1018, 5: 926, 10: 809, 11: 790, 12: 588, 4: 527, 13: 505, 14: 492, 15: 475, 16: 339, 17: 338, 18: 271, 19: 207, 20: 198, 3: 190, 21: 140, 22: 94, 23: 72, 24: 58, 2: 34, 25: 33, 27: 27, 26: 26, 1: 23, 30: 14, 29: 11, 31: 9, 28: 9, 35: 7, 33: 7, 32: 7, 34: 6, 36: 5, 37: 3, 50: 3, 39: 3, 44: 2, 53: 2, 38: 2, 41: 1, 43: 1, 45: 1, 46: 1, 62: 1}

  [correct_answer]
    dtype      : object
    sample val : 'mesophilic organisms'
    nulls      : 0
    n_unique   : 5896
    len dist   : {7: 1046, 8: 1043, 9: 948, 6: 934, 11: 920, 5: 845, 10: 801, 14: 674, 12: 648, 13: 533, 4: 435, 15: 432, 16: 370, 17: 366, 18: 247, 19: 226, 20: 213, 3: 194, 21: 154, 22: 136, 24: 85, 23: 69, 25: 63, 26: 53, 2: 44, 27: 29, 28: 27, 1: 25, 30: 19, 29: 14, 32: 11, 34: 10, 33: 9, 31: 9, 35: 6, 39: 6, 37: 5, 44: 5, 40: 5, 36: 4, 38: 3, 51: 2, 41: 2, 54: 2, 43: 1, 45: 1, 53: 1, 49: 1, 50: 1, 55: 1, 67: 1}

  [support]
    dtype      : object
    sample val : 'Mesophiles grow best in moderate temperature, typically between 25°C and 40°C (77°F and 104°F). Mesophiles are often fo
    nulls      : 0
    n_unique   : 10474
    len dist   : {0: 1198, 76: 38, 80: 36, 68: 36, 73: 35, 72: 34, 86: 32, 65: 30, 88: 29, 223: 29, 59: 29, 94: 29, 69: 28, 64: 28, 71: 28, 252: 27, 152: 27, 79: 27, 248: 27, 173: 27, 84: 26, 82: 26, 163: 26, 224: 26, 231: 26, 364: 26, 193: 26, 190: 26, 75: 25, 70: 25, 89: 25, 85: 25, 355: 25, 66: 25, 250: 24, 206: 24, 228: 23, 92: 23, 58: 23, 101: 23, 323: 23, 87: 23, 207: 23, 268: 23, 191: 23, 109: 23, 50: 23, 342: 23, 116: 23, 284: 23, 218: 23, 275: 23, 103: 23, 95: 23, 220: 23, 194: 23, 343: 23, 157: 22, 153: 22, 99: 22, 266: 22, 159: 22, 108: 22, 235: 22, 97: 22, 83: 22, 239: 22, 98: 22, 211: 22, 141: 22, 126: 22, 122: 22, 107: 22, 264: 22, 283: 22, 221: 21, 93: 21, 77: 21, 232: 21, 138: 21, 278: 21, 144: 21, 200: 21, 263: 21, 242: 21, 253: 21, 254: 21, 143: 20, 60: 20, 396: 20, 282: 20, 100: 20, 341: 20, 201: 20, 237: 20, 57: 20, 158: 20, 192: 20, 317: 20, 309: 20, 53: 20, 56: 20, 91: 20, 188: 20, 304: 20, 133: 20, 114: 20, 90: 19, 281: 19, 286: 19, 229: 19, 183: 19, 313: 19, 184: 19, 164: 19, 241: 19, 233: 19, 356: 19, 169: 19, 314: 19, 315: 19, 175: 19, 104: 19, 305: 19, 54: 19, 386: 19, 67: 19, 380: 19, 407: 18, 238: 18, 149: 18, 123: 18, 182: 18, 269: 18, 310: 18, 423: 18, 276: 18, 291: 18, 230: 18, 349: 18, 161: 18, 137: 18, 112: 18, 312: 18, 280: 18, 316: 18, 81: 18, 262: 18, 215: 18, 354: 18, 240: 18, 330: 18, 166: 18, 134: 18, 146: 18, 384: 18, 145: 18, 150: 18, 185: 18, 198: 18, 385: 18, 119: 18, 102: 17, 48: 17, 181: 17, 332: 17, 234: 17, 411: 17, 167: 17, 55: 17, 406: 17, 222: 17, 214: 17, 392: 17, 227: 17, 205: 17, 297: 17, 274: 17, 257: 17, 260: 17, 448: 17, 127: 17, 328: 17, 374: 17, 340: 17, 428: 17, 363: 17, 470: 17, 379: 17, 324: 17, 267: 17, 401: 17, 203: 17, 367: 17, 391: 17, 63: 17, 178: 17, 296: 17, 259: 17, 96: 17, 131: 16, 74: 16, 555: 16, 156: 16, 478: 16, 155: 16, 251: 16, 180: 16, 246: 16, 388: 16, 271: 16, 151: 16, 560: 16, 117: 16, 272: 16, 294: 16, 321: 16, 49: 16, 376: 16, 331: 16, 256: 16, 350: 16, 209: 16, 413: 16, 61: 16, 277: 16, 177: 16, 245: 16, 147: 16, 195: 16, 492: 16, 270: 16, 197: 16, 247: 16, 132: 16, 217: 16, 348: 16, 424: 16, 408: 16, 453: 16, 509: 16, 139: 16, 416: 16, 172: 16, 389: 15, 329: 15, 390: 15, 213: 15, 236: 15, 199: 15, 106: 15, 318: 15, 371: 15, 360: 15, 327: 15, 52: 15, 417: 15, 160: 15, 377: 15, 311: 15, 300: 15, 320: 15, 154: 15, 212: 15, 346: 15, 358: 15, 404: 15, 395: 15, 136: 15, 351: 15, 301: 15, 292: 15, 189: 15, 499: 15, 336: 15, 273: 15, 381: 15, 244: 15, 148: 14, 176: 14, 187: 14, 249: 14, 265: 14, 434: 14, 255: 14, 474: 14, 204: 14, 110: 14, 333: 14, 338: 14, 288: 14, 115: 14, 295: 14, 426: 14, 168: 14, 502: 14, 382: 14, 402: 14, 142: 13, 609: 13, 62: 13, 564: 13, 460: 13, 369: 13, 394: 13, 322: 13, 462: 13, 353: 13, 422: 13, 299: 13, 375: 13, 347: 13, 436: 13, 243: 13, 431: 13, 446: 13, 210: 13, 366: 13, 361: 13, 405: 13, 290: 13, 393: 13, 186: 13, 111: 13, 216: 13, 225: 13, 430: 13, 170: 13, 443: 13, 51: 13, 285: 13, 410: 13, 468: 13, 303: 13, 325: 13, 279: 13, 518: 13, 472: 12, 365: 12, 501: 12, 496: 12, 171: 12, 373: 12, 372: 12, 469: 12, 335: 12, 520: 12, 121: 12, 466: 12, 293: 12, 287: 12, 219: 12, 298: 12, 527: 12, 352: 12, 370: 12, 420: 12, 459: 12, 475: 12, 129: 12, 357: 12, 174: 12, 130: 12, 162: 12, 400: 12, 541: 12, 202: 12, 113: 12, 78: 12, 486: 12, 383: 12, 615: 12, 135: 12, 525: 12, 140: 12, 577: 11, 414: 11, 128: 11, 196: 11, 498: 11, 473: 11, 47: 11, 337: 11, 378: 11, 491: 11, 432: 11, 523: 11, 289: 11, 208: 11, 661: 11, 165: 11, 319: 11, 418: 11, 482: 11, 120: 11, 179: 11, 387: 11, 307: 11, 258: 11, 425: 11, 592: 11, 306: 11, 226: 11, 454: 11, 397: 11, 403: 11, 359: 11, 344: 11, 497: 10, 464: 10, 534: 10, 573: 10, 345: 10, 326: 10, 495: 10, 484: 10, 507: 10, 540: 10, 544: 10, 528: 10, 561: 10, 441: 10, 440: 10, 530: 10, 562: 10, 571: 10, 437: 10, 538: 10, 442: 10, 261: 10, 458: 10, 575: 10, 579: 10, 605: 10, 105: 10, 398: 10, 535: 10, 612: 10, 706: 9, 46: 9, 481: 9, 485: 9, 591: 9, 124: 9, 483: 9, 125: 9, 568: 9, 118: 9, 549: 9, 626: 9, 524: 9, 368: 9, 531: 9, 455: 9, 558: 9, 302: 9, 339: 9, 506: 9, 465: 9, 444: 9, 536: 9, 435: 9, 433: 9, 513: 9, 649: 9, 508: 9, 514: 9, 522: 9, 45: 9, 587: 9, 646: 9, 471: 9, 537: 9, 449: 9, 461: 8, 505: 8, 504: 8, 399: 8, 450: 8, 480: 8, 548: 8, 552: 8, 607: 8, 421: 8, 308: 8, 539: 8, 642: 8, 590: 8, 668: 8, 557: 8, 362: 8, 542: 8, 517: 8, 631: 8, 447: 8, 547: 8, 487: 8, 334: 8, 494: 8, 598: 8, 409: 8, 477: 8, 415: 8, 567: 8, 427: 8, 745: 8, 636: 8, 419: 8, 698: 8, 516: 8, 578: 7, 654: 7, 412: 7, 511: 7, 510: 7, 572: 7, 489: 7, 645: 7, 545: 7, 596: 7, 563: 7, 565: 7, 519: 7, 712: 7, 778: 7, 584: 7, 611: 7, 694: 7, 608: 7, 445: 7, 681: 7, 488: 7, 559: 7, 515: 7, 439: 7, 613: 7, 942: 7, 452: 7, 526: 7, 543: 7, 777: 7, 619: 7, 776: 7, 647: 7, 490: 7, 659: 7, 628: 7, 456: 7, 737: 7, 687: 7, 641: 7, 576: 7, 570: 7, 620: 6, 581: 6, 828: 6, 621: 6, 769: 6, 551: 6, 650: 6, 670: 6, 813: 6, 677: 6, 585: 6, 660: 6, 479: 6, 580: 6, 438: 6, 610: 6, 614: 6, 688: 6, 657: 6, 627: 6, 556: 6, 639: 6, 675: 6, 932: 6, 503: 6, 553: 6, 735: 6, 643: 6, 963: 6, 476: 6, 648: 6, 512: 6, 493: 6, 758: 6, 618: 6, 982: 6, 606: 6, 603: 6, 574: 6, 566: 5, 593: 5, 546: 5, 604: 5, 44: 5, 858: 5, 457: 5, 693: 5, 740: 5, 1036: 5, 529: 5, 622: 5, 664: 5, 623: 5, 747: 5, 637: 5, 42: 5, 857: 5, 820: 5, 597: 5, 672: 5, 1081: 5, 802: 5, 451: 5, 683: 5, 971: 5, 600: 5, 901: 5, 701: 5, 736: 5, 39: 5, 888: 5, 708: 5, 834: 5, 40: 5, 916: 5, 41: 5, 674: 5, 583: 5, 791: 5, 685: 5, 1388: 5, 754: 5, 739: 5, 902: 5, 601: 5, 1139: 4, 1006: 4, 467: 4, 692: 4, 569: 4, 994: 4, 632: 4, 656: 4, 1005: 4, 640: 4, 1010: 4, 1342: 4, 862: 4, 588: 4, 900: 4, 599: 4, 878: 4, 667: 4, 669: 4, 704: 4, 730: 4, 759: 4, 734: 4, 837: 4, 855: 4, 869: 4, 1211: 4, 550: 4, 1044: 4, 1123: 4, 884: 4, 1240: 4, 521: 4, 819: 4, 760: 4, 651: 4, 43: 4, 1292: 4, 1018: 4, 860: 4, 1168: 4, 697: 4, 554: 4, 709: 4, 717: 4, 586: 4, 966: 4, 748: 4, 799: 4, 429: 4, 533: 4, 1506: 4, 1468: 4, 898: 4, 700: 4, 833: 4, 1657: 4, 767: 4, 838: 4, 463: 4, 1060: 4, 1077: 4, 703: 4, 679: 4, 616: 4, 719: 4, 1290: 4, 859: 4, 1796: 4, 956: 4, 830: 4, 829: 4, 904: 4, 1206: 4, 699: 4, 892: 4, 686: 4, 633: 4, 1073: 4, 723: 4, 678: 4, 1170: 4, 929: 4, 750: 4, 1299: 4, 789: 3, 877: 3, 1368: 3, 594: 3, 880: 3, 990: 3, 743: 3, 744: 3, 893: 3, 751: 3, 638: 3, 1125: 3, 1178: 3, 726: 3, 630: 3, 812: 3, 1747: 3, 1112: 3, 680: 3, 825: 3, 1647: 3, 910: 3, 1189: 3, 866: 3, 1335: 3, 1083: 3, 711: 3, 814: 3, 1021: 3, 919: 3, 973: 3, 716: 3, 1324: 3, 856: 3, 1928: 3, 1130: 3, 741: 3, 658: 3, 766: 3, 1358: 3, 653: 3, 665: 3, 1409: 3, 1369: 3, 875: 3, 853: 3, 742: 3, 955: 3, 1037: 3, 1281: 3, 1336: 3, 1518: 3, 689: 3, 1049: 3, 882: 3, 764: 3, 1205: 3, 1180: 3, 872: 3, 854: 3, 816: 3, 629: 3, 1353: 3, 761: 3, 844: 3, 722: 3, 1042: 3, 800: 3, 897: 3, 655: 3, 696: 3, 876: 3, 1307: 3, 727: 3, 783: 3, 889: 3, 1162: 3, 953: 3, 930: 3, 1835: 3, 976: 3, 770: 3, 635: 3, 1642: 3, 1322: 3, 1101: 3, 1306: 3, 790: 3, 765: 3, 912: 3, 991: 3, 1537: 3, 1057: 3, 1357: 3, 894: 3, 780: 3, 1811: 3, 1272: 3, 1682: 3, 713: 3, 1119: 3, 752: 3, 861: 3, 786: 3, 824: 3, 1058: 3, 960: 3, 1341: 3, 774: 3, 617: 3, 918: 3, 836: 3, 1789: 3, 707: 3, 796: 3, 842: 3, 1028: 3, 879: 3, 1293: 3, 1064: 3, 808: 3, 848: 3, 1050: 3, 772: 3, 1145: 3, 1003: 3, 1017: 3, 1136: 3, 845: 3, 718: 3, 684: 3, 1235: 3, 1141: 3, 2256: 2, 2628: 2, 1704: 2, 1612: 2, 1508: 2, 934: 2, 1477: 2, 1181: 2, 1569: 2, 1140: 2, 1452: 2, 729: 2, 989: 2, 974: 2, 1510: 2, 1279: 2, 1328: 2, 931: 2, 1171: 2, 652: 2, 914: 2, 1318: 2, 1392: 2, 1088: 2, 1106: 2, 1072: 2, 935: 2, 1804: 2, 1746: 2, 1676: 2, 937: 2, 1329: 2, 1424: 2, 1720: 2, 899: 2, 1031: 2, 823: 2, 1751: 2, 1236: 2, 1019: 2, 2120: 2, 1447: 2, 1266: 2, 671: 2, 725: 2, 1542: 2, 1253: 2, 1857: 2, 908: 2, 771: 2, 1354: 2, 1308: 2, 1023: 2, 827: 2, 1418: 2, 1938: 2, 1519: 2, 792: 2, 787: 2, 1282: 2, 582: 2, 1498: 2, 1068: 2, 1438: 2, 1172: 2, 731: 2, 1482: 2, 1517: 2, 1271: 2, 1606: 2, 663: 2, 1743: 2, 1041: 2, 1065: 2, 1849: 2, 1094: 2, 992: 2, 967: 2, 1445: 2, 1309: 2, 1053: 2, 927: 2, 957: 2, 762: 2, 1135: 2, 1934: 2, 1052: 2, 1104: 2, 984: 2, 1263: 2, 1121: 2, 1533: 2, 794: 2, 1045: 2, 1584: 2, 1089: 2, 2307: 2, 873: 2, 1466: 2, 1330: 2, 1574: 2, 818: 2, 972: 2, 1214: 2, 1199: 2, 1161: 2, 804: 2, 1265: 2, 532: 2, 850: 2, 634: 2, 1230: 2, 695: 2, 784: 2, 2222: 2, 1863: 2, 1128: 2, 846: 2, 589: 2, 710: 2, 2123: 2, 865: 2, 1805: 2, 500: 2, 595: 2, 797: 2, 1071: 2, 1653: 2, 1400: 2, 890: 2, 870: 2, 1792: 2, 940: 2, 1132: 2, 775: 2, 1425: 2, 2058: 2, 732: 2, 1891: 2, 1561: 2, 2461: 2, 781: 2, 779: 2, 1217: 2, 1426: 2, 995: 2, 1436: 2, 738: 2, 1120: 2, 852: 2, 1347: 2, 851: 2, 1363: 2, 1547: 2, 1750: 2, 1989: 2, 958: 2, 1361: 2, 785: 2, 1182: 2, 885: 2, 867: 2, 1079: 2, 821: 2, 928: 2, 803: 2, 1689: 2, 1076: 2, 1775: 2, 702: 2, 676: 2, 1233: 2, 644: 2, 2393: 2, 1490: 2, 1004: 2, 1535: 2, 1596: 2, 1413: 2, 1416: 2, 883: 2, 1198: 2, 1219: 2, 1038: 2, 1360: 2, 1055: 2, 1594: 2, 798: 2, 1137: 2, 1107: 2, 997: 2, 691: 2, 822: 2, 922: 2, 1221: 2, 1446: 2, 793: 2, 896: 2, 849: 2, 1453: 2, 1011: 2, 1936: 2, 1069: 2, 909: 2, 1729: 2, 788: 2, 1411: 2, 1111: 2, 1439: 2, 1289: 2, 1389: 2, 1509: 2, 1147: 2, 1012: 2, 1602: 2, 1352: 2, 1395: 2, 1592: 2, 1391: 2, 1708: 2, 1365: 2, 1513: 2, 1673: 2, 1985: 2, 1157: 2, 1208: 2, 1380: 2, 1026: 2, 895: 2, 757: 2, 863: 2, 1127: 2, 835: 2, 1549: 2, 981: 2, 724: 2, 950: 2, 1390: 2, 1179: 2, 1020: 2, 921: 2, 1458: 2, 1815: 2, 1932: 2, 839: 2, 2409: 1, 1090: 1, 715: 1, 1456: 1, 1497: 1, 1643: 1, 2541: 1, 666: 1, 2155: 1, 1496: 1, 1616: 1, 1203: 1, 801: 1, 1881: 1, 2147: 1, 1813: 1, 1714: 1, 1702: 1, 841: 1, 1210: 1, 864: 1, 1961: 1, 2811: 1, 2095: 1, 1969: 1, 1565: 1, 886: 1, 2299: 1, 1766: 1, 1155: 1, 2432: 1, 975: 1, 1756: 1, 831: 1, 2166: 1, 1829: 1, 1994: 1, 2137: 1, 2173: 1, 1099: 1, 1035: 1, 1382: 1, 1605: 1, 1973: 1, 2809: 1, 2062: 1, 1008: 1, 2682: 1, 1414: 1, 968: 1, 1613: 1, 2226: 1, 2354: 1, 1861: 1, 811: 1, 1323: 1, 1762: 1, 1431: 1, 1222: 1, 1915: 1, 1450: 1, 1968: 1, 1457: 1, 1795: 1, 2782: 1, 1483: 1, 1945: 1, 2428: 1, 1566: 1, 1556: 1, 1022: 1, 2089: 1, 2700: 1, 1724: 1, 2360: 1, 1167: 1, 1965: 1, 1177: 1, 2310: 1, 1595: 1, 1000: 1, 1070: 1, 2898: 1, 2203: 1, 2154: 1, 2231: 1, 1822: 1, 1528: 1, 2300: 1, 941: 1, 1692: 1, 1797: 1, 1250: 1, 1876: 1, 2850: 1, 1732: 1, 2263: 1, 1462: 1, 1639: 1, 2117: 1, 2292: 1, 1032: 1, 1129: 1, 1007: 1, 3559: 1, 1455: 1, 1420: 1, 1717: 1, 1684: 1, 1753: 1, 1239: 1, 2649: 1, 1175: 1, 1589: 1, 2015: 1, 843: 1, 2616: 1, 1348: 1, 907: 1, 2532: 1, 1977: 1, 1394: 1, 1254: 1, 2515: 1, 1421: 1, 1707: 1, 1912: 1, 1552: 1, 925: 1, 944: 1, 2301: 1, 1169: 1, 2080: 1, 1138: 1, 946: 1, 1257: 1, 2555: 1, 1183: 1, 1785: 1, 1296: 1, 1563: 1, 1193: 1, 926: 1, 1067: 1, 1432: 1, 1261: 1, 2346: 1, 1375: 1, 1814: 1, 1986: 1, 2566: 1, 755: 1, 2237: 1, 1629: 1, 2329: 1, 1512: 1, 1459: 1, 1525: 1, 999: 1, 1294: 1, 1590: 1, 1661: 1, 624: 1, 1558: 1, 1158: 1, 673: 1, 1374: 1, 1773: 1, 1825: 1, 1444: 1, 1063: 1, 1879: 1, 2044: 1, 1047: 1, 1311: 1, 1554: 1, 1485: 1, 1924: 1, 1159: 1, 1950: 1, 2239: 1, 2103: 1, 1854: 1, 1474: 1, 2126: 1, 1831: 1, 1298: 1, 2565: 1, 1906: 1, 1376: 1, 1620: 1, 1536: 1, 1599: 1, 1340: 1, 2275: 1, 1866: 1, 2495: 1, 2241: 1, 1830: 1, 2099: 1, 1184: 1, 2175: 1, 2063: 1, 1899: 1, 1406: 1, 1479: 1, 2017: 1, 1853: 1, 1463: 1, 1275: 1, 1303: 1, 662: 1, 37: 1, 2121: 1, 1727: 1, 1637: 1, 980: 1, 1467: 1, 1009: 1, 1176: 1, 1437: 1, 1872: 1, 1274: 1, 1713: 1, 1326: 1, 1339: 1, 2018: 1, 35: 1, 1297: 1, 1149: 1, 714: 1, 2001: 1, 2794: 1, 1126: 1, 1215: 1, 993: 1, 1187: 1, 891: 1, 2819: 1, 1226: 1, 1499: 1, 2423: 1, 721: 1, 1530: 1, 1013: 1, 1245: 1, 2125: 1, 1868: 1, 1625: 1, 2211: 1, 1779: 1, 1956: 1, 2663: 1, 1781: 1, 1154: 1, 1244: 1, 1441: 1, 1974: 1, 756: 1, 2465: 1, 805: 1, 2953: 1, 1972: 1, 1415: 1, 1543: 1, 2695: 1, 2651: 1, 1611: 1, 1488: 1, 1816: 1, 1691: 1, 749: 1, 1134: 1, 1526: 1, 3405: 1, 2601: 1, 2198: 1, 2048: 1, 832: 1, 1819: 1, 1744: 1, 1954: 1, 1163: 1, 983: 1, 2153: 1, 1098: 1, 1886: 1, 915: 1, 2415: 1, 2028: 1, 2487: 1, 2051: 1, 31: 1, 1588: 1, 2269: 1, 1738: 1, 1024: 1, 1998: 1, 1694: 1, 1560: 1, 1662: 1, 1527: 1, 2097: 1, 1443: 1, 1277: 1, 1262: 1, 2424: 1, 1790: 1, 1285: 1, 1025: 1, 1786: 1, 1242: 1, 2053: 1, 1465: 1, 1677: 1, 1315: 1, 2208: 1, 1220: 1, 1091: 1, 2245: 1, 1033: 1, 1531: 1, 1723: 1, 1609: 1, 2255: 1, 602: 1, 1706: 1, 1964: 1, 1503: 1, 2331: 1, 1268: 1, 2087: 1, 1383: 1, 1559: 1, 2149: 1, 1749: 1, 1988: 1, 1103: 1, 1164: 1, 2462: 1, 1273: 1, 1538: 1, 2156: 1, 1080: 1, 1733: 1, 2081: 1, 1092: 1, 1152: 1, 906: 1, 1718: 1, 1039: 1, 1540: 1, 1675: 1, 1856: 1, 1359: 1, 1384: 1, 1225: 1, 3434: 1, 1051: 1, 1096: 1, 1283: 1, 1486: 1, 1212: 1, 1153: 1, 2229: 1, 2091: 1, 1195: 1, 1659: 1, 1246: 1, 1310: 1, 1093: 1, 1327: 1, 2223: 1, 868: 1, 996: 1, 1641: 1, 1404: 1, 3132: 1, 1371: 1, 1349: 1, 988: 1, 2614: 1, 1600: 1, 1507: 1, 2721: 1, 1953: 1, 1711: 1, 795: 1, 1113: 1, 938: 1, 1798: 1, 682: 1, 720: 1, 2396: 1, 1635: 1, 1845: 1, 810: 1, 1869: 1, 1287: 1, 1405: 1, 979: 1, 3369: 1, 2002: 1, 1770: 1, 1229: 1, 38: 1, 782: 1, 1870: 1, 2537: 1, 1930: 1, 2192: 1, 2084: 1, 2343: 1, 1579: 1, 964: 1, 1066: 1, 763: 1, 1740: 1, 2218: 1, 1516: 1, 1269: 1, 933: 1, 1156: 1, 1234: 1, 1665: 1, 3227: 1, 1663: 1, 1102: 1, 939: 1, 1909: 1, 1705: 1, 728: 1, 1480: 1, 1001: 1, 1715: 1, 2725: 1, 1487: 1, 924: 1, 809: 1, 1131: 1, 887: 1, 2129: 1, 1188: 1, 1319: 1, 2852: 1, 1534: 1, 3326: 1, 2180: 1, 1959: 1, 2505: 1, 1767: 1, 1712: 1, 2020: 1, 1655: 1, 1396: 1, 1249: 1, 1644: 1, 2145: 1, 1110: 1, 806: 1, 961: 1, 1196: 1, 2722: 1, 1999: 1, 1548: 1, 1218: 1, 917: 1, 1345: 1, 1410: 1, 936: 1, 913: 1, 2359: 1, 2264: 1, 1464: 1, 1888: 1, 773: 1, 1828: 1, 952: 1, 1343: 1, 1501: 1, 1709: 1, 1656: 1, 1472: 1, 1317: 1, 1698: 1, 847: 1, 2184: 1, 2650: 1, 911: 1, 815: 1, 1545: 1, 1987: 1, 1630: 1, 1670: 1, 1942: 1, 1397: 1, 2887: 1, 1931: 1, 1399: 1, 2100: 1, 1150: 1, 1591: 1, 969: 1, 1061: 1, 1757: 1, 1735: 1, 1227: 1, 1975: 1, 1122: 1, 2336: 1, 1114: 1, 2085: 1, 1683: 1, 3206: 1, 1771: 1, 948: 1, 2220: 1, 1841: 1, 2019: 1, 1654: 1, 1806: 1, 1385: 1, 1316: 1, 1173: 1, 1546: 1, 1555: 1, 733: 1, 1801: 1, 1754: 1, 1758: 1, 1652: 1, 2247: 1, 1386: 1, 3197: 1, 1799: 1, 1820: 1, 1087: 1, 3084: 1, 1370: 1, 2013: 1, 1288: 1, 1521: 1, 1276: 1, 1030: 1, 1433: 1, 2456: 1, 1029: 1, 1864: 1, 807: 1, 871: 1, 1582: 1, 690: 1, 1056: 1, 1074: 1, 2670: 1, 1618: 1, 2574: 1, 2316: 1, 1251: 1, 1971: 1, 1800: 1, 2411: 1, 2521: 1, 2108: 1, 1115: 1, 1996: 1, 2104: 1, 1850: 1, 2489: 1, 2376: 1, 2187: 1, 2365: 1, 2320: 1, 2068: 1, 2469: 1, 2188: 1, 1492: 1, 1095: 1, 977: 1, 1223: 1, 1301: 1, 1578: 1, 1259: 1, 1286: 1, 1108: 1}

  ── First 3 examples ──────────────────────────────────────
  ── Example 0 ────────────────────────────────────────
  question            : 'What type of organism is commonly used in preparation of foods such as cheese and yogurt?'
  distractor3         : 'viruses'
  distractor1         : 'protozoa'
  distractor2         : 'gymnosperms'
  correct_answer      : 'mesophilic organisms'

In [ ]:
print("Columns:", df_sciq.columns.tolist())
print()

Columns: ['question', 'distractor3', 'distractor1', 'distractor2', 'correct_answer', 'support']

# Dataset Gathering

## Analyzing the columns and datatypes

In [ ]:
import pandas as pd
from pprint import pformat

# Make pandas less aggressive about truncation
pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", 2000)
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

datasets = {
    "MMLU": df_mmlu,
    "AQUA-RAT": df_aqua,
    "ReClor": df_reclor,
    "MedQA": df_medqa,
    "ARC-Easy": df_arc_easy,
    "SciQ": df_sciq,
}

def print_full_sample(df, name):
    print("=" * 120)
    print(f"{name} Columns: {df.columns.tolist()}")
    print()

    print(f"{name} dtypes:")
    print(df.dtypes.to_string())
    print()

    if len(df) == 0:
        print(f"{name} sample: <empty dataframe>")
        return

    sample = df.iloc[0]
    print(f"{name} first sample, full values:")
    for col in df.columns:
        value = sample[col]
        print(f"\n[{col}]")
        print(f"  pandas dtype: {df[col].dtype}")
        print(f"  python type : {type(value)}")
        print(f"  value       : {pformat(value, width=200, compact=False, sort_dicts=False)}")

for name, df in datasets.items():
    print_full_sample(df, name)
    print()

========================================================================================================================
MMLU Columns: ['question', 'subject', 'choices', 'answer']

MMLU dtypes:
question    object
subject     object
choices     object
answer       int64

MMLU first sample, full values:

[question]
  pandas dtype: object
  python type : <class 'str'>
  value       : ("This is Bruce's Noodle House. We have different kinds of noodles. A large bowl of noodles with mutton  is only 4 dollars, and 3 dollars for a medium  bowl. Each bowl of beef noodles is just 3.5 "
 'dollars. And a large bowl of chicken noodles is 2 dollars. Each bowl of pork noodles is just 3.5 dollars. One dollar is for a large bowl of vegetable noodles. Come and enjoy the delicious noodles '
 'here! If you order any meat noodles, fruit is free . If you are too busy to come. Please call us at 2888998, and you will get the food in half an hour. Our Noodle House is open for 24 hours a day, '
 "from Monday afternoon to Sunday. Tom's family would like two large bowls of chicken noodles and a medium bowl of mutton noodles. They will pay    _   for the food.")

[subject]
  pandas dtype: object
  python type : <class 'str'>
  value       : ''

[choices]
  pandas dtype: object
  python type : <class 'numpy.ndarray'>
  value       : array(['$6', '$7', '$5', '$8'], dtype=object)

[answer]
  pandas dtype: int64
  python type : <class 'numpy.int64'>
  value       : np.int64(1)

========================================================================================================================
AQUA-RAT Columns: ['question', 'options', 'rationale', 'correct']

AQUA-RAT dtypes:
question     object
options      object
rationale    object
correct      object

AQUA-RAT first sample, full values:

[question]
  pandas dtype: object
  python type : <class 'str'>
  value       : ('Seven fencers participate in a fencing championship. Assuming all competitors have an equal chance of winning, how many possibilities are there with respect to how a first-place and second-place '
 'medal can be awarded?')

[options]
  pandas dtype: object
  python type : <class 'numpy.ndarray'>
  value       : array(['A)30', 'B)36', 'C)42', 'D)48', 'E)49'], dtype=object)

[rationale]
  pandas dtype: object
  python type : <class 'str'>
  value       : '7*6 = 42\nThe answer is C.'

[correct]
  pandas dtype: object
  python type : <class 'str'>
  value       : 'C'

========================================================================================================================
ReClor Columns: ['answers', 'context', 'label', 'id_string', 'question']

ReClor dtypes:
answers      object
context      object
label         int64
id_string    object
question     object

ReClor first sample, full values:

[answers]
  pandas dtype: object
  python type : <class 'numpy.ndarray'>
  value       : array(['It presumes that being a well-educated professional is relevant to being guilty or innocent.',
       'It fails to consider that Ziegler might have been insane when he worked as a consultant.',
       "It fails to consider the possibility that Ziegler's being sane after the shooting is an indication that he was sane at the time of the shooting.",
       "It concludes on the basis of evidence against Ziegler's being sane that there is a lack of evidence for Ziegler's being sane."],
      dtype=object)

[context]
  pandas dtype: object
  python type : <class 'str'>
  value       : ('Attorney for Ziegler: My client continued to do consulting work between the time of his arrest for attempted murder and the start of this trial. But I contend that Ziegler was insane at the time '
 'that he fired the shot. This is the only reasonable conclusion to draw from the fact that the accusers have submitted no evidence that he was sane at the time he pulled the trigger, only that he '
 'was sane some time after he did so.')

[label]
  pandas dtype: int64
  python type : <class 'numpy.int64'>
  value       : np.int64(2)

[id_string]
  pandas dtype: object
  python type : <class 'str'>
  value       : 'train_3110'

[question]
  pandas dtype: object
  python type : <class 'str'>
  value       : "Which one of the following most accurately describes a flaw in the reasoning of Ziegler's attorney?"

========================================================================================================================
MedQA Columns: ['question', 'answer', 'options', 'meta_info', 'answer_idx', 'metamap_phrases']

MedQA dtypes:
question           object
answer             object
options            object
meta_info          object
answer_idx         object
metamap_phrases    object

MedQA first sample, full values:

[question]
  pandas dtype: object
  python type : <class 'str'>
  value       : ('A 33-year-old woman with Crohn’s disease colitis presents to her physician after 2 days of photophobia and blurred vision. She has had no similar episodes in the past. She has no abdominal pain or '
 'diarrhea and takes mesalazine, azathioprine, and prednisone as maintenance therapy. Her vital signs are within normal range. Examination of the eyes shows conjunctival injection. The physical '
 'examination is otherwise normal. Slit-lamp examination by an ophthalmologist shows evidence of inflammation in the anterior chamber. Which of the following is the most appropriate modification to '
 'this patient’s medication at this time?')

[answer]
  pandas dtype: object
  python type : <class 'str'>
  value       : 'Increasing dose of prednisone'

[options]
  pandas dtype: object
  python type : <class 'dict'>
  value       : {'A': 'Adding infliximab', 'B': 'Discontinuing sulfasalazine', 'C': 'Increasing dose of prednisone', 'D': 'No modification of therapy at this time'}

[meta_info]
  pandas dtype: object
  python type : <class 'str'>
  value       : 'step2&3'

[answer_idx]
  pandas dtype: object
  python type : <class 'str'>
  value       : 'C'

[metamap_phrases]
  pandas dtype: object
  python type : <class 'numpy.ndarray'>
  value       : array(['year old woman', 'Crohns disease colitis presents', 'physician',
       '2 days', 'photophobia', 'blurred vision', 'similar episodes',
       'past', 'abdominal pain', 'diarrhea', 'takes mesalazine',
       'azathioprine', 'prednisone', 'maintenance therapy', 'vital signs',
       'normal range', 'Examination of',
       'eyes shows conjunctival injection', 'physical examination',
       'normal', 'Slit-lamp examination',
       'ophthalmologist shows evidence', 'inflammation',
       'anterior chamber', 'following', 'most appropriate modification',
       'patients medication', 'time'], dtype=object)

========================================================================================================================
ARC-Easy Columns: ['id', 'question', 'choices', 'answerKey']

ARC-Easy dtypes:
id           object
question     object
choices      object
answerKey    object

ARC-Easy first sample, full values:

[id]
  pandas dtype: object
  python type : <class 'str'>
  value       : 'Mercury_7038710'

[question]
  pandas dtype: object
  python type : <class 'str'>
  value       : 'Which is an example of substances reacting chemically?'

[choices]
  pandas dtype: object
  python type : <class 'dict'>
  value       : {'text': array(['iron and oxygen forming rust',
       'paper being cut into small pieces', 'chocolate melting in a pan',
       'flour and sugar mixed together in a bowl'], dtype=object),
 'label': array(['A', 'B', 'C', 'D'], dtype=object)}

[answerKey]
  pandas dtype: object
  python type : <class 'str'>
  value       : 'A'

========================================================================================================================
SciQ Columns: ['question', 'distractor3', 'distractor1', 'distractor2', 'correct_answer', 'support']

SciQ dtypes:
question          object
distractor3       object
distractor1       object
distractor2       object
correct_answer    object
support           object

SciQ first sample, full values:

[question]
  pandas dtype: object
  python type : <class 'str'>
  value       : 'What type of science is the application of science to answer questions related to the law?'

[distractor3]
  pandas dtype: object
  python type : <class 'str'>
  value       : 'physics'

[distractor1]
  pandas dtype: object
  python type : <class 'str'>
  value       : 'ecology'

[distractor2]
  pandas dtype: object
  python type : <class 'str'>
  value       : 'biologic'

[correct_answer]
  pandas dtype: object
  python type : <class 'str'>
  value       : 'forensic'

[support]
  pandas dtype: object
  python type : <class 'str'>
  value       : ('Forensic Scientist Forensic science is the application of science to answer questions related to the law. Biologists as well as chemists and biochemists can be forensic scientists. Forensic '
 'scientists provide scientific evidence for use in courts, and their job involves examining trace material associated with crimes. Interest in forensic science has increased in the last few years, '
 'possibly because of popular television shows that feature forensic scientists on the job. Also, the development of molecular techniques and the establishment of DNA databases have updated the '
 'types of work that forensic scientists can do. Their job activities are primarily related to crimes against people such as murder, rape, and assault. Their work involves analyzing samples such as '
 'hair, blood, and other body fluids and also processing DNA (Figure 1.13) found in many different environments and materials. Forensic scientists also analyze other biological evidence left at '
 'crime scenes, such as insect parts or pollen grains. Students who want to pursue careers in forensic science will most likely be required to take chemistry and biology courses as well as some '
 'intensive math courses.')

## Normalize and Combine them

In [ ]:
import re
import numpy as np
import pandas as pd

pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", 2000)
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

datasets = {
    "MMLU": df_mmlu,
    "AQUA-RAT": df_aqua,
    "ReClor": df_reclor,
    "MedQA": df_medqa,
    "ARC-Easy": df_arc_easy,
    "SciQ": df_sciq,
}

def to_list(x):
    if x is None:
        return None
    if isinstance(x, np.ndarray):
        return x.tolist()
    if isinstance(x, (list, tuple)):
        return list(x)
    return [x]

def idx_to_label(i):
    return chr(ord("A") + int(i))

def clean_text(x):
    if x is None:
        return None
    return str(x).strip()

def parse_labeled_option(option):
    """
    Parses strings like:
      A)120960
      B. 42
      C: text
    Returns (label, text). If no label prefix is found, returns (None, original_text).
    """
    s = clean_text(option)
    m = re.match(r"^\s*([A-Z])[\)\.\:\-]?\s*(.*)\s*$", s)
    if m and m.group(1) in {"A", "B", "C", "D", "E", "F", "G", "H"}:
        return m.group(1), m.group(2)
    return None, s

def make_choice_payload(labels, texts):
    labels = [clean_text(x) for x in labels]
    texts = [clean_text(x) for x in texts]
    return labels, texts

def normalize_mmlu(df):
    rows = []
    for _, r in df.iterrows():
        texts = to_list(r["choices"])
        labels = [idx_to_label(i) for i in range(len(texts))]
        gold_index = int(r["answer"])
        gold_label = labels[gold_index] if gold_index < len(labels) else None
        gold_text = texts[gold_index] if gold_index < len(texts) else None

        rows.append({
            "source": "MMLU",
            "task_type": "mcq",
            "source_id": None,
            "question": clean_text(r["question"]),
            "context": None,
            "choice_labels": labels,
            "choice_texts": texts,
            "gold_label": gold_label,
            "gold_index": gold_index,
            "gold_text": gold_text,
            "explanation": None,
            "subject": clean_text(r["subject"]),
            "meta": {}
        })
    return pd.DataFrame(rows)

def normalize_aqua(df):
    rows = []
    for _, r in df.iterrows():
        raw_options = to_list(r["options"])
        parsed = [parse_labeled_option(opt) for opt in raw_options]
        labels = [p[0] if p[0] is not None else idx_to_label(i) for i, p in enumerate(parsed)]
        texts = [p[1] for p in parsed]

        gold_label = clean_text(r["correct"])
        gold_index = labels.index(gold_label) if gold_label in labels else None
        gold_text = texts[gold_index] if gold_index is not None and gold_index < len(texts) else None

        rows.append({
            "source": "AQUA-RAT",
            "task_type": "mcq_rationale",
            "source_id": None,
            "question": clean_text(r["question"]),
            "context": None,
            "choice_labels": labels,
            "choice_texts": texts,
            "gold_label": gold_label,
            "gold_index": gold_index,
            "gold_text": gold_text,
            "explanation": clean_text(r["rationale"]),
            "subject": None,
            "meta": {}
        })
    return pd.DataFrame(rows)

def normalize_reclor(df):
    rows = []
    for _, r in df.iterrows():
        texts = to_list(r["answers"])
        labels = [idx_to_label(i) for i in range(len(texts))]
        gold_index = int(r["label"])
        gold_label = labels[gold_index] if gold_index < len(labels) else None
        gold_text = texts[gold_index] if gold_index < len(texts) else None

        rows.append({
            "source": "ReClor",
            "task_type": "reading_comp_mcq",
            "source_id": clean_text(r["id_string"]),
            "question": clean_text(r["question"]),
            "context": clean_text(r["context"]),
            "choice_labels": labels,
            "choice_texts": texts,
            "gold_label": gold_label,
            "gold_index": gold_index,
            "gold_text": gold_text,
            "explanation": None,
            "subject": None,
            "meta": {}
        })
    return pd.DataFrame(rows)

def normalize_medqa(df):
    rows = []
    for _, r in df.iterrows():
        opt = r["options"]
        if isinstance(opt, dict):
            labels = [clean_text(k) for k in opt.keys()]
            texts = [clean_text(v) for v in opt.values()]
        else:
            labels, texts = make_choice_payload([], to_list(opt))

        gold_label = clean_text(r["answer_idx"])
        gold_index = labels.index(gold_label) if gold_label in labels else None
        gold_text = clean_text(r["answer"])

        rows.append({
            "source": "MedQA",
            "task_type": "mcq_medical",
            "source_id": None,
            "question": clean_text(r["question"]),
            "context": clean_text(r["meta_info"]),
            "choice_labels": labels,
            "choice_texts": texts,
            "gold_label": gold_label,
            "gold_index": gold_index,
            "gold_text": gold_text,
            "explanation": None,
            "subject": None,
            "meta": {
                "metamap_phrases": to_list(r["metamap_phrases"])
            }
        })
    return pd.DataFrame(rows)

def normalize_arc_easy(df):
    rows = []
    for _, r in df.iterrows():
        choices = r["choices"]
        if isinstance(choices, dict):
            labels = to_list(choices.get("label"))
            texts = to_list(choices.get("text"))
        else:
            texts = to_list(choices)
            labels = [idx_to_label(i) for i in range(len(texts))]

        gold_label = clean_text(r["answerKey"])
        gold_index = labels.index(gold_label) if gold_label in labels else None
        gold_text = texts[gold_index] if gold_index is not None and gold_index < len(texts) else None

        rows.append({
            "source": "ARC-Easy",
            "task_type": "mcq_science",
            "source_id": clean_text(r["id"]),
            "question": clean_text(r["question"]),
            "context": None,
            "choice_labels": labels,
            "choice_texts": texts,
            "gold_label": gold_label,
            "gold_index": gold_index,
            "gold_text": gold_text,
            "explanation": None,
            "subject": None,
            "meta": {}
        })
    return pd.DataFrame(rows)

def normalize_sciq(df):
    rows = []
    for _, r in df.iterrows():
        texts = [
            clean_text(r["correct_answer"]),
            clean_text(r["distractor1"]),
            clean_text(r["distractor2"]),
            clean_text(r["distractor3"]),
        ]
        labels = [idx_to_label(i) for i in range(len(texts))]
        gold_index = 0
        gold_label = labels[gold_index]
        gold_text = texts[gold_index]

        rows.append({
            "source": "SciQ",
            "task_type": "mcq_science",
            "source_id": None,
            "question": clean_text(r["question"]),
            "context": clean_text(r["support"]),
            "choice_labels": labels,
            "choice_texts": texts,
            "gold_label": gold_label,
            "gold_index": gold_index,
            "gold_text": gold_text,
            "explanation": None,
            "subject": None,
            "meta": {"choice_order": "constructed_from_correct_plus_distractors"}
        })
    return pd.DataFrame(rows)

normalized_frames = [
    normalize_mmlu(df_mmlu),
    normalize_aqua(df_aqua),
    normalize_reclor(df_reclor),
    normalize_medqa(df_medqa),
    normalize_arc_easy(df_arc_easy),
    normalize_sciq(df_sciq),
]

combined = pd.concat(normalized_frames, ignore_index=True)

# Optional sanity checks
print("Combined shape:", combined.shape)
print(combined["source"].value_counts(dropna=False).to_string())
print()

for src in combined["source"].unique():
    row = combined[combined["source"] == src].iloc[0]
    print("=" * 120)
    print(src)
    for col in ["question", "context", "choice_labels", "choice_texts", "gold_label", "gold_index", "gold_text", "explanation", "subject", "meta"]:
        print(f"\n[{col}]")
        print(row[col])

Combined shape: (3000, 13)
source
MMLU        500
AQUA-RAT    500
ReClor      500
MedQA       500
ARC-Easy    500
SciQ        500

========================================================================================================================
MMLU

[question]
This is Bruce's Noodle House. We have different kinds of noodles. A large bowl of noodles with mutton  is only 4 dollars, and 3 dollars for a medium  bowl. Each bowl of beef noodles is just 3.5 dollars. And a large bowl of chicken noodles is 2 dollars. Each bowl of pork noodles is just 3.5 dollars. One dollar is for a large bowl of vegetable noodles. Come and enjoy the delicious noodles here! If you order any meat noodles, fruit is free . If you are too busy to come. Please call us at 2888998, and you will get the food in half an hour. Our Noodle House is open for 24 hours a day, from Monday afternoon to Sunday. Tom's family would like two large bowls of chicken noodles and a medium bowl of mutton noodles. They will pay    _   for the food.

[context]
None

[choice_labels]
['A', 'B', 'C', 'D']

[choice_texts]
['$6', '$7', '$5', '$8']

[gold_label]
B

[gold_index]
1

[gold_text]
$7

[explanation]
None

[subject]


[meta]
{}
========================================================================================================================
AQUA-RAT

[question]
Seven fencers participate in a fencing championship. Assuming all competitors have an equal chance of winning, how many possibilities are there with respect to how a first-place and second-place medal can be awarded?

[context]
None

[choice_labels]
['A', 'B', 'C', 'D', 'E']

[choice_texts]
['30', '36', '42', '48', '49']

[gold_label]
C

[gold_index]
2

[gold_text]
42

[explanation]
7*6 = 42
The answer is C.

[subject]
None

[meta]
{}
========================================================================================================================
ReClor

[question]
Which one of the following most accurately describes a flaw in the reasoning of Ziegler's attorney?

[context]
Attorney for Ziegler: My client continued to do consulting work between the time of his arrest for attempted murder and the start of this trial. But I contend that Ziegler was insane at the time that he fired the shot. This is the only reasonable conclusion to draw from the fact that the accusers have submitted no evidence that he was sane at the time he pulled the trigger, only that he was sane some time after he did so.

[choice_labels]
['A', 'B', 'C', 'D']

[choice_texts]
['It presumes that being a well-educated professional is relevant to being guilty or innocent.', 'It fails to consider that Ziegler might have been insane when he worked as a consultant.', "It fails to consider the possibility that Ziegler's being sane after the shooting is an indication that he was sane at the time of the shooting.", "It concludes on the basis of evidence against Ziegler's being sane that there is a lack of evidence for Ziegler's being sane."]

[gold_label]
C

[gold_index]
2

[gold_text]
It fails to consider the possibility that Ziegler's being sane after the shooting is an indication that he was sane at the time of the shooting.

[explanation]
None

[subject]
None

[meta]
{}
========================================================================================================================
MedQA

[question]
A 33-year-old woman with Crohn’s disease colitis presents to her physician after 2 days of photophobia and blurred vision. She has had no similar episodes in the past. She has no abdominal pain or diarrhea and takes mesalazine, azathioprine, and prednisone as maintenance therapy. Her vital signs are within normal range. Examination of the eyes shows conjunctival injection. The physical examination is otherwise normal. Slit-lamp examination by an ophthalmologist shows evidence of inflammation in the anterior chamber. Which of the following is the most appropriate modification to this patient’s medication at this time?

[context]
step2&3

[choice_labels]
['A', 'B', 'C', 'D']

[choice_texts]
['Adding infliximab', 'Discontinuing sulfasalazine', 'Increasing dose of prednisone', 'No modification of therapy at this time']

[gold_label]
C

[gold_index]
2

[gold_text]
Increasing dose of prednisone

[explanation]
None

[subject]
None

[meta]
{'metamap_phrases': ['year old woman', 'Crohns disease colitis presents', 'physician', '2 days', 'photophobia', 'blurred vision', 'similar episodes', 'past', 'abdominal pain', 'diarrhea', 'takes mesalazine', 'azathioprine', 'prednisone', 'maintenance therapy', 'vital signs', 'normal range', 'Examination of', 'eyes shows conjunctival injection', 'physical examination', 'normal', 'Slit-lamp examination', 'ophthalmologist shows evidence', 'inflammation', 'anterior chamber', 'following', 'most appropriate modification', 'patients medication', 'time']}
========================================================================================================================
ARC-Easy

[question]
Which is an example of substances reacting chemically?

[context]
None

[choice_labels]
['A', 'B', 'C', 'D']

[choice_texts]
['iron and oxygen forming rust', 'paper being cut into small pieces', 'chocolate melting in a pan', 'flour and sugar mixed together in a bowl']

[gold_label]
A

[gold_index]
0

[gold_text]
iron and oxygen forming rust

[explanation]
None

[subject]
None

[meta]
{}
========================================================================================================================
SciQ

[question]
What type of science is the application of science to answer questions related to the law?

[context]
Forensic Scientist Forensic science is the application of science to answer questions related to the law. Biologists as well as chemists and biochemists can be forensic scientists. Forensic scientists provide scientific evidence for use in courts, and their job involves examining trace material associated with crimes. Interest in forensic science has increased in the last few years, possibly because of popular television shows that feature forensic scientists on the job. Also, the development of molecular techniques and the establishment of DNA databases have updated the types of work that forensic scientists can do. Their job activities are primarily related to crimes against people such as murder, rape, and assault. Their work involves analyzing samples such as hair, blood, and other body fluids and also processing DNA (Figure 1.13) found in many different environments and materials. Forensic scientists also analyze other biological evidence left at crime scenes, such as insect parts or pollen grains. Students who want to pursue careers in forensic science will most likely be required to take chemistry and biology courses as well as some intensive math courses.

[choice_labels]
['A', 'B', 'C', 'D']

[choice_texts]
['forensic', 'ecology', 'biologic', 'physics']

[gold_label]
A

[gold_index]
0

[gold_text]
forensic

[explanation]
None

[subject]
None

[meta]
{'choice_order': 'constructed_from_correct_plus_distractors'}

## Verification

In [ ]:
import pandas as pd

print("=" * 80)
print("BASIC INFO")
print("=" * 80)
print("Shape:", combined.shape)
print()
print("Source distribution:")
print(combined["source"].value_counts().to_string())
print()

# -----------------------------
# Missing values
# -----------------------------
print("=" * 80)
print("MISSING VALUES")
print("=" * 80)
print(combined.isna().sum().to_string())
print()

# -----------------------------
# Choice consistency
# -----------------------------
def check_choices(row):
    labels = row["choice_labels"]
    texts = row["choice_texts"]
    if not isinstance(labels, list) or not isinstance(texts, list):
        return False
    if len(labels) != len(texts):
        return False
    if len(labels) < 2:
        return False
    return True

combined["valid_choices"] = combined.apply(check_choices, axis=1)

print("=" * 80)
print("CHOICE STRUCTURE")
print("=" * 80)
print("Invalid choice rows:", (~combined["valid_choices"]).sum())
print()

# -----------------------------
# Gold alignment checks
# -----------------------------
def check_gold(row):
    labels = row["choice_labels"]
    texts = row["choice_texts"]
    g_label = row["gold_label"]
    g_index = row["gold_index"]
    g_text = row["gold_text"]

    try:
        if g_index is not None:
            if g_index >= len(texts):
                return False
            if texts[g_index] != g_text:
                return False

        if g_label is not None and g_label in labels:
            idx = labels.index(g_label)
            if texts[idx] != g_text:
                return False

        return True
    except Exception:
        return False

combined["valid_gold"] = combined.apply(check_gold, axis=1)

print("=" * 80)
print("GOLD ALIGNMENT")
print("=" * 80)
print("Invalid gold rows:", (~combined["valid_gold"]).sum())
print()

# -----------------------------
# Empty / bad questions
# -----------------------------
combined["bad_question"] = combined["question"].isna() | (combined["question"].str.strip() == "")

print("=" * 80)
print("QUESTION QUALITY")
print("=" * 80)
print("Empty questions:", combined["bad_question"].sum())
print()

# -----------------------------
# Summary of all failures
# -----------------------------
combined["any_issue"] = ~(
    combined["valid_choices"] &
    combined["valid_gold"] &
    ~combined["bad_question"]
)

print("=" * 80)
print("OVERALL DATA HEALTH")
print("=" * 80)
print("Rows with any issue:", combined["any_issue"].sum())
print()

# Optional: inspect bad rows
bad_rows = combined[combined["any_issue"]]
if len(bad_rows) > 0:
    print("Sample problematic row:")
    print(bad_rows.iloc[0].to_dict())

================================================================================
BASIC INFO
================================================================================
Shape: (3000, 13)

Source distribution:
source
MMLU        500
AQUA-RAT    500
ReClor      500
MedQA       500
ARC-Easy    500
SciQ        500

================================================================================
MISSING VALUES
================================================================================
source              0
task_type           0
source_id        2000
question            0
context          1500
choice_labels       0
choice_texts        0
gold_label          0
gold_index          0
gold_text           0
explanation      2500
subject          2500
meta                0

================================================================================
CHOICE STRUCTURE
================================================================================
Invalid choice rows: 0

================================================================================
GOLD ALIGNMENT
================================================================================
Invalid gold rows: 0

================================================================================
QUESTION QUALITY
================================================================================
Empty questions: 0

================================================================================
OVERALL DATA HEALTH
================================================================================
Rows with any issue: 0

In [ ]:
# Drop verification columns if present
cols_to_drop = [
    "valid_choices",
    "valid_gold",
    "bad_question",
    "any_issue"
]

clean_combined = combined.drop(columns=[c for c in cols_to_drop if c in combined.columns])

# Save as pickle (preserves Python objects like lists/dicts cleanly)
clean_combined.to_pickle("combined_dataset.pkl")

# Save as JSON (more portable, but larger)
clean_combined.to_json("combined_dataset.json", orient="records", indent=2)

# Optional: CSV (not ideal for nested fields, but usable)
clean_combined.to_csv("combined_dataset.csv", index=False)

print("Saved:")
print(" - combined_dataset.pkl")
print(" - combined_dataset.json")
print(" - combined_dataset.csv")

Saved:
 - combined_dataset.pkl
 - combined_dataset.json
 - combined_dataset.csv

In [ ]:
from sklearn.model_selection import train_test_split

train_df, temp_df = train_test_split(clean_combined, test_size=600, random_state=42, stratify=clean_combined["source"])
val_df, test_df = train_test_split(temp_df, test_size=300, random_state=42, stratify=temp_df["source"])

print(f"Train: {len(train_df)}")
print(train_df["source"].value_counts().to_string())
print(f"\nVal: {len(val_df)}")
print(val_df["source"].value_counts().to_string())
print(f"\nTest: {len(test_df)}")
print(test_df["source"].value_counts().to_string())

train_df.to_csv("train.csv", index=False)
val_df.to_csv("validation.csv", index=False)
test_df.to_csv("test.csv", index=False)

from google.colab import files
files.download("train.csv")
files.download("validation.csv")
files.download("test.csv")

Train: 2400
source
MedQA       400
AQUA-RAT    400
ReClor      400
MMLU        400
ARC-Easy    400
SciQ        400

Val: 300
source
ReClor      50
MedQA       50
SciQ        50
ARC-Easy    50
MMLU        50
AQUA-RAT    50

Test: 300
source
SciQ        50
MedQA       50
MMLU        50
ARC-Easy    50
ReClor      50
AQUA-RAT    50